Fix issues in AddCapacity Modal
red-hat-storage/odf-console pull request #101
Opened 2022-01-19 09:52 UTC by bipuladh

StorageClassDropdown now references the component.
![Screenshot from 2022-01-19 15-36-51](https://user-images.githubusercontent.com/54092533/150106634-5207d55d-eaa8-4083-b696-6e35cfa0d4c2.png)

2022-01-19 10:02 UTC, afreen23 requested changes

2022-01-19 10:02 UTC, afreen23 commented on packages/odf/modals/add-capacity/add-capacity-modal.tsx
> +const StorageClassDropdown = (ScModule as any).StorageClassDropdown;
Why this ?

2022-01-19 10:07 UTC, bipuladh commented
Changes in the kubevirt SDK, Previously it was exporting the component now it is exporting the whole module but under the same name. 
Reference: 
https://github.com/openshift/console/commit/e94be3265f2ced9c4aca1587ee3ac011a665d534#diff-5e83ab3d6fc56a1651d0621bac9b3d901cadaa18c868b99c4582262fbbb1e453L175-L176

2022-01-19 10:07 UTC, bipuladh commented on packages/odf/modals/add-capacity/add-capacity-modal.tsx
> +const StorageClassDropdown = (ScModule as any).StorageClassDropdown;
See https://github.com/red-hat-storage/odf-console/pull/101#issuecomment-1016277766

2022-01-19 10:09 UTC, afreen23 approved these changes
/lgtm

2022-01-19 10:09 UTC, afreen23 commented on packages/odf/modals/add-capacity/add-capacity-modal.tsx
> +const StorageClassDropdown = (ScModule as any).StorageClassDropdown;
Makes sense now, thanks.

2022-01-19 11:21 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-19 12:21 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-19 13:02 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-20 05:33 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-20 05:35 UTC, vbnrh commented
/lgtm

2022-01-20 12:55 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-21 09:37 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-21 11:59 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-01-21 12:00 UTC, vbnrh commented
/lgtm

2022-01-21 12:01 UTC, merged