Added required field check in wizard flow - WIP
red-hat-storage/odf-console pull request #1039
Opened 2023-09-07 13:17 UTC by GowthamShanmugam

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2236436

2023-09-11 10:52 UTC, GowthamShanmugam commented
[Screencast from 2023-09-11 16-20-43.webm](https://github.com/red-hat-storage/odf-console/assets/15073590/10cab075-1f72-4f4a-b150-7d4572c14807)

2023-09-12 05:52 UTC, SanjalKatiyar requested changes

2023-09-12 05:52 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
> +  const [isValidationEnabled, setEnableValidation] = React.useState(false);
nits:
```suggestion
  const [isValidationEnabled, setIsValidationEnabled] = React.useState(false);
```

2023-09-12 05:52 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
> +    }
```suggestion
    if (canJumpToNext) {
      setStepIdReached(stepIdReached <= stepId ? stepId + 1 : stepIdReached);
      onNext();
      setEnableValidation(false);
    } else setEnableValidation(true);
```

2023-09-12 05:52 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
> +          isValidationEnabled && !selectedLabels?.length ? 'error' : 'default'
can we create a small util function for mco ?
`const getValidatedProp = (error: boolean) => error ? 'error' : 'default'`;

2023-09-12 05:52 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
> +  !!dataPolicy?.placementControlInfo?.every(
```suggestion
  !!dataPolicy.placementControlInfo.every(
```

2023-09-12 05:52 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
> +  !!dataPolicy?.placementControlInfo?.every(
if `!!dataPolicy?.placementControlInfo?.length` is true then only we will reach to next condition... and if that is happening it means all fields are present...

2023-09-12 05:52 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
> +    (drpc) => !!drpc?.pvcSelector?.length
```suggestion
    (drpc) => !!drpc.pvcSelector?.length
```

2023-09-12 05:53 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/helper/pvc-details-wizard-content.tsx
> +          isValidationEnabled && !selectedLabels?.length ? 'error' : 'default'
PF also have a constant for 'error' & 'default', we can use that directly...

2023-09-12 09:35 UTC, GowthamShanmugam commented on packages/mco/components/modals/app-manage-policies/helper/assign-policy-view-footer.tsx
> +  !!dataPolicy?.placementControlInfo?.every(
ack

2023-09-13 12:04 UTC, SanjalKatiyar commented
/cherry-pick release-4.14

2023-09-13 12:04 UTC, SanjalKatiyar commented
/cherry-pick release-4.14-compatibility

2023-09-13 12:05 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-manage-policies/assign-policy-view.tsx
> +    await Promise.all(promises)
not needed... still not blocking the PR for this small nit...
```suggestion
    Promise.all(promises)
```

2023-09-13 12:09 UTC, merged