i18n path update
red-hat-storage/odf-console pull request #106
Opened 2022-01-24 08:40 UTC by RishabhKodes

Updated the path for the i18n

2022-01-24 08:42 UTC, SanjalKatiyar commented
/ok-to-test
/LGTM

2022-01-24 08:56 UTC, RishabhKodes commented
/assign @bipuladh

2022-01-25 10:05 UTC, bipuladh commented
There are instances of `ceph-storage-plugin` used in the codebase. Can you please remove them and run the i18n command again?

2022-02-02 02:48 UTC, bipuladh requested changes
https://github.com/red-hat-storage/odf-console/blob/master/packages/shared/status/statuses.tsx#L10-L15
Update it here too.

2022-02-02 02:48 UTC, bipuladh commented on packages/odf/components/system-list/odf-system-list.tsx
> +  const { t } = useTranslation('ceph-storage-plugin');
```suggestion
  const { t } = useTranslation('plugin__odf-console');
```

2022-02-02 02:48 UTC, bipuladh commented on packages/odf/modals/add-capacity/add-capacity-modal.tsx
> +  const { t } = useTranslation('ceph-storage-plugin');
```suggestion
  const { t } = useTranslation('plugin__odf-console');
```

2022-02-02 07:11 UTC, bipuladh requested changes
Please run `yarn i18n` as well.

2022-02-02 07:11 UTC, bipuladh commented on packages/shared/storage/pvc/pvs-available-capacity.tsx
> +  const { t } = useTranslation('plugin_odf-console');
```suggestion
  const { t } = useTranslation('plugin__odf-console');
```

2022-02-02 07:11 UTC, bipuladh commented on packages/shared/status/statuses.tsx
> +  const { t } = useTranslation('plugin_odf-console');
```suggestion
  const { t } = useTranslation('plugin__odf-console');
```

2022-02-02 07:11 UTC, bipuladh commented on packages/odf/components/system-list/odf-system-list.tsx
> +  const { t } = useTranslation('plugin_odf-console');
```suggestion
  const { t } = useTranslation('plugin__odf-console');
```

2022-02-02 09:25 UTC, bipuladh requested changes
You need to change the namespace(ns prop) of Trans as well at https://github.com/red-hat-storage/odf-console/blob/master/packages/odf/modals/add-capacity/add-capacity-modal.tsx#L324-L325

2022-02-02 09:26 UTC, bipuladh commented on locales/en/console-shared.json
> +{
This file should not exist.

2022-02-02 09:54 UTC, RishabhKodes commented
> You need to change the namespace(ns prop) of Trans as well at https://github.com/red-hat-storage/odf-console/blob/master/packages/odf/modals/add-capacity/add-capacity-modal.tsx#L324-L325

The trans is already updated in the latest commit.

2022-02-02 16:59 UTC, bipuladh requested changes

2022-02-02 16:59 UTC, bipuladh commented on locales/en/ceph-storage-plugin.json
> +{
This file should not exist at all.

2022-02-03 15:08 UTC, bipuladh reviewed
There are some strings starting with `public~` can we change that as well?

2022-02-03 15:18 UTC, RishabhKodes commented
> There are some strings starting with `public~` can we change that as well?

Changing `public~` to `plugin__odf-console`?

2022-02-04 03:47 UTC, bipuladh commented
> > There are some strings starting with `public~` can we change that as well?
> 
> Changing `public~` to `plugin__odf-console~`?

No remove `public~` and pass `plugin__odf-console` to `t` funciton.

2022-02-04 08:38 UTC, bipuladh requested changes

2022-02-04 08:38 UTC, bipuladh commented on packages/odf/constants/common.ts
> +        'The amount of capacity that would be dynamically allocated on the selected StorageClass.',
```suggestion
        'plugin__odf-console~The amount of capacity that would be dynamically allocated on the selected StorageClass.',
```

2022-02-04 08:38 UTC, bipuladh commented on packages/odf/constants/common.ts
> +        'The StorageClass used by OpenShift Data Foundation to write its data and metadata.',
```suggestion
        'plugin__odf-console~The StorageClass used by OpenShift Data Foundation to write its data and metadata.',
```

2022-02-04 08:38 UTC, bipuladh commented on packages/odf/components/system-list/utils.ts
> +        labelKey: t('Add Capacity'),
```suggestion
        labelKey: t('plugin__odf-console~Add Capacity'),
```

2022-02-04 14:40 UTC, bipuladh approved these changes
Please squash the commits.

2022-02-04 17:19 UTC, merged

2022-02-11 16:47 UTC, bipuladh commented
/cherry-pick release-4.10

2022-02-11 16:48 UTC, bipuladh commented
/cherrpick release-4.10

2022-02-11 16:49 UTC, bipuladh commented
/cherrypick rlelease-4.10-compatibility

2022-02-11 16:50 UTC, bipuladh commented
/cherrypick release-4.10-compatibility