Fix CVE-2023-43646 get-func-name module security issue
red-hat-storage/odf-console pull request #1081
Opened 2023-10-17 05:44 UTC by TimothyAsirJeyasing

broccoli-output-wrapper uses get-func-name module version 2.0.0 which has some security issues. 
Its fixed in version 2.0.1.
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2023-10-17 05:45 UTC, TimothyAsirJeyasing commented
@SanjalKatiyar , @bipuladh Please review

2023-10-17 05:59 UTC, SanjalKatiyar commented
this is not a correct fix, assuming description of PR is correct and "broccoli-output-wrapper" is affected then you need to fix the existing package which is the cause of this instead of adding a new package directly to your dependencies.

2023-10-17 06:06 UTC, SanjalKatiyar commented
also u mentioned `broccoli-output-wrapper uses get-func-name`, I don't find `get-func-name` to be an internal dep of `broccoli-output-wrapper`, how does it use that can you point me to the file ?

2023-10-17 07:13 UTC, TimothyAsirJeyasing commented
Sorry, its a sub dependency for broccoli-output-wrapper used by chai module
node_modules/broccoli-output-wrapper/yarn.lock:get-func-name@^2.0.0

2023-10-17 07:23 UTC, SanjalKatiyar commented
> Sorry, its a sub dependency for broccoli-output-wrapper used by chai module node_modules/broccoli-output-wrapper/yarn.lock:get-func-name@^2.0.0

can u send me the yarn.lock file's exact line (in our odf-console) where `get-func-name` is defined as an internal dep of `broccoli-output-wrapper` ??

2023-10-17 07:51 UTC, SanjalKatiyar commented
> Sorry, its a sub dependency for broccoli-output-wrapper used by chai module node_modules/broccoli-output-wrapper/yarn.lock:get-func-name@^2.0.0

or maybe, the place where we are defining `chai` as a dep in odf-console ??

2023-10-26 07:49 UTC, bipuladh requested changes

2023-10-26 07:49 UTC, bipuladh commented on package.json
> +    "get-func-name": "^2.0.1",
I don't understand the need to introduce a new package.

2023-10-26 10:27 UTC, TimothyAsirJeyasing commented on package.json
> +    "get-func-name": "^2.0.1",
└─┬ i18next-parser@6.6.0
  └─┬ broccoli-plugin@4.0.7
    └── broccoli-output-wrapper@3.2.5

The recent available version of broccoli-output-wrapper package holds a devDependency to chai ^4.2.0, which included a version of get-func-name vulnerable to CVE-2023-43646. This CVE is fixed in get-func-name version 2.0.1 and above and its fixed/the higher version used only in Chai version 4.3.10  (https://github.com/chaijs/chai/pull/1540). I could see the entry of get-func-name only in node_modules/broccoli-output-wrapper/yarn.lock after i do yarn install. And i agree, we do not need this package and this CVE will not affect our component as we do not directly consume this anywhere.

2023-11-07 10:53 UTC, bipuladh reviewed
Why are we introducing chai?

2023-12-27 06:48 UTC, TimothyAsirJeyasing commented
odf-console is not affected by "get-func-name" for production environment, it just used as a internal dependency for chai. 

└─┬ i18next-parser@6.6.0
└─┬ broccoli-plugin@4.0.7
└── broccoli-output-wrapper@3.2.5
        └── (devDependency) chai@4.2.0
                                                 └── get-func-name@2.0.0

We are not at all using the packages chai or get-func-name and (we do not have any entry either in yarn.lock). Chai is used only as a dev-dependency for broccoli-output-wrapper. Initially i was a bit confused about the sub dependencies. There is no fix required for this. I will close this pr and move the bz to on-qa with this note.

2024-01-03 06:27 UTC, TimothyAsirJeyasing commented
/close

2024-01-03 06:27 UTC, closed without merging