Provide osd migration status alert for dr brownfield
red-hat-storage/odf-console pull request #1097
Opened 2023-11-10 11:05 UTC by TimothyAsirJeyasing

2023-11-10 11:05 UTC, TimothyAsirJeyasing commented
![image](https://github.com/red-hat-storage/odf-console/assets/6670284/2c2085e3-56a8-4c52-a343-01c510a268b6)

2023-11-10 11:06 UTC, TimothyAsirJeyasing commented
@GowthamShanmugam Please review

2023-11-10 11:26 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +    documentationLink = 'www.google.com';
Please help me point the document link i should use ?

2023-11-16 06:25 UTC, GowthamShanmugam commented
Please add screenshots

2023-11-16 07:58 UTC, bipuladh requested changes

2023-11-16 07:58 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +  return (
We definitely don't want to make it a part of Alert.

2023-11-16 08:14 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-item.tsx
> +          </div>
This part is messing up with the alert card, can we keep this entire part are out of alert card?

2023-11-16 08:41 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-item.tsx
> +          </div>
lets not touch alert cars, keep you status under alert card, Please discuss this with UX

2023-11-16 08:42 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-item.scss
> +  }
use patternfly components Flex and Button, you dont need these CSS

2023-11-16 08:44 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +};
This function is also used in detail cards to  trigger migration, keep one function and keep it in common place.

2023-11-16 08:44 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +        description: `Cluster is undergoing OSDs migration. ${percentageComplete}% completed (${migratedDevices}/${totalOsd} remaining)`,
translate the text

2023-11-16 08:44 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +        alertname: 'Cluster OSDs are being migrated',
translate the text

2023-11-16 08:44 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +        severity: 'current',
no need to translate the text?

2023-11-16 08:44 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +          'OSDs migration is successful. Your cluster is ready for a regional DR setup.',
translate the text

2023-11-16 08:44 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +        alertname: 'Cluster ready for Regional-DR setup',
translate the text

2023-11-16 08:45 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +        severity: 'passed',
translate the text

2023-11-16 08:45 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +        severity: 'passed',
keep severity under enum

2023-11-16 08:45 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +    documentationLink = 'www.google.com';
simply use prod document of  ODF DR section

2023-11-16 08:46 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      </AlertsBody>
better keep this out of alert card, use seperare component

2023-11-16 08:46 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <CephAlerts data={data} />
dont keep this part of alert card

2023-11-16 08:48 UTC, GowthamShanmugam commented
Also, please check why the build is failing. And every PR in UI needs Unit testing and e2e testing.

2023-11-20 11:29 UTC, TimothyAsirJeyasing commented
![image](https://github.com/red-hat-storage/odf-console/assets/6670284/c804c9c4-eb67-4d6f-bcac-05080cb44557)

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +import CephClusterOSDMigrationStatus from '../../../modals/osd-migration/osd-migration-status';
```suggestion
import {OSDMigrationStatus} from '../../../modals/osd-migration/osd-migration-status';
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <CephClusterOSDMigrationStatus data={data} />
```suggestion
      <OSDMigrationStatus data={cephDetails} />
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +const CephClusterOSDMigrationStatus: React.FC<CephClusterOSDMigrationStatusProps> =
```suggestion
const OSDMigrationStatus: React.FC<OSDMigrationStatusProps> =
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +    const osdMigrationStatus = getOSDMigrationStatus(data[0]);
```suggestion
    const osdMigrationStatus = getOSDMigrationStatus(data);
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +    const osdMigrationStatus = getOSDMigrationStatus(data[0]);
change to migrationStatus or status

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/utils/ocs.ts
> +export const getOSDMigrationStatus = (ceph: CephClusterKind) => {
const OSDMigrationModal: React.FC<OSDMigrationModalProps> = ({ cephData }) => {

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/utils/ocs.ts
> +export const getOSDMigrationStatus = (ceph: CephClusterKind) => {
move this inside utils folder under ocs.ts, And rename this function as getOSDMigrationStatus

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/utils/ocs.ts
> +  UNKNOWN = '',
```suggestion
  
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/utils/ocs.ts
> +  return OSDMigrationStatus.UNKNOWN;
```suggestion
  return '';
```

or return undefined

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +    const osdMigrationStatus = getOSDMigrationStatus(data[0]);
```suggestion
    const osdMigrationStatus: string = getOSDMigrationStatus(data[0]);
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +    }
```suggestion
 
```
move description and icon changing logic inside return block

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +        totalOsd !== 0 ? Math.round((migratedDevices / totalOsd) * 100) : 0;
movie this logic inside function and keep it outside of the component in the same file

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +    let IconComponent: React.ComponentType<any> = () => null;
```suggestion
    
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +    const osdMigrationStatus = getOSDMigrationStatus(data[0]);
movie this inside useMemo

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +        <hr />
use <Divider />

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +      <div>
```suggestion
      <>
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +      </div>
decide description and icon based on Status here.

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/healthchecks.scss
> +}
```suggestion


```

use <Flex> component

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/healthchecks.scss
> +}
```suggestion
use <Flux> component
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +type CephClusterOSDMigrationStatusProps = {
```suggestion
type OSDMigrationStatusProps = {
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  data?: K8sResourceKind[];
```suggestion
  data?: CephClusterKind;
```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +export default CephClusterOSDMigrationStatus;
```suggestion

```

2023-11-20 11:55 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +const CephClusterOSDMigrationStatus: React.FC<CephClusterOSDMigrationStatusProps> =
```suggestion
export const CephClusterOSDMigrationStatus: React.FC<CephClusterOSDMigrationStatusProps> =
```

2023-11-20 13:04 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <CephClusterOSDMigrationStatus data={data} />
OSD migration details are coming from data.storage.... Whereas cephDetails are pointing to data.status

2023-11-21 09:07 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <OSDMigrationStatus data={data[0]} />
<OSDMigrationStatus data={data?.[0]}

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <OSDMigrationStatus data={data[0]} />
```suggestion
      <OSDMigrationStatus data={data?.[0]} />
```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/healthchecks.scss
> +}
```suggestion

```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +import * as React from 'react';
osd-migration-status.tsx is not a modal, dont keep this file inside a modal folder

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +import { DOC_LINKS, ViewDocumentation } from '@odf/mco/utils';
Don't import anything from MCO. if you want to use doc_utils then move it to shared and refactor doc-utils.ts. Also, It should not have any info about MCO or ODF.

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +} from '../../utils/osd-migration';
keep these inside enum and move the enum to dataProtection.ts

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +const calculateOSDMigration = (data: CephClusterKind) => {
```suggestion
const calculateOSDMigration = (: CephClusterKind) => {
```
dont use name 'data' everywhere, use the proper name

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  };
if you are returning as an object then you need a proper return type. Otherwise, return as array of values

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  data,
dont use name 'data', use correct variable name

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  const migrationStatus: string = getOSDMigrationStatus(data);
these two line will render again and again, use hooks to prevent

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  }
```suggestion

```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  }
```suggestion

```

I am not getting what is this for.

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +      <hr />
```suggestion
      
```
i commented multiple times to use `<Divider />`

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +        <FlexItem className="mco-osd-migration"></FlexItem>
```suggestion
```

why empty FlexItem?

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              {t('Cluster ready for Regional-DR setup.')}
```suggestion
             
```
use `<StatusIconAndText>`

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
```suggestion
            <FlexItem>
```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              )}
```suggestion

```
use `<StatusIconAndText>`

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              {t('Could not migrate cluster OSDs.')}
```suggestion
 
```

use `<StatusIconAndText>`

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
```suggestion
            <FlexItem>
```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +                `Cluster is undergoing OSDs migration. ${osdMigrationData.percentageComplete}% completed (${osdMigrationData.migratedDevices}/${osdMigrationData.totalOsd} remaining)`
```suggestion
            
```
This is not the right way to translate, please refer other places

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
```suggestion
            <FlexItem>
```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +                ` ${osdMigrationData.percentageComplete}% completed (${osdMigrationData.migratedDevices}/${osdMigrationData.totalOsd} remaining)`
```suggestion
                
```
This is not the right way to translate, please refer other places

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              <span aria-hidden>✕</span>
```suggestion
              
```

what is this X ?

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              <span aria-hidden>✕</span>
i think you are using a wrong patternfly component to implement this

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  data?: CephClusterKind;
```suggestion
  cephData?: CephClusterKind;
```

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/utils/osd-migration.ts
> +export const FAILED = 'Failed';
convert this status into Enum and move inside constant folder

2023-11-21 13:25 UTC, GowthamShanmugam commented on packages/ocs/utils/osd-migration.ts
> +export const BLUESTORE = 'bluestore';
move inside constant folder

2023-11-21 14:10 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  }
This is for closing the status alert if the users wants when the status as complete

2023-11-21 14:13 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +        <FlexItem className="mco-osd-migration"></FlexItem>
I want to align with the status icon to avoid starts from left edge

2023-11-21 14:15 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
I want the icon to be displayed at the same size of the icons which are already under Status

2023-11-22 06:39 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +        <FlexItem className="mco-osd-migration"></FlexItem>
try to use '<StatusIconAndText>' it may already have left alignment

2023-11-22 11:11 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <OSDMigrationStatus data={data[0]} />
done

2023-11-23 06:36 UTC, GowthamShanmugam commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              <span aria-hidden>✕</span>
you should use X icon

2023-11-23 07:38 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +      <OSDMigrationStatus data={data[0]} />
done

2023-11-23 07:38 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/healthchecks.scss
> +}
done

2023-11-23 07:38 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +import * as React from 'react';
done

2023-11-23 07:38 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +} from '../../utils/osd-migration';
done

2023-11-23 07:39 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +const calculateOSDMigration = (data: CephClusterKind) => {
done

2023-11-23 07:39 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  };
done, i used array to return

2023-11-23 07:39 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  data,
done, used cephData

2023-11-23 07:50 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  const migrationStatus: string = getOSDMigrationStatus(data);
done

2023-11-23 07:50 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  }
done

2023-11-23 07:50 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  }
done

2023-11-23 07:50 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +      <hr />
done

2023-11-23 07:51 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +        <FlexItem className="mco-osd-migration"></FlexItem>
done, used HealthBody, it resolved the alignment issue at the beginning

2023-11-23 07:53 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              {t('Cluster ready for Regional-DR setup.')}
Used HealthItem to have same alignment and size like status items and passed state to ok to avoid the status to be displayed bellow to the icon.

2023-11-23 07:53 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
Resolved by using HealthItem

2023-11-23 07:53 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              )}
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +              {t('Could not migrate cluster OSDs.')}
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +                `Cluster is undergoing OSDs migration. ${osdMigrationData.percentageComplete}% completed (${osdMigrationData.migratedDevices}/${osdMigrationData.totalOsd} remaining)`
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +            <FlexItem className="co-dashboard-icon">
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +                ` ${osdMigrationData.percentageComplete}% completed (${osdMigrationData.migratedDevices}/${osdMigrationData.totalOsd} remaining)`
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/modals/osd-migration/osd-migration-status.tsx
> +  data?: CephClusterKind;
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/utils/osd-migration.ts
> +export const FAILED = 'Failed';
done

2023-11-23 07:54 UTC, TimothyAsirJeyasing commented on packages/ocs/utils/osd-migration.ts
> +export const BLUESTORE = 'bluestore';
done

2023-11-23 16:02 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +  cephData?: CephClusterKind;
```suggestion
  cephData: CephClusterKind;
```

2023-11-23 16:02 UTC, GowthamShanmugam commented on packages/odf/constants/dataProtection.ts
> +}
```suggestion
export enum OSD_MIGRATION_STATUS {
  IN_PROGRESS = 'In Progress',
  PENDING = 'Pending',
  COMPLETED = 'Completed',
  FAILED = 'Failed',
}
```

2023-11-27 11:21 UTC, TimothyAsirJeyasing commented on packages/mco/components/modals/app-failover-relocate/subscriptions/error-messages.tsx
> +} from '../../../../../shared/src/doc/doc-utils';
done

2023-11-27 11:21 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +  cephData?: CephClusterKind;
done

2023-11-27 11:22 UTC, TimothyAsirJeyasing commented on packages/odf/constants/dataProtection.ts
> +}
done as per 1st PR review suggestion to this name

2023-11-27 11:42 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.spec.tsx
> +import * as migrationStatus from '../../../../utils/osd-migration';
```suggestion
import { getOSDMigrationStatus } from '../../../../utils/osd-migration';
```

2023-11-27 11:42 UTC, GowthamShanmugam commented on packages/shared/src/doc/doc-utils.tsx
doc-utils.ts has a lot of MCO and ACM-related constants, you have to move these to MCO constants. Shared component should be generic.

2023-11-27 11:42 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +            <>
can't we move <Divider /> here?

2023-11-27 11:49 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +            <>
Could you give some more light on this

2023-11-27 12:15 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +            <>
```suggestion
            <>
            <Divider />
```

2023-11-27 12:17 UTC, SanjalKatiyar commented
add screenshots for all the flows added by this PR... to cross-check if they matches with the provided UX...

2023-11-28 05:05 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    (cephData?.status?.storage?.osd?.storeType?.[BLUESTORE] || 0) +
create a separate function under `utils` which returns `ceph.status?.storage?.osd?.storeType`, and use that every where needed... this will be used in another files as well related to this epic...

2023-11-28 05:06 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    (cephData?.status?.storage?.osd?.storeType?.[BLUESTORE] || 0) +
eg:
``` 
const getBluestoreCount = (ceph: CephClusterKind): number => {
  return getCephStoreType(ceph)?.[BLUESTORE] || 0;
};

2023-11-28 05:22 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    (cephData?.status?.storage?.osd?.storeType?.[BLUESTORE] || 0) +
Sure, have't notice this comment, i will update this PR

2023-11-28 05:25 UTC, TimothyAsirJeyasing commented
![image](https://github.com/red-hat-storage/odf-console/assets/6670284/e5deda5c-723a-4337-9d9d-d652dd4861a3)
![Screenshot from 2023-11-28 10-44-27](https://github.com/red-hat-storage/odf-console/assets/6670284/49b2a5d2-defd-4ede-b770-e73db325fb3c)
![Screenshot from 2023-11-28 10-43-36](https://github.com/red-hat-storage/odf-console/assets/6670284/b9db21ce-f54c-430a-82c3-d5d1991cc5b3)
![Screenshot from 2023-11-28 10-42-42](https://github.com/red-hat-storage/odf-console/assets/6670284/a1b11e8c-2a01-42a3-a14c-2d8cfc587ff7)

2023-11-28 05:26 UTC, TimothyAsirJeyasing commented
![Uploading Screenshot from 2023-11-28 10-46-43.png…]()

2023-11-28 05:36 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +        OSDMigrationStatus.FAILED,
what about unknown or not available status ??

2023-11-28 05:37 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +            <>
```suggestion
```

2023-11-28 05:39 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +          )}
didn't UX had a cancel button to remove the status when migration is completed ??

2023-11-28 05:41 UTC, SanjalKatiyar commented on packages/ocs/utils/osd-migration.ts
> +      ceph?.status?.storage?.osd?.storeType?.[BLUESTORE_RDR];
eg:
```
const getBluestoreCount = (ceph: CephClusterKind): number => {
  return getCephStoreType(ceph)?.[BLUESTORE] || 0;
};
```

2023-11-28 05:43 UTC, SanjalKatiyar commented on packages/shared/src/utils/doc-utils.tsx
> +export const ODF_DOC_BASE_PATH = `${ODF_DOC_HOME}/html-single`;
there are constants...

2023-11-28 05:44 UTC, SanjalKatiyar commented on packages/shared/src/utils/doc-utils.tsx
> +export const DR_DOC_HOME = `${ODF_DOC_BASE_PATH}/configuring_openshift_data_foundation_disaster_recovery_for_openshift_workloads/index#apply-drpolicy-to-sample-application_manage-dr`;
DR specific link in shared ??

2023-11-28 05:48 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +                  '{{ percentageComplete }}% completed ({{ migratedDevices }}/ {{ totalOsd }} remaining)',
```suggestion
                  '{{ percentageComplete }}% completed ({{ migratedDevices }}/{{ totalOsd }} remaining)',
```

2023-11-28 05:48 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +                  '{{ percentageComplete }}% completed ({{ migratedDevices }}/ {{ totalOsd }} remaining)',
```suggestion
                  '{{ percentageComplete }}% completed ({{ migratedDevices }}/{{ totalOsd }} remaining)',
```

2023-11-28 05:59 UTC, TimothyAsirJeyasing commented on packages/shared/src/utils/doc-utils.tsx
> +export const ODF_DOC_BASE_PATH = `${ODF_DOC_HOME}/html-single`;
ok, i will move these constants to /shared/src/constants as this required by multiple module

2023-11-28 06:07 UTC, TimothyAsirJeyasing commented on packages/shared/src/utils/doc-utils.tsx
> +export const DR_DOC_HOME = `${ODF_DOC_BASE_PATH}/configuring_openshift_data_foundation_disaster_recovery_for_openshift_workloads/index#apply-drpolicy-to-sample-application_manage-dr`;
Shall i move this to DR_DOC_HOME to ocs/constants/common.ts ?

2023-11-28 07:10 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +                  '{{ percentageComplete }}% completed ({{ migratedDevices }}/ {{ totalOsd }} remaining)',
done

2023-11-28 07:10 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +                  '{{ percentageComplete }}% completed ({{ migratedDevices }}/ {{ totalOsd }} remaining)',
done

2023-11-28 07:10 UTC, TimothyAsirJeyasing commented on packages/ocs/utils/osd-migration.ts
> +      ceph?.status?.storage?.osd?.storeType?.[BLUESTORE_RDR];
done

2023-11-28 07:10 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +          )}
Added a close button

2023-11-28 09:22 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +        ].includes(migrationStatus as OSDMigrationStatus) && <Divider />}{' '}
if we are not displaying the divider only for the pending, then lets check !OSDMigrationStatus.PENDING.

2023-11-28 10:48 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    isMigrationStatusVisible && (
can users close pending and failed status as well ?? (isn't UX only allow it for completed status ??

2023-11-28 10:59 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    isMigrationStatusVisible && (
this will not work, what if I close dashboard and visit it again (FC will be un-mounted and mounted again), `isMigrationStatusVisible` will again be set to `true` and u will see both status and close button...

2023-11-28 11:29 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    isMigrationStatusVisible && (
the close icon will be available only for complete status, so user will not have any close options for other status.

2023-11-28 11:37 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    isMigrationStatusVisible && (
but that's not happening here, right ?
u are showing it for all statuses...

2023-11-28 17:23 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    setIsMigrationStatusVisible(true);
did u test ur PR ?? this is not gonna make any difference to the original issue we discussed https://github.com/red-hat-storage/odf-console/pull/1097#discussion_r1407584008

2023-11-28 17:23 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    setIsMigrationStatusVisible(true);
this is not correct...

2023-11-28 20:21 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    setIsMigrationStatusVisible(true);
maybe we can remove close button entirely (discussed with @GowthamShanmugam), need to be verified with UX (asap)...

2023-11-28 20:22 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    setIsMigrationStatusVisible(true);
for now let's remove it and if needed to absolutely add it we can do so as a bug fix... no need to block this PR any longer...

2023-11-29 07:09 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +    setIsMigrationStatusVisible(true);
Sure, removed the button and updated

2023-11-29 08:00 UTC, GowthamShanmugam approved these changes

2023-11-29 08:04 UTC, SanjalKatiyar commented
LGTM

2023-11-29 16:47 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +export const OSDMigration: React.FC<OSDMigrationStatusProps> = ({
to match it with file name and props' type name...
```suggestion
export const OSDMigrationStatus: React.FC<OSDMigrationStatusProps> = ({
```

2023-11-29 16:48 UTC, SanjalKatiyar commented on packages/shared/src/utils/doc-utils.tsx
> +};
export from `index` file...

2023-11-29 16:48 UTC, SanjalKatiyar commented on packages/mco/components/modals/app-failover-relocate/subscriptions/error-messages.tsx
> +import { ViewDocumentation } from '@odf/shared/utils/doc-utils';
```suggestion
import { ViewDocumentation } from '@odf/shared/utils';
```

2023-11-29 16:48 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +import { ViewDocumentation } from '@odf/shared/utils/doc-utils';
```suggestion
import { ViewDocumentation } from '@odf/shared/utils';
```

2023-11-29 16:49 UTC, SanjalKatiyar commented on packages/odf/constants/dataProtection.ts
> +export const BLUESTORE = 'bluestore';
plz rename this file to `data-protection`

2023-11-30 05:03 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +export const OSDMigration: React.FC<OSDMigrationStatusProps> = ({
OSDMigrationStatus name used for "enum OSDMigrationStatus" in data-protection.ts and its used here

2023-11-30 05:07 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +export const OSDMigration: React.FC<OSDMigrationStatusProps> = ({
so ? rename the `enum` or rename ur props' type/file name to match with the FC name...

2023-11-30 08:33 UTC, TimothyAsirJeyasing commented on packages/odf/constants/dataProtection.ts
> +export const BLUESTORE = 'bluestore';
done

2023-11-30 08:33 UTC, TimothyAsirJeyasing commented on packages/mco/components/modals/app-failover-relocate/subscriptions/error-messages.tsx
> +import { ViewDocumentation } from '@odf/shared/utils/doc-utils';
done

2023-11-30 08:33 UTC, TimothyAsirJeyasing commented on packages/mco/components/modals/app-failover-relocate/error-messages.tsx
> +import { ViewDocumentation } from '@odf/shared/utils/doc-utils';
done

2023-11-30 08:33 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/status-card/osd-migration/osd-migration-status.tsx
> +export const OSDMigration: React.FC<OSDMigrationStatusProps> = ({
done

2023-11-30 08:45 UTC, SanjalKatiyar commented
/approve
/lgtm

2023-11-30 12:13 UTC, merged