[WIP] refactoring (multiple StorageClusters + ODF in any Namespace)
red-hat-storage/odf-console pull request #1099
Opened 2023-11-13 10:43 UTC by SanjalKatiyar

2023-11-20 04:57 UTC, bipuladh requested changes

2023-11-20 04:57 UTC, bipuladh commented on packages/odf/redux/reducers/opr-install-namespace.ts
> +        ...state,
This performs a shallow copy. The internal properties will be equal by reference, this can cause bugs. Use `immutable` to help you work with state.
see https://immutable-js.com/

2023-11-20 06:54 UTC, SanjalKatiyar commented on packages/odf/redux/reducers/opr-install-namespace.ts
> +        ...state,
done, added `immer` as per the suggestion...

2023-11-22 01:57 UTC, bipuladh commented on packages/odf/hooks/useSafeK8sGet.ts
> +export const useSafeK8sGet = <R extends K8sResourceCommon = K8sResourceCommon>(
Is this required for the usecase when the user is not an admin?

2023-11-22 01:57 UTC, bipuladh commented on packages/odf/components/utils/safety-box.tsx
> +    <StatusBox loaded={isAllLoaded} loadError={anyError} />
Doesn't `StatusBox` take a component as child?

2023-11-22 05:19 UTC, SanjalKatiyar commented on packages/odf/hooks/useSafeK8sGet.ts
> +export const useSafeK8sGet = <R extends K8sResourceCommon = K8sResourceCommon>(
this can use used for any case (given we have required RBACs), it saves some unnecessary API calls... in case of non-admin, if we want we can pass `allowFallback = true` argument which would default to `openshift-storage`...

2023-11-22 05:30 UTC, SanjalKatiyar commented on packages/odf/components/utils/safety-box.tsx
> +    <StatusBox loaded={isAllLoaded} loadError={anyError} />
it does, but current way makes it possible to display `children` even in case of any error (upto consumer of the FC to decide what to do)...
one of the example:
`<StatusBox loaded={isAllLoaded} loadError={anyError} />{children}</StatusBox>` >> then in case of non-admin this will always show error as `anyError` will not be empty (RBAC issue), but if I pass `allowFallback` argument and use ternary condition (current way) I can still display `children`, if I want to.

2023-11-22 06:55 UTC, bipuladh commented on packages/ocs/storage-class/sc-form.tsx
> +          }}
Why this change?

2023-11-22 06:55 UTC, bipuladh commented on packages/ocs/storage-class/sc-form.tsx
> +      CEPH_CLUSTER_NAMESPACE_SESSION_STORAGE,
```suggestion
      CEPH_CLUSTER_NAMESPACE,
```

2023-11-22 06:55 UTC, bipuladh commented on packages/odf/hooks/useSafeK8sGet.ts
> +  const useK8sGetArgs = getValidK8sOptions(
```suggestion
  const K8sGetArgs = getValidK8sOptions(
```
 `use` should be prefix for hooks.

2023-11-22 06:55 UTC, bipuladh commented on packages/odf/hooks/useSafeK8sGet.ts
> + * Ensures no API request is made unless its "safe" to do so (ODF installed namespace is fetched successfully).
IIUC this assumption is incorrect. A fetch request will go but it will just be a useless call. Nevertheless we are adding this call to our stack. If you really want to avoid this I suggest you use the fetch functions such as `k8sGetResource` instead of `useK8sGet` hook. This applies for other safe functions as well.

2023-11-22 06:55 UTC, bipuladh commented on packages/odf/redux/dispatchers/opr-install-namespace.ts
> +export const useOprInstallNamespaceDispatch: UseOprInstallNamespaceDispatch =
I don't see much value of having a separate component. It's used in only one place. We can just simply dispatch the action with some args. Is this used in more than one place?

2023-11-22 06:55 UTC, bipuladh commented on packages/odf/redux/provider-hooks/useOprInstallNamespace.ts
> +import { useOprInstallNamespaceDispatch } from '../dispatchers';
Please see that you are not adding circular dependencies with imports.

2023-11-22 06:55 UTC, bipuladh commented on packages/odf/redux/selectors/opr-install-namespace.ts
> +    oprInstallNs,
Could we do a better name `odfNamespace`? Also how are we handling usecases for MCO? Do we need to detect MCO as well?

2023-11-22 06:55 UTC, bipuladh commented on packages/odf/redux/selectors/opr-install-namespace.ts
> +  return {
If you return it as an array end users will not have to use the same name for variables. It might be better as we might have to support multiple namespaces for multiple operators.

2023-11-22 07:02 UTC, SanjalKatiyar commented on packages/odf/hooks/useSafeK8sGet.ts
> + * Ensures no API request is made unless its "safe" to do so (ODF installed namespace is fetched successfully).
it won't send any api call at all because of the resource object that I am passing to `useK8sGet` (I defined `getValidK8sOptions` for the very same reason)...
and I already updated `useK8sGet` as well, there is a condition `if (kind) fetch();` that would ensure no api call...

2023-11-22 07:02 UTC, SanjalKatiyar commented on packages/odf/hooks/useSafeK8sGet.ts
> + * Ensures no API request is made unless its "safe" to do so (ODF installed namespace is fetched successfully).
same is true for other "safe" hook wrapper that I defined...

2023-11-22 07:03 UTC, SanjalKatiyar commented on packages/ocs/storage-class/sc-form.tsx
> +          }}
I was testing something, then forgot to remove this... will update...

2023-11-22 07:04 UTC, SanjalKatiyar commented on packages/ocs/storage-class/sc-form.tsx
> +      CEPH_CLUSTER_NAMESPACE_SESSION_STORAGE,
I agree it is a long name, but it is not really a `CEPH_CLUSTER_NAMESPACE`, it is infact the "key" that we use to store the namespace in the session... will update anyway...

2023-11-22 07:05 UTC, SanjalKatiyar commented on packages/odf/hooks/useSafeK8sGet.ts
> +  const useK8sGetArgs = getValidK8sOptions(
ack...

2023-11-22 07:09 UTC, SanjalKatiyar commented on packages/odf/redux/dispatchers/opr-install-namespace.ts
> +export const useOprInstallNamespaceDispatch: UseOprInstallNamespaceDispatch =
not really, but it is more of a directory structure to keep things logically grouped together...
in future if we need another dispatcher (diff use case) then we can create a separate file for that (here under `/redux/dispatchers`) and export via `index`...
maybe `useOprInstallNamespaceDispatch` is not reused, but others (in future) could be... so it's more of a way to group things under new `redux` directory...

2023-11-22 07:11 UTC, bipuladh commented on packages/odf/hooks/useSafeK8sGet.ts
> + * Ensures no API request is made unless its "safe" to do so (ODF installed namespace is fetched successfully).
I don't see `if (kind) fetch();` anywhere. Can you point me to it?

2023-11-22 07:12 UTC, SanjalKatiyar commented on packages/odf/redux/provider-hooks/useOprInstallNamespace.ts
> +import { useOprInstallNamespaceDispatch } from '../dispatchers';
I don;t think we have any circular dependency, maybe I missed somewhere ??
also we use `CircularDependencyPlugin` in webpack config... so I am assuming we are safe...

2023-11-22 07:16 UTC, SanjalKatiyar commented on packages/odf/redux/selectors/opr-install-namespace.ts
> +  return {
but array would mean to always read "return"ed values in same order... and if I don't want to read all values leaving gaps such as: `const [oprInstallNs, _, _, isSafe] = useOprInstallNamespaceSelector();`...

if we want to rename we can use `const { oprInstallNs: test } = useOprInstallNamespaceSelector();` right ??

2023-11-22 07:19 UTC, SanjalKatiyar commented on packages/odf/redux/selectors/opr-install-namespace.ts
> +    oprInstallNs,
ack !
we don't need it in MCO, there are just couple of places where we need this namespace and for that as well we need not to rely on this hook/redux (anyway MCO will be on hub and ODF on managed cluster, so this redux won't work for MCO)...

2023-11-22 07:21 UTC, SanjalKatiyar commented on packages/shared/src/hooks/k8s-get-hook.ts
> +    else setLoaded(true);
cc @bipuladh

2023-11-22 07:21 UTC, SanjalKatiyar commented on packages/shared/src/hooks/k8s-get-hook.ts
> +    else setLoaded(true);
same is true for `useK8sList.ts`

2023-11-22 07:21 UTC, SanjalKatiyar commented on packages/odf/hooks/useSafeK8sGet.ts
> + * Ensures no API request is made unless its "safe" to do so (ODF installed namespace is fetched successfully).
https://github.com/red-hat-storage/odf-console/pull/1099/files#r1401607319

2023-11-22 08:09 UTC, SanjalKatiyar commented on packages/odf/redux/selectors/opr-install-namespace.ts
> +    oprInstallNs,
gonna be lot of changes to rename everything though !!

2023-11-22 08:20 UTC, SanjalKatiyar commented on packages/odf/redux/selectors/opr-install-namespace.ts
> +    oprInstallNs,
done...

2023-11-22 09:32 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-11-23 04:00 UTC, bipuladh approved these changes

2023-11-23 04:00 UTC, bipuladh commented
/lgtm

2023-11-23 04:04 UTC, merged