Create StorageSystem: add perfomance mode selector
red-hat-storage/odf-console pull request #1102
Opened 2023-11-14 11:21 UTC by alfonsomthd

2023-11-17 12:25 UTC, SanjalKatiyar requested changes

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
> +  }
shoudn't this be calculated based on nodes which are currently selected by users ("selectedNodes"), rather that nodes which could be selected ("selectableNodes") ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
> +  }
if already "selectedNodes" do not satisfy the requirements for other profiles, but do so for lean then we force it to be lean ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/utils/common.ts
> -          isMinimal ? MIN_DEVICESET_RESOURCES : {}
we don't have to set it now ? will backend update StorageCluster CR again and update this based on the profile ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/utils/common.ts
> -      resources: isMinimal ? MIN_SPEC_RESOURCES : {},
we don't have to set it now ? will backend update StorageCluster CR again and update this based on the profile ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/system-list/odf-system-list.tsx
> +            },
there are 2 places where we might want to add this option in kebab:
1. "Data Foundation > StorageSystem" list page (which we did above).
2. "Installed Operators > StorageSystem (under Provided APIs)" list page (check `odf/components/actions/csv-actions.ts` file, we do it for AddCapacity modal similarly).

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/utils/common-odf-install-el.tsx
> +          `The selected nodes do not match Data Foundation's StorageCluster requirement of an aggregated ${minCpu} CPUs and ${minMem} GiB of RAM. If the selection cannot be modified a minimal cluster
are we still using term "minimal" even though we have 3 diffferent profiles now ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/utils/common.ts
> +export const getTotalMemoryInGB = (nodes: WizardNodeState[]): number =>
```suggestion
export const getTotalMemoryInGiB = (nodes: WizardNodeState[]): number =>
```

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/components/utils/common-odf-install-el.tsx
> +          `The selected nodes do not match Data Foundation's StorageCluster requirement of an aggregated ${minCpu} CPUs and ${minMem} GiB of RAM. If the selection cannot be modified a minimal cluster
don't we wanna call it "lean" now ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/constants/common.ts
> + */
these numbers are not confirmed yet ??

2023-11-17 12:25 UTC, SanjalKatiyar commented on packages/odf/utils/ocs.ts
> + * @param memory The amount of selected nodes' memory in GB.
```suggestion
 * @param memory The amount of selected nodes' memory in GiB.
```

2023-11-17 12:35 UTC, alfonsomthd commented on locales/en/plugin__odf-console.json
> +  "Customize your Data Foundation Cluster's performance by selecting a performance profile that meets your specific needs.": "Customize your Data Foundation Cluster's performance by selecting a perfo
`Cluster` appears capitalized in the design.

2023-11-17 12:37 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Customize your Data Foundation Cluster's performance by selecting a performance profile that meets your specific needs.": "Customize your Data Foundation Cluster's performance by selecting a perfo
seems wrong to me (I mean in the design)...

2023-11-17 12:37 UTC, alfonsomthd commented on packages/odf/components/create-storage-system/reducer.ts
> +  resourceProfile: ResourceProfile.Balanced,
IMHO it appears in this step but it's not semantically the same, we're talking about performance which is related (but not the same) to capacity.

2023-11-17 12:38 UTC, alfonsomthd commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          resourceProfile={resourceProfile}
IMHO Performance does not belong to capacity, its's related to it.

2023-11-17 12:39 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          resourceProfile={resourceProfile}
yeah, but it still comes under "Capacity and nodes" step... current redux state is set up that way that all state per step is under single/same key...

2023-11-17 12:40 UTC, alfonsomthd commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
> +  }
Yes, the PM requirement is that we know in advance that even selecting all `selectableNodes` you cannot apply for anything higher than `Lean`, then we force it.

2023-11-17 12:41 UTC, alfonsomthd commented on packages/odf/components/utils/common.ts
> -          isMinimal ? MIN_DEVICESET_RESOURCES : {}
Backend will take care of applying the required `ResourceRequirements` for the storage pods.

2023-11-17 12:43 UTC, alfonsomthd commented on packages/odf/components/system-list/odf-system-list.tsx
> +            },
OK

2023-11-17 12:50 UTC, alfonsomthd commented on packages/odf/components/utils/common-odf-install-el.tsx
> +          `The selected nodes do not match Data Foundation's StorageCluster requirement of an aggregated ${minCpu} CPUs and ${minMem} GiB of RAM. If the selection cannot be modified a minimal cluster
> are we still using term "minimal" even though we have 3 diffferent profiles now ??

I'll confirm with Chandan.

2023-11-17 12:51 UTC, alfonsomthd commented on packages/odf/constants/common.ts
> + */
No, they're provisional numbers.
@malayparida2000 will provide more accurate numbers based on the backend counterpart.

2023-11-17 12:53 UTC, alfonsomthd commented on packages/odf/components/utils/common-odf-install-el.tsx
> +          `The selected nodes do not match Data Foundation's StorageCluster requirement of an aggregated ${minCpu} CPUs and ${minMem} GiB of RAM. If the selection cannot be modified a minimal cluster
@Chandan141996 Should we replace `minimal` with `lean` ?

2023-11-17 13:03 UTC, Chandan141996 commented on packages/odf/components/utils/common-odf-install-el.tsx
> +          `The selected nodes do not match Data Foundation's StorageCluster requirement of an aggregated ${minCpu} CPUs and ${minMem} GiB of RAM. If the selection cannot be modified a minimal cluster
I'll need to have a discussion with the microcopy team and Eran, honestly. I'm not sure whether they're planning to introduce new terminology for these new items or if they intend to use the ones already present in the epics. Once, I'll have more clarity on this I'll let you know. @SanjalKatiyar @alfonsomthd

2023-11-20 05:43 UTC, malayparida2000 commented on packages/odf/constants/common.ts
> + */
Yes @SanjalKatiyar, We are still not fully sure that this will be the number so using an approx number based on our initial discussion, so that the UI story is not blocked due to the number only. I am in touch with Travis from rook & Elvir from perf to get an more accurate number. But this number is not too far off the final number.

2023-11-20 05:45 UTC, malayparida2000 commented on packages/odf/components/utils/common.ts
> -          isMinimal ? MIN_DEVICESET_RESOURCES : {}
Yes, ocs operator will now apply the profiles. UI just needs to set the resourceProfile value in the CR.

2023-11-20 07:53 UTC, alfonsomthd commented on packages/odf/components/utils/common.ts
> -      resources: isMinimal ? MIN_SPEC_RESOURCES : {},
Same as above.

2023-11-21 09:25 UTC, alfonsomthd commented on locales/en/plugin__odf-console.json
> +  "Customize your Data Foundation Cluster's performance by selecting a performance profile that meets your specific needs.": "Customize your Data Foundation Cluster's performance by selecting a perfo
@Chandan141996 I'll apply the change if you don't have any objection.

2023-11-21 14:34 UTC, alfonsomthd commented on packages/odf/components/system-list/odf-system-list.tsx
> +            },
Done.

2023-11-21 14:35 UTC, alfonsomthd commented on packages/odf/components/utils/common.ts
> +export const getTotalMemoryInGB = (nodes: WizardNodeState[]): number =>
Done.

2023-11-21 14:37 UTC, alfonsomthd commented on packages/odf/utils/ocs.ts
> + * @param memory The amount of selected nodes' memory in GB.
Done.

2023-11-22 10:32 UTC, alfonsomthd commented on packages/odf/components/create-storage-system/reducer.ts
> +  resourceProfile: ResourceProfile.Balanced,
Anyway I did the change.

2023-11-23 06:24 UTC, SanjalKatiyar commented on packages/odf/components/utils/common-odf-install-el.tsx
> +          `The selected nodes do not match Data Foundation's StorageCluster requirement of an aggregated ${minCpu} CPUs and ${minMem} GiB of RAM. If the selection cannot be modified a minimal cluster
ack !

2023-11-23 06:41 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
> +  }
this is a side-effect and should be handled in a `useEffect`...

2023-11-23 06:42 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
> +  }
it might not cause issue here because of `&& resourceProfile !== ResourceProfile.Lean` condition, but ideally we should not do this IMO...

2023-11-23 06:54 UTC, SanjalKatiyar commented on packages/odf/modals/configure-performance/configure-performance-modal.tsx
> +  const loading = false;
what's the use of this ? IIUC we are not updating its value and it is always `const` with value as `false`...

2023-11-23 08:59 UTC, alfonsomthd commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/configure-performance.tsx
> +  }
[React documentation](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes) recommends this approach over `useEffect` for this kind of scenarios.

2023-11-23 12:57 UTC, alfonsomthd commented
/assign @bipuladh

2023-11-24 12:23 UTC, GowthamShanmugam commented
LGTM

2023-11-27 08:42 UTC, bipuladh commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
> +  (dispatch: WizardDispatch, newProfile: ResourceProfile): void => {
Is there a reason we need to curry this?

2023-11-27 09:43 UTC, alfonsomthd commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
> +  (dispatch: WizardDispatch, newProfile: ResourceProfile): void => {
This function is invoked in 2 different components both receiving the `dispatch` by prop, so with `curry` I can 
 define the function once and then wrap it in the components like this:
`  const onProfileChange = React.useCallback(
    (profile) => onResourceProfileChange(dispatch)(profile),
    [dispatch]
  );`

2023-11-27 10:52 UTC, bipuladh commented
/lgtm

2023-11-28 07:44 UTC, bipuladh commented
/lgtm

2023-11-29 13:03 UTC, alfonsomthd commented
/retest

2023-11-29 17:19 UTC, malayparida2000 requested changes

2023-11-29 17:19 UTC, malayparida2000 commented on openshift-ci/odf-catalog-source.yaml
> +  channel: alpha
Shouldn't the channel be stable-4.15 instead of alpha?

2023-11-30 07:04 UTC, alfonsomthd commented on openshift-ci/odf-catalog-source.yaml
> +  channel: alpha
@malayparida2000 the last commit if for CI testing purposes, it's not ment to be merged. We have a separate PR for that: https://github.com/red-hat-storage/odf-console/pull/1109

2023-12-01 06:59 UTC, alfonsomthd commented
/retest

2023-12-02 08:07 UTC, SanjalKatiyar commented
/lgtm

2023-12-02 09:27 UTC, merged