[WIP] Adds Provider Mode support
red-hat-storage/odf-console pull request #1115
Opened 2023-12-05 08:40 UTC by bipuladh

- Adds listpage for Storage Clients
 - Adds Modal for generating onboarding token
 - Adds Client status in Status Card

2023-12-07 10:07 UTC, bipuladh commented
Mock links: https://www.figma.com/proto/Afl7ntvufZTshGyuX701u7/Provider-mode?page-id=0%3A1&type=design&node-id=1-330&viewport=60%2C485%2C0.38&t=ngq3FBzQrHNQyEh6-1&scaling=min-zoom&starting-point-node-id=1%3A330

2023-12-07 14:44 UTC, SanjalKatiyar requested changes

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +};
are we using this anywhere ??

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/status-card.tsx
> +  const clientAggregateHealth = getAggregateClientHealthState(clients);
should we for safety to prevent type error ?? or `useK8sWatchResource` will guaranteed return empty list meanwhile when resources are loading or if in error ??
```suggestion
  const clientAggregateHealth = getAggregateClientHealthState(clients || []);
```

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +  return HealthState.UNKNOWN;
if `totalClientsCount = 2` and `healthyClientsCount = 0`, we are reporting it as `UNKNOWN` instead of `ERROR` ??

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +  return HealthState.UNKNOWN;
why do we need `&& healthyClientsCount > 0` part ??

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/status-card.tsx
> +  const clientAggregateHealth = getAggregateClientHealthState(clients);
or maybe we can directly do `state={getAggregateClientHealthState(clients)}`, because then this function will only be called when request is loaded with no error...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +  const totalClientsCount = clients.length;
this entire calculation can be a separate function I guess, which takes `clients` and return healthy and total... u r also using it in `getAggregateClientHealthState`...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +        title: t('Openshift Version'),
```suggestion
        title: t('Openshift version'),
```

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  obj.status.client.operatorVersion;
no optional changing ?? for the cases if `status` or maybe versions are missing from the CR...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [difference]);
does it matter to use `useMemo` here ?? It's not like `Component`'s ref is getting changed or any thing...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [difference]);
it can either be `YellowExclamationTriangleIcon` or `RedExclamationCircleIcon`, which are not getting created on each re-render...

also this `useMemo` is gonna get executed multiple times anyway, as `difference` can highly likely to be diff across re-renders...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +        'Due to the misatch in the client and provider version. This provider cluster cannot be upgraded.'
```suggestion
        'Due to the mismatch in the client and provider version this provider cluster cannot be upgraded.'
```

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +        <LastHeartBeat heartbeat={obj.status.lastHeartbeat} />
no optional chaining ?? for case if `lastHeartbeat` is not present at all in the CR (some bug maybe)...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  hideColumnManagement?: boolean;
all props are optional ??

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [launchModal]);
do we need `useCallback` here ??
https://kentcdodds.com/blog/usememo-and-usecallback

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/onboarding-modal.tsx
> +  const [ticket, _setTicket] = React.useState('dummy--text');
I am assuming that u r setting initial state to `dummy--text` and have `eslint-disable-next-line` comment as this modal is still WIP... and u did not forget to remove this...

2023-12-07 14:44 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +        setFlag(PROVIDER_MODE, isProviderMode(storageCluster));
just FYI, we will need to move this to redux later... `useODFSystemFlags` is already taking care of this, u just need to add a new field for `isProviderMode` in the object (exactly same as other flags)...

2023-12-07 14:44 UTC, SanjalKatiyar commented on plugins/odf/console-extensions.json
> +      "name": "%plugin__odf-console~Storage Clients%",
u need to add a comment in `odf/i18n-comments.ts` file to make it really work... I mean that's the correct way...

2023-12-07 14:44 UTC, SanjalKatiyar commented on plugins/odf/console-extensions.json
> +      "name": "%plugin__odf-console~Storage Clients%",
here it will work without adding a comment to `i18n-comments.ts` file as well because u already parsed `Storage Clients` in `status-card.tsx`, but that is a coincidence.

2023-12-08 06:44 UTC, bipuladh commented on packages/odf/components/storage-consumers/client-list.tsx
> +        <LastHeartBeat heartbeat={obj.status.lastHeartbeat} />
it should be always present. if it's not we will raise a bug on backend.

2023-12-08 06:44 UTC, bipuladh commented on packages/odf/components/storage-consumers/client-list.tsx
> +  obj.status.client.operatorVersion;
we will raise a bug on the backend

2023-12-08 06:44 UTC, bipuladh commented on packages/odf/components/storage-consumers/client-list.tsx
> +  hideColumnManagement?: boolean;
yes

2023-12-08 06:44 UTC, bipuladh commented on packages/odf/components/storage-consumers/onboarding-modal.tsx
> +  const [ticket, _setTicket] = React.useState('dummy--text');
`_setTicket` iis not being used so need this

2023-12-08 06:44 UTC, bipuladh commented on packages/odf/features.ts
> +        setFlag(PROVIDER_MODE, isProviderMode(storageCluster));
We need it is a flag to disable extensions for Provider mode.

2023-12-08 06:44 UTC, bipuladh commented on plugins/odf/console-extensions.json
> +      "name": "%plugin__odf-console~Storage Clients%",
ack

2023-12-08 06:45 UTC, bipuladh commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +};
removing

2023-12-08 06:46 UTC, bipuladh commented on packages/odf/components/odf-dashboard/status-card/status-card.tsx
> +  const clientAggregateHealth = getAggregateClientHealthState(clients);
I will add a default value in the function parameter.

2023-12-08 06:49 UTC, bipuladh commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [difference]);
using `useMemo` as we don't need to update the value if the difference is same.

2023-12-08 07:02 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [difference]);
https://github.com/red-hat-storage/odf-console/pull/1115#discussion_r1420020048

2023-12-08 07:04 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [difference]);
even then, it doesn't matter right ? I mean `Component` can either be `YellowExclamationTriangleIcon` or `RedExclamationCircleIcon`... all we are memoizing is two `if` conditions which are not expensive at all...

2023-12-08 07:05 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +        setFlag(PROVIDER_MODE, isProviderMode(storageCluster));
aahhh !!
so how will u set this in case of multiple storage cluster CR then ?? right now we are just taking first cluster and checking for the flag, this will not work for multiple clusters...

2023-12-08 07:10 UTC, bipuladh commented on packages/odf/features.ts
> +        setFlag(PROVIDER_MODE, isProviderMode(storageCluster));
are we supporting multiple clusters as part of 4.15?

2023-12-08 07:10 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +  return HealthState.UNKNOWN;
u missed this one ??

2023-12-08 07:16 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +        setFlag(PROVIDER_MODE, isProviderMode(storageCluster));
yeah 1 internal + 1 external... so multiple StorageCluster CRs can be present at a time...

2023-12-08 07:16 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +        setFlag(PROVIDER_MODE, isProviderMode(storageCluster));
we can filter internal one though... that will always be single

2023-12-08 07:23 UTC, bipuladh commented on packages/odf/components/odf-dashboard/status-card/utils.ts
> +  return HealthState.UNKNOWN;
yeah. updated the first case to make sure that we have more than 0 clients.

2023-12-08 07:23 UTC, SanjalKatiyar commented on packages/odf/components/storage-consumers/client-list.tsx
> +  obj.status.client.operatorVersion;
ack

2023-12-08 07:23 UTC, bipuladh commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [difference]);
removed memoization

2023-12-08 07:24 UTC, bipuladh commented on packages/odf/components/storage-consumers/client-list.tsx
> +  }, [launchModal]);
removed hook

2023-12-08 07:43 UTC, SanjalKatiyar commented
LGTM cc @GowthamShanmugam

2023-12-11 05:31 UTC, bipuladh commented
/test odf-console-e2e-aws

2023-12-12 09:28 UTC, SanjalKatiyar commented
/lgtm

2023-12-12 10:31 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-12-12 13:40 UTC, merged

2023-12-20 07:03 UTC, nehaberry commented
> Mock links: https://www.figma.com/proto/Afl7ntvufZTshGyuX701u7/Provider-mode?page-id=0%3A1&type=design&node-id=1-330&viewport=60%2C485%2C0.38&t=ngq3FBzQrHNQyEh6-1&scaling=min-zoom&starting-point-node-id=1%3A330

Do I need special login /password to access this?

Also, are these UI changes available in the provider base cluster dashboard?