Add cypress obc-test migration
red-hat-storage/odf-console pull request #122
Opened 2022-02-24 13:05 UTC by TimothyAsirJeyasing

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2022-02-24 13:05 UTC, TimothyAsirJeyasing commented
@bipuladh , @vbnrh Please review

2022-03-02 04:57 UTC, bipuladh requested changes

2022-05-18 05:11 UTC, TimothyAsirJeyasing commented on cypress/cypress-base/support/i18n.ts
> +Cypress.Commands.add('testI18n', (selectors: string[] = [], testIDs: string[] = []) => {
We are not using and i have removed this

2022-05-18 05:11 UTC, TimothyAsirJeyasing commented on cypress/cypress-base/support/i18n.ts
> +Cypress.Commands.add(
We are not using and i have removed this

2022-05-18 05:11 UTC, TimothyAsirJeyasing commented on cypress/cypress-base/support/selectors.ts
> +import Loggable = Cypress.Loggable;
Removed this

2022-05-18 05:12 UTC, TimothyAsirJeyasing commented on cypress/cypress-base/support/README.md
> +# Cypress Custom Commands
Yes not required, i have removed this

2022-05-18 05:12 UTC, TimothyAsirJeyasing commented on cypress/cypress-base/view/details-page.ts
> +export const detailsPage = {
Sure, Done

2022-05-18 05:12 UTC, TimothyAsirJeyasing commented on cypress/views/obcPage.ts
> +import { projectNameSpace } from '../support/pages/app';
Sure, Its done

2022-05-18 05:40 UTC, TimothyAsirJeyasing commented
@bipuladh Please review

2022-05-19 09:22 UTC, GowthamShanmugam commented on cypress/mocks/storageclass.ts
> +};
We dont need these two mockups, they can be removed or replaced with RBD and CephFs instead.

2022-05-19 09:37 UTC, GowthamShanmugam commented on cypress/support/pages/app.ts
> +import { detailsPage } from '../../cypress-base/support/details-page';
This is for developer perspective, we dont need this

2022-05-19 09:41 UTC, GowthamShanmugam commented on cypress/support/pageob.ts
> +  add: '[data-test-id="+Add-header"]',
We dont need this also, this is also dev perspective

2022-05-19 09:42 UTC, GowthamShanmugam commented on cypress/tests/obc-test.spec.ts
> +//import { detailsPage } from '../views/details-page';
```suggestion

```

2022-05-19 09:42 UTC, GowthamShanmugam commented on cypress/tests/obc-test.spec.ts
> +//import { listPage } from '../views/list-page';
```suggestion

```

2022-05-19 10:25 UTC, GowthamShanmugam commented on cypress/tests/obc-test.spec.ts
> +    cy.log('Test if owner and creation date are shown correctly');
```suggestion
    
```

2022-05-19 20:49 UTC, TimothyAsirJeyasing commented on cypress/mocks/storageclass.ts
> +};
Done

2022-05-19 20:49 UTC, TimothyAsirJeyasing commented on cypress/support/pages/app.ts
> +import { detailsPage } from '../../cypress-base/support/details-page';
Done

2022-05-19 20:50 UTC, TimothyAsirJeyasing commented on cypress/support/pageob.ts
> +  add: '[data-test-id="+Add-header"]',
Done

2022-05-19 20:50 UTC, TimothyAsirJeyasing commented on cypress/tests/obc-test.spec.ts
> +//import { detailsPage } from '../views/details-page';
Done

2022-05-19 20:51 UTC, TimothyAsirJeyasing commented on cypress/tests/obc-test.spec.ts
> +    cy.log('Test if owner and creation date are shown correctly');
Done

2022-05-19 20:51 UTC, TimothyAsirJeyasing commented
@bipuladh , @GowthamShanmugam , @SanjalKatiyar Please review

2022-05-23 11:49 UTC, TimothyAsirJeyasing commented
![Screenshot from 2022-05-17 13-37-53](https://user-images.githubusercontent.com/6670284/169812997-a2bebc53-5a70-47c2-b7b9-d920b43db1a5.png)

2022-06-03 08:47 UTC, TimothyAsirJeyasing commented
/retest

2022-06-17 17:40 UTC, TimothyAsirJeyasing commented
/test odf-console-e2e-aws

2022-06-18 09:22 UTC, TimothyAsirJeyasing commented
/test odf-console-e2e-aws

2022-06-21 05:33 UTC, bipuladh commented
/approve
/lgtm

2022-06-21 07:25 UTC, bipuladh commented
/retest

2022-06-21 08:58 UTC, merged