Should not allow to create a 2nd DR policy on existing cluster pair
red-hat-storage/odf-console pull request #1324
Opened 2024-04-23 09:35 UTC by GowthamShanmugam

2024-04-23 09:36 UTC, GowthamShanmugam commented
![image](https://github.com/red-hat-storage/odf-console/assets/15073590/ca213df2-2ebb-4a3f-8475-7736aee06b0c)

2024-04-23 15:27 UTC, alfonsomthd requested changes

2024-04-23 15:27 UTC, alfonsomthd commented on packages/mco/components/create-dr-policy/select-replication-type.tsx
> +  selelctedClusters: string[]
Typo:
```suggestion
  selectedClusters: string[]
```

2024-04-23 16:13 UTC, alfonsomthd commented
/approve

2024-04-23 16:15 UTC, alfonsomthd commented
/lgtm

2024-04-24 15:19 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
>    "Delete {{kind}}?": "Delete {{kind}}?",
this might get resolved, once you rebase with latest master and run i18n command again...

2024-04-24 15:24 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-replication-type.tsx
> +    );
let's handle loading and error state, for at-least MDR ?

`policyLoaded = replicationType === REPLICATION_TYPE.SYNC && loaded`

`policyError =  replicationType === REPLICATION_TYPE.SYNC && error`

2024-04-24 15:25 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-replication-type.tsx
> +    replicationType === REPLICATION_TYPE.SYNC &&
probably store `replicationType === REPLICATION_TYPE.SYNC` in a boolean variable too...

2024-04-24 15:28 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-replication-type.tsx
> +  drPolicies: DRPolicyKind[],
```suggestion
  drPolicies: DRPolicyKind[] = [],
```

2024-04-24 15:30 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-replication-type.tsx
> +    return isSyncPolicy && isClustersMatches;
nits (optional): no need to run `every` if policy is `async`...
```suggestion
    return isSyncPolicy && drClusters.every((cluster) =>
      selectedClusters.includes(cluster)
    );
```

2024-04-24 16:09 UTC, GowthamShanmugam commented on packages/mco/components/create-dr-policy/select-replication-type.tsx
> +  drPolicies: DRPolicyKind[],
i am changing code like 
loaded && !!loadError && replicationType === REPLICATION_TYPE.SYNC && checkSyncPolicyAlreadyExists(drPolicies, selectedClusters.map((cluster) => cluster.name))

So this change not required

2024-04-24 16:11 UTC, GowthamShanmugam commented
I really hate entire create policy flow implementation :(, entire code need refactoring in future.

2024-04-25 05:20 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/create-dr-policy.tsx
>    // odfmco mirrorpeer info
nits: we probably can remove this commit :)

2024-04-25 08:19 UTC, GowthamShanmugam commented on packages/mco/components/create-dr-policy/create-dr-policy.tsx
>    // odfmco mirrorpeer info
ack

2024-04-25 11:12 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2024-04-25 11:34 UTC, SanjalKatiyar commented
/approve
/lgtm

2024-04-25 11:34 UTC, SanjalKatiyar commented
/cherry-pick release-4.16

2024-04-25 11:34 UTC, SanjalKatiyar commented
/cherry-pick release-4.16-compatibility

2024-04-25 14:39 UTC, merged