Add Tech preview message for Azure Key Vault
red-hat-storage/odf-console pull request #1343
Opened 2024-04-29 11:18 UTC by TimothyAsirJeyasing

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2277711

2024-04-29 13:20 UTC, alfonsomthd requested changes

2024-04-29 13:20 UTC, alfonsomthd commented on packages/odf/components/kms-config/kms-config.tsx
> +    name: 'Azure Key Vault (Tech preview)',
Do we need translations for this, right?
```suggestion
    name: t('Azure Key Vault (Tech preview)'),
```

2024-05-03 09:38 UTC, alfonsomthd commented
/lgtm

2024-05-03 10:05 UTC, TimothyAsirJeyasing commented
![image](https://github.com/red-hat-storage/odf-console/assets/6670284/ea1b3e98-9ca6-4fae-be33-55258b9f0968)

2024-05-08 08:09 UTC, SanjalKatiyar commented
/lgtm cancel

2024-05-08 08:10 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +        name: t('Azure Key Vault (Tech preview)'),
plz revert it back like it was earlier... we do not translate product name...
```suggestion
        name: Vault,
        value: ProviderNames.VAULT,
        Component: VaultConfigure,
      },
      {
        name: Hyper Protect Crypto Services,
        value: ProviderNames.HPCS,
        Component: HpcsConfigure,
        allowedPlatforms: ['IBMCloud'],
      },
      {
        name: Thales CipherTrust Manager (using KMIP),
        value: ProviderNames.THALES,
        Component: ThalesConfigure,
      },
      {
        name: Azure Key Vault,
```

2024-05-08 08:11 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +        name: t('Azure Key Vault (Tech preview)'),
this is wrong... plz talk with UX this is not how we add a TP label... we have a separate FC for this that needs to be added to the dropdown item, not here...

2024-05-08 08:12 UTC, SanjalKatiyar commented on packages/odf/constants/kms.ts
> +    group: t('Vault'),
plz revert back all these changes...

2024-05-08 08:12 UTC, SanjalKatiyar commented on packages/odf/constants/kms.ts
> +    group: t('Vault'),
unrelated to this PR, also these hard values are used for filtering... unless tested properly, it could lead to regression...

2024-05-08 08:13 UTC, SanjalKatiyar commented on packages/odf/constants/kms.ts
> +    group: t('Thales CipherTrust Manager (using KMIP)'),
```suggestion
    group: Thales CipherTrust Manager (using KMIP),
```

2024-05-08 08:13 UTC, SanjalKatiyar commented on packages/odf/constants/kms.ts
> +    group: t('Azure Key Vault (Tech preview)'),
```suggestion
    group: Azure Key Vault (Tech preview),
```

2024-05-08 11:11 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
> +        name: t('Azure Key Vault (Tech preview)'),
Thank you, To add the Tech Preview badge next to the "Azure Key Vault" option. I attempted to implement this, but encountered a limitation with the PatternFly library. The FormSelectOption component we have used here for the dropdown option strictly accepts only strings for its label property and does not support React Elements. ...

2024-05-08 11:12 UTC, TimothyAsirJeyasing commented on packages/odf/constants/kms.ts
> +    group: t('Hyper Protect Crypto Services'),
ack

2024-05-08 11:12 UTC, TimothyAsirJeyasing commented on packages/odf/constants/kms.ts
> +    group: t('Thales CipherTrust Manager (using KMIP)'),
done

2024-05-09 07:55 UTC, TimothyAsirJeyasing commented
![Screenshot from 2024-05-09 13-21-27](https://github.com/red-hat-storage/odf-console/assets/6670284/b16ceff5-e2bf-487b-8e23-bc5f58a901d9)

2024-05-09 08:37 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +            </SelectOption>
what's the issue with this ?
```suggestion
            <FormSelectOption
              value={provider.value}
              label={<>{provider.name} <TechPreviewBadge /></>}
              key={provider.value}
            />
```

2024-05-09 08:38 UTC, SanjalKatiyar commented
> ![Screenshot from 2024-05-09 13-21-27](https://private-user-images.githubusercontent.com/6670284/329170406-b16ceff5-e2bf-487b-8e23-bc5f58a901d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQxNjcsIm5iZiI6MTcxNTI0Mzg2NywicGF0aCI6Ii82NjcwMjg0LzMyOTE3MDQwNi1iMTZjZWZmNS1lMmJmLTQ4N2ItOGUyMy1iYzVmNThhOTAxZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDgzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTlhMjc5ZjEzYmMwYTIyOWI3NTAxMjFiMTU0NjBjOGRlYWVjNWRlZDExOGUyNjMzZTA1NGRlN2Y4MDI2YjY0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.S-kE3heS1ZxvwMlfB9Fe1fiVc7GhTZjKfPS06NFGQv4) ![image](https://private-user-images.githubusercontent.com/6670284/329174247-f2622d7f-1967-4edc-be8e-e2c89468e81b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQxNjcsIm5iZiI6MTcxNTI0Mzg2NywicGF0aCI6Ii82NjcwMjg0LzMyOTE3NDI0Ny1mMjYyMmQ3Zi0xOTY3LTRlZGMtYmU4ZS1lMmM4OTQ2OGU4MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDgzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2UxNTAwOWQxOGM0MDBjYzQ5NTNiYzYyMzZiY2VlZjIzYTIwMTRhYmNjZTU0MzRlZDFlZjM1NTk1MWNlNDk1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EHhlDVimltIF6rDtb8ZgmphDBhmz-4FJoWiEVPpU_HI)

is this suggested by UX ?

2024-05-09 08:46 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
> +            </SelectOption>
FormSelectOptionProps.label is expecting a string

2024-05-09 09:06 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
>            isDisabled={isLengthUnity(allowedKMSProviders)}
does `Select` even has `isDisabled` field ??

2024-05-09 09:09 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +          toggle={toggle}
add `selected`...

2024-05-09 09:10 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +          toggle={toggle}
check whether we need `onOpenChange` or not...

2024-05-09 09:12 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +      className={'pf-v5-c-form-control'}
u really need this class ??
```suggestion
      className='pf-v5-c-form-control'
```

2024-05-09 09:37 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
> +      className={'pf-v5-c-form-control'}
yes, otherwise the size is very small and not align with other text box in the ui

2024-05-09 10:08 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
>            isDisabled={isLengthUnity(allowedKMSProviders)}
While building, it does not throw any error, so I assumed it is supported. However, upon referring to the documentation, I couldn’t find the isDisabled field for the Select component.  I will move this to MenuToggle

2024-05-09 10:26 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
> +          toggle={toggle}
Okay, I checked. The onOpenChange is not required because we are already handling the open/close state of the dropdown with a local state managed by isOpen and controlled via the onToggleClick function

2024-05-09 10:30 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +          toggle={toggle}
it is not used for that, `onOpenChange` has diff use case...

2024-05-09 11:01 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
> +          toggle={toggle}
Done

2024-05-09 13:18 UTC, TimothyAsirJeyasing commented
![Screenshot from 2024-05-09 18-39-40](https://github.com/red-hat-storage/odf-console/assets/6670284/4c599a99-b4a7-42e9-95c5-6069973b1712)

2024-05-09 15:14 UTC, TimothyAsirJeyasing commented
![image](https://github.com/red-hat-storage/odf-console/assets/6670284/bb247d6a-8e85-4cb7-9f83-00d79cae7df4)

2024-05-14 04:24 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2024-05-14 04:42 UTC, SanjalKatiyar commented on packages/shared/src/badges/Badge.scss
> +    --pf-v5-c-label--m-orange__icon--Color: var(--	--pf-v5-c-label--m-orange__content--Color);
```suggestion
    --pf-v5-c-label--m-orange__icon--Color: var(--pf-v5-c-label--m-orange__content--Color);
```

2024-05-14 04:43 UTC, SanjalKatiyar commented on packages/shared/src/badges/Badge.scss
> +    );
from where this value coming from ?

2024-05-14 04:43 UTC, SanjalKatiyar commented on packages/shared/src/badges/Badge.scss
> +    );
I mean how do we know which class to apply...

2024-05-14 05:51 UTC, TimothyAsirJeyasing commented on packages/shared/src/badges/Badge.scss
> +    );
Sorry, I did not noticed this while i copy from the console badge.scss. Yes its not defined anywhere and its using the default one. I will remove this.

2024-05-14 06:05 UTC, TimothyAsirJeyasing commented
![image](https://github.com/red-hat-storage/odf-console/assets/6670284/424c6362-bf50-427e-b3fe-bc766f2ae1fd)

2024-05-14 09:07 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/kms-config.tsx
> +          onOpenChange={setIsOpen}
can optimize the code by using SingleSelectDropdown?

2024-05-14 09:24 UTC, GowthamShanmugam commented on packages/shared/src/badges/Badge.scss
> +    --pf-v5-c-label--BorderRadius: 30em;
Do these changes not affect the other places? Is this tested with others who are all using badges?

2024-05-14 09:44 UTC, TimothyAsirJeyasing commented on packages/shared/src/badges/Badge.scss
> +    --pf-v5-c-label--BorderRadius: 30em;
Currently ocs-preview-badge is used only for TechPreviewBadge and the TechPreviewBadge is used only for Azure Kms. Also its based on the discussion we agree to go with one design https://ibm-systems-storage.slack.com/archives/C06SS96EECT/p1715261556528409?thread_ts=1714389611.825559&cid=C06SS96EECT

2024-05-14 10:02 UTC, TimothyAsirJeyasing commented on packages/odf/components/kms-config/kms-config.tsx
> +          onOpenChange={setIsOpen}
I have used the patternfly select work smoothly with darkmode and other settings also this techpreview badge we added to Azure KMS will go away in the next release and i feel this change is a temporary one. We may need to revert back to old listing kind. So if its very necessary i can use SingeSelectDropdown. What is your view on this ?

2024-05-14 10:09 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/kms-config.tsx
> +          onOpenChange={setIsOpen}
We have already implemented select dropdown behavior in SingeSelectDropdown it will minimize the number of code that has been written here.

2024-05-14 11:14 UTC, SanjalKatiyar commented
/approve
/lgtm

2024-05-14 11:14 UTC, SanjalKatiyar commented
/cherry-pick release-4.16

2024-05-14 11:14 UTC, SanjalKatiyar commented
/cherry-pick release-4.16-compatibility

2024-05-14 14:42 UTC, merged