remove usage of setFlag from wizard footer.tsx
red-hat-storage/odf-console pull request #137
Opened 2022-03-07 06:33 UTC by SanjalKatiyar

https://issues.redhat.com/browse/RHSTOR-2805

2022-03-07 06:38 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +};
Still need to add an extension `"type": "console.flag"`

2022-03-08 03:23 UTC, bipuladh requested changes

2022-03-08 03:23 UTC, bipuladh commented on packages/odf/features.ts
> +      if (storageClusters?.length > 0) {
else let's set set these all flags to false.

2022-03-08 08:20 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +      if (storageClusters?.length > 0) {
won't it trigger re-render unnecessarily every 15 sec in this case until storageClusters is found ??

2022-03-08 08:20 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +      if (storageClusters?.length > 0) {
I can use a flag to set all flags to false only once...

2022-03-11 11:54 UTC, bipuladh requested changes

2022-03-11 11:54 UTC, bipuladh commented on packages/odf/features.ts
> +        setFlag(OCS_INDEPENDENT_FLAG, false);
Let's setup MCG standalone as false as well( also in the catch statement)

2022-03-14 15:46 UTC, afreen23 requested changes

2022-03-14 15:46 UTC, afreen23 commented on packages/odf/features.ts
> +  // untill storageClusters are found
```suggestion
  // until storageClusters are found
```

2022-03-14 15:48 UTC, afreen23 requested changes

2022-03-14 15:48 UTC, afreen23 commented on packages/odf/features.ts
> +const setFlagsFalse = (setFlag: SetFeatureFlag) => {
```suggestion
const setOCSFlagsFalse = (setFlag: SetFeatureFlag) => {
```

2022-03-14 17:57 UTC, afreen23 approved these changes

2022-03-14 17:58 UTC, afreen23 commented
/lgtm cancel

@bipuladh review pending

2022-03-16 06:57 UTC, bipuladh commented
/lgtm

2022-03-16 10:12 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-03-16 12:02 UTC, merged