Add package and extensions for Multicluster orchestrator operator UI
red-hat-storage/odf-console pull request #138
Opened 2022-03-07 13:18 UTC by afreen23

Signed-off-by: Afreen Rahman <afrahman@redhat.com>

2022-03-07 13:23 UTC, GowthamShanmugam commented on console-extensions.json
> +        "id": "data-services",
```suggestion
        "id": "odf-data-services",
```

2022-03-07 13:33 UTC, GowthamShanmugam commented on console-extensions.json
> +      "href": "/odf/edit/dr/policy"
data policies are common between different policy types. Also, lets not use the name of anywhere in the URL.

I suggest to stick with ACM console URL: /multicloud/dataservices/datapolicies

2022-03-07 14:15 UTC, GowthamShanmugam commented on console-extensions.json
> +      "path": "/data-services/data-policies",
no need /multicloud/?

2022-03-07 14:56 UTC, bipuladh requested changes

2022-03-07 14:56 UTC, bipuladh commented on packages/multicluster-orchestrator/package.json
> +      "@odf/core": "0.0.0"
```suggestion
      "@odf/shared": "0.0.0"
```

2022-03-07 20:49 UTC, GowthamShanmugam commented on packages/multicluster-orchestrator/package.json
> +    "name": "@odf/mco",
```suggestion
    "name": "@odf/multicluster-orchestrator",
```

2022-03-07 20:49 UTC, GowthamShanmugam commented on package.json
> +      "dataPolicies": "@odf/mco/components/data-polices"
```suggestion
      "dataPolicies": "@odf/multicluster-orchestrator/components/data-polices"
```

2022-03-07 20:51 UTC, GowthamShanmugam commented on packages/multicluster-orchestrator/components/data-policies-list.tsx
> +import * as React from 'react';
move file inside data-polices folder

2022-03-08 05:05 UTC, cloudbehl commented on console-extensions.json
> +      "href": "/data-services/data-policies"
Does ACM or OCP create href based on the left nav?

Like we want to add `Data Services` and under that, we will have data policies and etc. Is it a common pattern to create URL like  `/data-services/data-policies`?

2022-03-09 07:41 UTC, afreen23 commented on console-extensions.json
> +      "href": "/odf/edit/dr/policy"
ack

2022-03-09 07:42 UTC, afreen23 commented on packages/multicluster-orchestrator/package.json
> +    "name": "@odf/mco",
I renamed package folder

2022-03-09 07:43 UTC, afreen23 commented on packages/multicluster-orchestrator/components/data-policies-list.tsx
> +import * as React from 'react';
done

2022-03-09 07:44 UTC, afreen23 commented on console-extensions.json
> +      "href": "/data-services/data-policies"
We need add /multicloud before, added now.

2022-03-09 08:09 UTC, bipuladh requested changes

2022-03-09 08:09 UTC, bipuladh commented on console-extensions.json
> +  },
These need to be guarded based on presence of MCO and the rest of the extensions.

2022-03-09 08:10 UTC, afreen23 commented on console-extensions.json
> +  },
We dont need to do this atm. When we mature , we will put it.
This is to start dev work.

2022-03-09 08:38 UTC, afreen23 commented on console-extensions.json
> +  },
Also, guarding might not be needed since it will go under ACM perspective, we still need to evaluate such things.
Its our first PR for MCO to kick off development

2022-03-09 09:31 UTC, afreen23 commented
There was  typo with exporting package name, hence tests were failing.
Fixed it now.

2022-03-09 09:46 UTC, bipuladh commented
/lgtm

2022-03-09 10:49 UTC, merged