support negative values in humanizeBinaryBytes
red-hat-storage/odf-console pull request #1469
Opened 2024-07-15 07:04 UTC by weirdwiz

this commit adds support for negative values withing
humanizeBinaryBytes, we need to also convert negative values to human
readable form to accommodate negative values in capacity trend card.

2024-07-16 09:00 UTC, SanjalKatiyar commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
`humamizeNegative` pass this optional parameter, default value of this should be `false` so that it won't affect existing graphs where this utility is used...
```suggestion
const shouldHumamizeNegative = humamizeNegative && value < 0;
```

2024-07-16 09:01 UTC, SanjalKatiyar commented on packages/shared/src/utils/humanize.js
> +  value = Math.abs(value);
```suggestion
if (shouldHumamizeNegative) {
  value = Math.abs(value);
}
```

2024-07-16 09:01 UTC, SanjalKatiyar commented on packages/shared/src/utils/humanize.js
> +  if (isNegative) {
```suggestion
  if (shouldHumamizeNegative) {
```

2024-07-18 12:06 UTC, weirdwiz commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
we don't need to pass the argument, because this should be the correct if a graph would ever encounter a negative value

2024-07-18 14:19 UTC, SanjalKatiyar commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
argument is because we don't want to affect any existing graphs which are using this util... we never had any bugs on those existing graphs, so better to keep their working as it is...

2024-07-19 05:40 UTC, SanjalKatiyar commented
plz add screenshots...

2024-07-19 05:44 UTC, SanjalKatiyar commented on packages/shared/src/generic/FieldLevelHelp.tsx
> +          {buttonText}{' '}
```suggestion
          {!!buttonText && (buttonText + ' ')}
```

2024-07-19 05:50 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/utilization-item.tsx
> +import { ChartThemeColor } from '@patternfly/react-charts';
```suggestion
import { ChartThemeColor, ChartLegend } from '@patternfly/react-charts';
```

2024-07-19 05:50 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/utilization-item.tsx
> +import { ChartLegend } from '@patternfly/react-charts/dist/js/components/ChartLegend/ChartLegend';
```suggestion
```

2024-07-19 05:58 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/utilization-item.tsx
> +      );
let PF decide the default behaviour by itself (they can decide to use something other than `ChartLegend` as well)
```suggestion
    let humanizedLegend:  JSX.Element;
      if (!!showHumanizedInLegend && current)
        humanizedLegend = <ChartLegend
          themeColor={ChartThemeColor.purple}
          data={[{ name: description + ' : ' + humanizeValue(current).string }]}
        />
```

2024-07-19 06:00 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/utilization-item.tsx
> +        legendComponent={humanizedLegend}
```suggestion
              {...(!!humanizedLegend
                ? { legendComponent: humanizedLegend }
                : {}
               )}
```

2024-07-19 06:01 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
> +        showHumanizedInLegend={showHumanizedInLegend}
nits:
```suggestion
       {...(!!showHumanizedInLegend ? showHumanizedInLegend : {})}
```

2024-07-19 06:02 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/utilization-item.tsx
> +        legendComponent={humanizedLegend}
feel free to skip this comment, if needed...

2024-07-19 06:03 UTC, SanjalKatiyar commented on packages/shared/src/dashboards/utilization-card/prometheus-utilization-item.tsx
> +        showHumanizedInLegend={showHumanizedInLegend}
feel free to skip this comment, if needed...

2024-07-19 06:03 UTC, weirdwiz commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
I don't think it will affect any graph, the behaviour is the same eg: "100000" would be "12,5KiB" but this change just changes "-100000" -> "-100000B" to "-100000"->"-12.5KiB"

2024-07-19 06:05 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
>                    {t('Estimated days until full')}
how are u handling this estimated days when average is -ve ??

2024-07-19 06:06 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
>                    {t('Estimated days until full')}
it will be buggy as per current implementation...

2024-07-19 06:09 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +                  {t('Average Storage Consumption')}
```suggestion
                  {t('Average storage consumption')}
```

2024-07-19 06:12 UTC, SanjalKatiyar commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
let the behaviour same at other places as it is right now, no need to humanize or anything... fix it for the specific case where u really need to based on arg...
`shared` components are not just used by ODF, but other plugins as well... it is a library... don't make any assumptions and add a generic fix (unless really needed) and add optional changes instead...

2024-07-19 06:13 UTC, SanjalKatiyar commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
let the behaviour/flow same at other places as it is right now... fix it for the specific case where u really need to based on arg...
`shared` components are not just used by ODF, but other plugins as well... it is a library... don't make any assumptions and add a generic fix (unless really needed) and add optional changes instead...

2024-07-19 06:16 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +              </FieldLevelHelp>
can u check whether it needs sm or xs margin/padding on right ?? I see in screenshots, it's slightly with other options like `Average storage consumption` etc...

2024-07-19 06:32 UTC, alfonsomthd requested changes

2024-07-19 06:32 UTC, alfonsomthd commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +          Indicates the number of days remaning before a storage system reaches
```suggestion
          Indicates the number of days remaining before a storage system reaches
```

2024-07-19 06:32 UTC, alfonsomthd commented on packages/shared/src/generic/FieldLevelHelp.tsx
> +  ({ children, popoverHasAutoWidth, testId, buttonText }) => {
Please rebase as I added `position` prop in a recently merged PR.

2024-07-19 06:32 UTC, alfonsomthd commented on packages/shared/src/utils/humanize.js
> +  if (value < 0) isNegative = true;
@SanjalKatiyar I agree with you about keeping the current behaviour but the best way to keep peace of mind is to add several unit tests for the utility that ensure the default behaviour as well as the correctness of the new one.

2024-07-22 10:08 UTC, SanjalKatiyar commented
@weirdwiz can u plz update the PR ??

2024-07-22 10:16 UTC, weirdwiz commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +              </FieldLevelHelp>
if we do auto popover width, the paragraphs will overflow out of the screen

2024-07-22 10:16 UTC, weirdwiz commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +              <FieldLevelHelp buttonText={t('Understanding these terms')}>
https://github.com/red-hat-storage/odf-console/pull/1469#discussion_r1686318039

2024-07-22 10:16 UTC, weirdwiz commented on packages/shared/src/generic/FieldLevelHelp.tsx
> +  ({ children, popoverHasAutoWidth, testId, buttonText }) => {
done

2024-07-22 10:17 UTC, weirdwiz commented
> @weirdwiz can u plz update the PR ??
updated, still trying to find a fix for negative average values for estimated days, albiet it's an extremely rare case (considering we need to empty the cluster on a massive scale (more than the retention period)) it's a little hard to test

2024-07-22 13:28 UTC, alfonsomthd commented
> > @weirdwiz can u plz update the PR ??
> 
> updated, still trying to find a fix for negative average values for estimated days, albiet it's an extremely rare case (considering we need to empty the cluster on a massive scale (more than the retention period)) it's a little hard to test

Apart from the above ongoing fix, LGTM. Tagging delegated to @SanjalKatiyar

2024-07-22 14:17 UTC, SanjalKatiyar commented
LGTM.

Pending things:
1. https://github.com/red-hat-storage/odf-console/pull/1469#discussion_r1683842700
2. Squashing the commits.
3. CI is failing (probably a flake ?)

2024-07-23 09:17 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +  }
can u add a comment explaining why we did it ??

2024-07-23 09:22 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +  }
cluster_clean_up__to_zero_days = `totalUtilMetric / Math.abs(avgUtilMetric)`;

cluster_fill_up_to_max_days = totalCapacityMetric / Math.abs(avgUtilMetric);

2024-07-23 09:23 UTC, weirdwiz commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +  }
i merged the wrong commit while squashing, fixed it sending an update right now

2024-07-23 09:23 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +  }
total = `cluster_clean_up__to_zero_days + cluster_fill_up_to_max_days`

2024-07-23 09:34 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +    const cluster_fill_up_to_max_days =
I comment using `_` case for reference... we don't follow that in repo...
```suggestion
    const clusterCleanUpToZeroDays =
      totalUtilMetric / Math.abs(avgUtilMetric);
    const clusterFillUpToMaxDays =
```

2024-07-23 09:35 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +    const cluster_clean_up_to_zero_days =
there is one issue here... since we are using `totalUtilMetric`, this is not exactly giving us `clean_up_to_zero_day`, instead giving us the days in which cluster will reach the state which it was "n" (uptime) days ago...

2024-07-23 09:37 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +    const cluster_clean_up_to_zero_days =
whereas `cluster_fill_up_to_max_days` considers filling up from zero to max...

2024-07-23 09:37 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +    const cluster_clean_up_to_zero_days =
I know it's an estimate, but ideally both values ("cluster_clean_up_to_zero_days" & "cluster_fill_up_to_max_days") should make similar assumptions while calculation...

2024-07-23 09:38 UTC, weirdwiz commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +    const cluster_clean_up_to_zero_days =
ah, so i think we should use the total used capacity instead of the delta

2024-07-23 09:38 UTC, weirdwiz commented on packages/ocs/dashboards/persistent-internal/capacity-trend-card/capacity-trend-card.tsx
> +    const cluster_fill_up_to_max_days =
oops, fixing

2024-07-23 10:12 UTC, SanjalKatiyar commented
/approve

2024-07-23 10:13 UTC, SanjalKatiyar commented
/lgtm cancel
cc @bipuladh @alfonsomthd for final tagging.

2024-07-23 10:14 UTC, SanjalKatiyar commented
/approve

2024-07-23 11:46 UTC, GowthamShanmugam approved these changes

2024-07-23 11:46 UTC, GowthamShanmugam commented
/LGTM

2024-07-23 11:54 UTC, alfonsomthd commented
/retest

2024-07-23 12:16 UTC, weirdwiz commented
/retest

2024-07-23 12:17 UTC, weirdwiz commented
/test images

2024-07-23 12:36 UTC, weirdwiz commented
/retest

2024-07-23 12:50 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2024-07-23 12:50 UTC, SanjalKatiyar commented
/test images

2024-07-23 12:54 UTC, SanjalKatiyar commented
/retest

2024-07-23 13:14 UTC, SanjalKatiyar commented
/retest

2024-07-23 13:29 UTC, SanjalKatiyar commented
/retest

2024-07-23 13:34 UTC, SanjalKatiyar commented
/lgtm

2024-07-23 16:08 UTC, bipuladh commented
/lgtm

2024-07-23 17:27 UTC, merged