Add the dr-list page
red-hat-storage/odf-console pull request #147
Opened 2022-03-15 13:09 UTC by RishabhKodes

Initialized the Disaster recovery list page and created the headers for the list.

2022-03-23 08:28 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +        <TableData {...tableColumnInfo[2]} activeColumnIDs={activeColumnIDs}>
Values are hardcoded for now, once ramen dependency PR is ready, we will modify this to actual value

2022-03-23 09:17 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +      </ListPageHeader>
```suggestion
      <ListPageHeader title={t('DR Policies')}>
          <ListPageCreateLink to={createProps}>
            {t('Create DRPolicy')}
          </ListPageCreateLink>
      </ListPageHeader>
```

2022-03-23 09:18 UTC, SanjalKatiyar commented on packages/mco/models/disaster-recovery.ts
> +
```suggestion
```

2022-03-23 09:18 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/159665214-9db8a57d-d418-414f-81b4-6ba599f35b33.png)

2022-03-23 09:19 UTC, SanjalKatiyar commented on packages/mco/models/disaster-recovery.ts
> +
```suggestion
import { K8sModel } from '@openshift-console/dynamic-plugin-sdk/lib/api/common-types';

```
Don't use kubevirt anywhere...

2022-03-23 09:20 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +        <TableData {...tableColumnInfo[2]} activeColumnIDs={activeColumnIDs}>
ack...

2022-03-23 09:24 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/data-policies-list.tsx
>  import * as React from 'react';
we should change the file name (can be done later)...
`data-policies-list.tsx` seems like this is only for data-policies whereas later this will contain other horizontal nav items as well...

2022-03-23 09:30 UTC, SanjalKatiyar commented
> ![image](https://user-images.githubusercontent.com/15073590/159665214-9db8a57d-d418-414f-81b4-6ba599f35b33.png)

designs did not had this `ListPageHeader: "DR Policies"`.

2022-03-23 09:33 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +      </ListPageHeader>
btw designs did not had this  `DR Policies` header.

2022-03-24 07:55 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> -          </ListPageCreateLink>
why remove this ? we need the create button...

2022-03-24 15:34 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +      <ListPageHeader title={''}>
.

2022-03-24 15:39 UTC, RishabhKodes commented
![image](https://user-images.githubusercontent.com/41220684/159954263-67ae43d7-e2b8-461f-ac17-7de4268fbade.png)

2022-03-24 15:58 UTC, SanjalKatiyar approved these changes

2022-03-24 15:59 UTC, SanjalKatiyar commented
/retest

2022-03-28 11:04 UTC, GowthamShanmugam approved these changes

2022-03-28 11:04 UTC, GowthamShanmugam commented
/retest

2022-03-28 11:15 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-03-28 18:35 UTC, GowthamShanmugam commented
/retest-required

2022-03-29 16:21 UTC, GowthamShanmugam commented
/retest-required

2022-03-30 01:23 UTC, bipuladh requested changes

2022-03-30 01:23 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +        </TableData>
Where is the Kebab menu?

2022-03-30 01:23 UTC, bipuladh commented on packages/mco/models/disaster-recovery.ts
> +import { K8sModel } from '@openshift-console/dynamic-plugin-sdk/lib/api/common-types';
The original models file is fine.

2022-03-30 01:23 UTC, bipuladh commented on packages/mco/types/disaster-recovery.ts
> +import { K8sResourceCommon } from '@openshift-console/dynamic-plugin-sdk';
Have one file name types.ts

2022-03-30 09:01 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +        </TableData>
it is seperate PR

2022-03-31 08:48 UTC, RishabhKodes commented on packages/mco/types/disaster-recovery.ts
> +import { K8sResourceCommon } from '@openshift-console/dynamic-plugin-sdk';
there's already a `types.ts` present

2022-03-31 10:06 UTC, GowthamShanmugam commented on packages/mco/types/types.ts
> +export const DRPolicyModel: K8sModel = {
Why you created model inside types?

2022-03-31 11:13 UTC, GowthamShanmugam approved these changes

2022-03-31 11:13 UTC, GowthamShanmugam commented
/assign bipuladh

2022-03-31 12:31 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +          {"Synchronous"}
This value we are stuck due to reamen spec change, it is inprogress, we will change it once it is ready.

2022-03-31 13:48 UTC, bipuladh requested changes
Squash the commits as well

2022-04-05 06:33 UTC, bipuladh approved these changes

2022-04-05 08:35 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-05 08:47 UTC, merged