Use ManagedClusterView for ODF info - DRPolicy creation
red-hat-storage/odf-console pull request #1470
Opened 2024-07-15 16:29 UTC by SanjalKatiyar

https://bugzilla.redhat.com/show_bug.cgi?id=2297447

### Before:
OCS used to create multiple ClusterClaims and MCO console used to read ODF info (StorageCluster, Ceph details) from ManageCluster CR's status.

### After:
https://github.com/red-hat-storage/ocs-operator/pull/2440
https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/219
OCS now creates a single ConfigMap (with all the StorageClusters, Clients details) and a single ClusterClaim (with ConfigMap's namespaced-name details), MCO creates the corresponding ManagedClusterView referencing this ConfigMap and MCO console reads ODF info from the ManagedClusterView CR.

2024-07-15 16:34 UTC, SanjalKatiyar commented
/hold
wait for operator PRs to get merged first...

2024-07-16 13:45 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        isDROptimized: true,
clean this up...

2024-07-16 13:46 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> -  ClusterClaimTypes,
remove the enum from `constants` as well...

2024-07-16 13:46 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        isDROptimized: false,
clean this up...

2024-07-16 13:47 UTC, SanjalKatiyar commented
remove clusterclaim checks from DRPolicy creation unit tests...

2024-07-19 09:00 UTC, vbnrh requested changes

2024-07-19 11:08 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        ? storageClusterName + '/' + storageClusterNamespace
yeah... but while splitting (in various files) we are currently expecting the `name/namespace` format...

2024-07-19 11:09 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        return acc;
`ValidateManagedClusterCondition(cluster, MANAGED_CLUSTER_JOINED)` step has already been taken care of before even calling this function...

2024-07-19 11:10 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        return acc;
all the "cluster" it receives will be `MANAGED_CLUSTER_JOINED`

2024-07-19 11:13 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
I don't think we can filter on the basis of `spec` (during GET request)... for filtering we need unique label or expression... do u mean something else ??
Anyway if MCO is creating a combined ConfigMap, UI can just poll that based on name & namespace, can you confirm it once ??

2024-07-19 11:16 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +    console.error(err);
UI will be error out and user will be notified anyway in this case...
this is more of a console logging, we can choose to remove it as well... I only added it here because we are logging similarly at few other places as well... but yeah I don't think it is really needed...

2024-07-19 11:45 UTC, vbnrh commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        return acc;
Got it, precisely why early returning is preferred.

2024-07-19 11:45 UTC, vbnrh commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
Yeah you can use the configmap now 
[ClusterName/ClientName] = ClientInfo

2024-07-19 11:48 UTC, vbnrh commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
@SanjalKatiyar Or since you already have the ManagedCluster and watching it, you can check if it contains the clusterClaim and fetch the MCV on demand instead of watching all of them.

Each MCV is mapped to the ManagedCluster

2024-07-19 11:49 UTC, vbnrh commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        ? storageClusterName + '/' + storageClusterNamespace
Ok, can't do anything except leave it up for later changes in all the files

2024-07-19 12:06 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
on demand here would mean a new API call everytime user select (or un-select and re-select) a cluster from the list... which will amount to multiple calls and corresponding waiting/loading on UI...

compared to that, currently it's just a single connection request (for entire list of MCVs) and later filtering based ManagedCluster CRs...

I see the concern here of component re-rendering for unrelated MCVs, for which I can either rely on "created-by" label which MCO is adding (for filtering) or maybe shift to ConfigMap approach, given once MCO flow is finalised and the PR is merged.

2024-07-22 12:40 UTC, GowthamShanmugam commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
ack

2024-07-23 09:44 UTC, GowthamShanmugam commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
is this createdBy by label selector has to be updated in this PR?

2024-07-23 14:17 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
I have to resolve conflicts and do some clean-up... will add label selector in this PR as well...

2024-07-23 14:17 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +
will add it...

2024-07-23 14:17 UTC, SanjalKatiyar commented on packages/mco/components/create-dr-policy/select-cluster-list.tsx
> +        }
ack...

2024-07-24 06:42 UTC, SanjalKatiyar commented
/hold cancel

2024-07-24 06:46 UTC, SanjalKatiyar commented
/retitle Bug 2297447: Use ManagedClusterView for ODF info - DRPolicy creation

2024-07-24 06:55 UTC, SanjalKatiyar commented on packages/mco/constants/disaster-recovery.ts
> +  'odf-multicluster-managedcluster-controller';
@vbnrh plz make sure these constants are not changed on the MCO side by mistake.

2024-07-24 06:56 UTC, SanjalKatiyar commented on packages/mco/constants/disaster-recovery.ts
> +  'odf-multicluster-managedcluster-controller';
@vbnrh can u cross-verify these constants ?? also, plz make sure these are not changed/updated on the MCO side by mistake.

2024-07-24 07:09 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.tsx
> +  // Converting into name/namespace for unique identification in dropdown option
optional, need to update these comments for util function

2024-07-24 09:52 UTC, vbnrh commented
/lgtm

2024-07-24 09:55 UTC, merged