DR policy actions
red-hat-storage/odf-console pull request #154
Opened 2022-03-23 10:17 UTC by GowthamShanmugam

2022-03-23 10:18 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/159676793-f335f0d0-1fcd-44bd-ad1c-b428c8eaf16d.png)

2022-03-23 10:41 UTC, SanjalKatiyar commented on packages/mco/utils/index.ts
> +export * from './consts';
constants should be under `/mco/constants/` not under `/mco/utils/`...

2022-03-23 10:45 UTC, SanjalKatiyar commented on packages/mco/types/acm.ts
> +};
already present under `shared/types` we should either edit that or rename this one specific for ACM (something like `ACMSubscriptionKind`).
but I think we should edit `shared/types` one if this is an accepted change in Subscription CRD ??

2022-03-23 11:04 UTC, SanjalKatiyar commented on packages/mco/utils/disaster-recovery.ts
> +    application?.spec?.selector?.matchExpressions?.forEach((expr) => {
use `.every` instead of `.forEach`. What I understood is that we need to return `false` if any of the expression check results in `false`.
So, `.every` will break at the first `false` value it will encounter whereas `.forEach` will always run over the entire list.

2022-03-23 11:07 UTC, SanjalKatiyar commented on packages/mco/utils/disaster-recovery.ts
> +                valid = valid && (expr?.values?.includes(subscription?.metadata?.labels?.[expr?.key]));
nits: not anything too important. We can create a separate function for calculating
`expr?.values?.includes(subscription?.metadata?.labels?.[expr?.key])` and
`Object.keys(subscription?.metadata?.labels).includes(expr?.key)) && (!Array.isArray(expr?.values))` 
so that we don't have to write this expression twice.

2022-03-23 11:13 UTC, SanjalKatiyar commented on packages/mco/models/acm.ts
> +import { K8sModel } from '@openshift-console/dynamic-plugin-sdk-internal-kubevirt/lib/api/common-types';
`import { K8sModel } from '@openshift-console/dynamic-plugin-sdk/lib/api/common-types'`
don't import anything from kubevirt, from 4.11 console is not supporting it. Please fix it at other places as well (if any).

2022-03-23 11:17 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +  });
please add it outside of the FC. Also, why are we passing `t` if we are not using it.

2022-03-23 11:19 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/policy-actions.tsx
> +    [Actions.DELETE_DR_POLICY]: React.lazy(() => import('@odf/shared/modals/DeleteModal'))
can you please cross-check this once ?? 
I think modelLauncher hook is adding `DELETE` modal by default. We might not need to explicitly need to add it in this modalmap.

2022-03-23 11:20 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/policy-actions.tsx
> +    [Actions.DELETE_DR_POLICY]: React.lazy(() => import('@odf/shared/modals/DeleteModal'))
I am not sure about it, just requesting to cross-check once.

2022-03-23 11:27 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +type PlacementRuleDict = {
nits: if by `Dict` u mean `Dictionary` then we don't use this term in JS.

2022-03-23 11:29 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +import { ApplicationModel, PlacementRuleModel, SubscriptionModel, DRPlacementControlModel } from '../../../../models';
just like `SubscriptionKind` we also have `SubscriptionModel` in `shared/models` no need to add it under `mco/models`.

2022-03-23 11:54 UTC, GowthamShanmugam commented on packages/mco/utils/index.ts
> +export * from './consts';
ack

2022-03-23 12:09 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +import { ApplicationModel, PlacementRuleModel, SubscriptionModel, DRPlacementControlModel } from '../../../../models';
ack

2022-03-23 12:10 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +type PlacementRuleDict = {
i used name like python, will change it

2022-03-23 12:12 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/policy-actions.tsx
> +    [Actions.DELETE_DR_POLICY]: React.lazy(() => import('@odf/shared/modals/DeleteModal'))
Yes, it is already there, but I want to override this, I want to pass some extra dropdown properties to the delete option. So i am adding it as one extra option. But we need some way to hide the default. Let's takecare of that in separate PR.

2022-03-23 12:57 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const managedClusters: ManagedCluster[] = resource?.spec?.drClusterSet;;
we can move this under `useMemo` on L48.

2022-03-23 12:59 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +        managedClusters?.map((cluster) => cluster.name), [managedClusters]);
we can move L28 inside this `useMemo` and add `resource` to the dependency list instead.
`managedClusters` reference can change on every re-render even though reference of `resource` is not getting changed.

2022-03-23 14:28 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +
can we move this outside the FC ?? 
we have 4 `useEffect`, 1 `useMemo` and 1 `useCallback` within same component, looks too much to me !
can we try reducing number of `useEffect` or if possible break this component into even smaller components ??

2022-03-23 16:20 UTC, SanjalKatiyar commented on packages/mco/types/acm.ts
> +export type ApplicationKind = K8sResourceCommon & {
if this is not a custom resource but something native to K8s, then this should be in shared folder. Same is with the ApplicationModel.

2022-03-23 16:37 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +
I am using usek8sget, i think I dont need useEffect.  will check and remove this.

2022-03-23 16:49 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +  };
```
  const onSearch = (searchValue: string) => 
      setFilteredNames(Object.keys(applicationToPlacementRuleMap).filter(name => filterItems(applicationToPlacementRuleMap?.[name].applicationName, searchValue)));
```
`'text'.includes('') is true`

2022-03-24 14:35 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/159939978-9c7c46d5-7d1b-4aa6-bc1c-85271f50c46c.png)

![image](https://user-images.githubusercontent.com/15073590/159940060-5aaaf69e-9b75-410f-ac65-7ae84aa206fc.png)

2022-03-24 14:51 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +    application?.spec?.selector?.matchExpressions?.forEach((expr) => {
i tired ever, it is stopped after first iteration, and i dont find any issue with forloop

2022-03-24 14:55 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/policy-actions.tsx
> +    [Actions.DELETE_DR_POLICY]: React.lazy(() => import('@odf/shared/modals/DeleteModal'))
i will send this on separate PR

2022-03-24 14:59 UTC, GowthamShanmugam commented on packages/mco/types/acm.ts
> +export type ApplicationKind = K8sResourceCommon & {
it is a k8 resource, moving under k8 file

2022-03-24 15:02 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +  };
we need to refill filternames if search becomes empty

2022-03-24 15:02 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +
yeah, but if we move it outside we don't have to use `useCallback` and also since it is outside it's memory address will not change on every re-render on the FC component, hence already optimised not need to hook.

2022-03-24 15:09 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +import { ApplicationModel, PlacementRuleModel, SubscriptionModel, DRPlacementControlModel } from '../../../../models';
Sorry, I missed one thing earlier, if it something specific to ACM then no need to move to shared.
Earlier when I added this comment I got confused with the `Subscription` that we have for any operator, if it is something specific to ACM it can stay in `mco` package.

2022-03-28 11:13 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +                <TextInput placeholder={t("Application name")} name="appNameText" id="appNameText" type="search" aria-label={t("application name search")} onChange={onSearch}/>
We dont need a button here, i added this because it was the design, i will check with UX and  modify this

2022-03-28 19:11 UTC, GowthamShanmugam commented
@SanjalKatiyar @bipuladh Changes done

2022-03-30 02:03 UTC, bipuladh requested changes

2022-03-30 02:03 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      var result = [];
```suggestion
      let result = [];
```

2022-03-30 02:03 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +          result = result.concat(flattenTree(item.children));
```suggestion
          result.push(flattenTree(item.children));
```
Wouldn't this work?

2022-03-30 02:03 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    const filterItems = (item, checkedItem) => {
Move functions that are not using state values/props outside of the React component

2022-03-30 09:26 UTC, GowthamShanmugam commented on packages/shared/types/k8s.ts
> +export type ApplicationKind = K8sResourceCommon & {
it is part of openshift, it is default CR from k8

2022-03-30 09:26 UTC, GowthamShanmugam commented on packages/shared/types/k8s.ts
> +        selector?: Selector | null;
ack

2022-03-30 09:27 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +export const ApplicationToSubscriptionMatching = (subscription: ACMSubscriptionKind, application: ApplicationKind): boolean => {
ack

2022-03-30 09:29 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +    const isIn = (expr: MatchExpression, match: Boolean) =>
ack

2022-03-30 09:30 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +    const isExists = (expr: MatchExpression, match: Boolean) =>
ack

2022-03-30 09:30 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const [applications, applicationsLoaded, applicationsLoadError] = useK8sGet<ListKind<ApplicationKind>>(
user wont take much time while applying the policy, it is very short operation, i dont think watch is required here

2022-03-30 09:31 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                application?.spec?.componentKinds.some((componentKind) =>
ack

2022-03-30 09:34 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                    componentKind?.group === ACMSubscriptionModel?.apiGroup &&
no need to match version. since application is k8 specific, we are using these ACM subscription field to confirm this application handled by ACM or not.

2022-03-30 09:39 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            const subsFilter = (subscription: ACMSubscriptionKind) => (
ack

2022-03-30 09:44 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    }, [resource]);
ack

2022-03-30 09:45 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    const isChecked = dataItem => selectedNames.checkedItems.some(item => item.id === dataItem.id);
ack

2022-03-30 09:45 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      var result = [];
Ah! what i have done

2022-03-30 09:53 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    const filterItems = (item, checkedItem) => {
ack

2022-03-30 10:11 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +          result = result.concat(flattenTree(item.children));
it wont it is merging the arrays

2022-04-08 20:34 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-04-12 08:21 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +    application?.spec?.selector?.matchExpressions?.forEach((expr) => {
ack

2022-04-13 06:47 UTC, SanjalKatiyar approved these changes

2022-04-13 06:47 UTC, SanjalKatiyar commented
/lgtm

2022-04-13 08:37 UTC, afreen23 requested changes

2022-04-13 08:37 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Select the apps you would like to apply the policy on": "Select the apps you would like to apply the policy on",
```suggestion
  "Select the apps for applying the policy": "Select the apps you would like to apply the policy on",
```

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    const {applicationToPlacementRuleMapping, selectedNames, setSelectedNames} = props;
```suggestion
    const {applicationToPlacementRuleMapping, selectedNames, setSelectedNames} = props;
    
     const { t } = useTranslation('plugin__odf-console');
```

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +  const [ModalComponent, props, launchModal] = useModalLauncher(DRPolicyActions);
```suggestion
 const [ModalComponent, props, launchModal] = useModalLauncher(DRPolicyActions);
 
```

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                            {(error as any)?.message}
```suggestion
                            {error}
```

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            (error) => setError(error)
```suggestion
            (error) => setError(error?.message)
```

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +
```suggestion
```

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.scss
> +        margin-bottom: var(--pf-global--spacer--lg) !important;
important is scary.
There should be a different css class of the component itself you can modify. You can check for that in PF docs of the component. Or that means you are not using correct component.

2022-04-13 08:37 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +
```suggestion
   // Reset checked properties to be updated
      item.checkProps.checked = false;
      const hasCheck = areAllDescendantsChecked(item);
      const hasPartialCheck = areSomeDescendantsChecked(item);
     if (hasCheck) {
        item.checkProps.checked = true;
      } else if (hasPartialCheck) {
          item.checkProps.checked = null;
        }
   

```

2022-04-13 11:18 UTC, afreen23 requested changes

2022-04-13 11:18 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Create BlockPool": "Create BlockPool",
I dont see these externalized , you might nee dto run yarn i18n to update texts, looks like stale.

2022-04-13 11:18 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.scss
> +      min-height: 200px;
use rem or PF global css variables

2022-04-13 11:18 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    };
this is a helper function, can be outside the component. Also not using any state to keep here.

2022-04-13 11:18 UTC, afreen23 commented on packages/mco/constants/dr-policy.ts
> +  APPLY_DR_POLICY = 'Apply DRPolicy',
externalize ??

2022-04-13 11:18 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'drplacementcontrol',
```suggestion
```

2022-04-13 11:18 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'acmplacementrule',
```suggestion
```

2022-04-13 11:18 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'acmsubscription',
```suggestion
```

2022-04-13 11:18 UTC, afreen23 commented on packages/shared/models/common.ts
> +  id: 'acmapplication',
```suggestion
```

2022-04-14 07:27 UTC, afreen23 requested changes

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +          const plsRule = filteredApplicationToPlacementRuleMapping[appUniqueName].placements[placementUniqueName]?.placementRules;
```suggestion
          const placementName = filteredApplicationToPlacementRuleMapping[appUniqueName].placements[placementUniqueName];
          const { subscriptions, placementRules } = placementNames || {};
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +        let childerns: TreeViewDataItem[] = [];
```suggestion
        const childrens: TreeViewDataItem[] = [];
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            const IsPlacementRuleModel = (subscription: ACMSubscriptionKind) => (
```suggestion
            const isPlacementRuleModel = (subscription: ACMSubscriptionKind) => (
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    };
I think you should do  this inside useEffect as well

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            let appToPlsRuleMapping: ApplicationToPlacementRuleMapping = {};
```suggestion
            const appToPlsRuleMap: AppToPlacementRule = {};
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            pvcSelector: {
can be outside the react component.

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/types/types.ts
> +      Phase: string;
```suggestion
      phase: string;
```
??

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/utils/disaster-recovery.ts
> +            : !(Object.keys(subscription?.metadata?.labels).includes(expr?.key)) && (!Array.isArray(expr?.values));
define them as separate function

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const[applicationMapping, setApplicationMapping] = React.useState<ApplicationMapping>({});
```suggestion
    const[applicationMap, setApplicationMap] = React.useState<ApplicationMapping>({});
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const[subscriptionMapping, setSubscriptionMapping] = React.useState<SubcsriptionMapping>({});
```suggestion
    const[subscriptionMap, setSubscriptionMap] = React.useState<SubcsriptionMapping>({});
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const[placementRuleMapping, setPlacementRuleMapping] = React.useState<PlacementRuleMapping>({});
```suggestion
    const[placementRuleMap, setPlacementRuleMap] = React.useState<PlacementRuleMapping>({});
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const[applicationToPlacementRuleMapping, setApplicationToPlacementRuleMapping] = React.useState<ApplicationToPlacementRuleMapping>({});
```suggestion
    const[appToPlacementRuleMap, setAppToPlacementRuleMap] = React.useState<ApplicationToPlacementRuleMapping>({});
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            const subscDict: SubcsriptionMapping = subscriptions?.items.reduce((arr, subscription) => (IsPlacementRuleModel(subscription)? { ...arr, [subscription?.metadata?.namespace]: {...arr[subsc
```suggestion
            const subsDict: SubcsriptionMapping = subscriptions?.items.reduce((arr, subscription) => (IsPlacementRuleModel(subscription)? { ...arr, [subscription?.metadata?.namespace]: {...arr[subscription?.metadata?.namespace],  [subscription?.metadata?.name]: subscription}} : arr), {});
```

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    }, [managedClusterNames]);
This seems utility , can be outside react component.

2022-04-14 07:27 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                        const applicationUniqueName = `${appName}-${appNamespace}`;
```suggestion
                        const appUniqueName = `${appName}-${appNamespace}`;
```

2022-04-18 10:29 UTC, bipuladh requested changes

2022-04-18 10:29 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +export type AppToPlacementRule = {
move it to a types file if this needs to be exported.

2022-04-18 10:29 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +const badge = (subNames: string[], plsRule: string) => {
please make a component out of it

2022-04-18 10:29 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const [applications, applicationsLoaded, applicationsLoadError] = useK8sGet<ListKind<ApplicationKind>>(
we can never be so sure. users tend to keep tabs open a while.

2022-04-18 10:41 UTC, afreen23 requested changes

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +type TreeViewDataItemMapping = {
```suggestion
type TreeViewDataItemMap = {
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +  applicationToPlacementRuleMapping: AppToPlacementRule;
```suggestion
  applicationToPlacementRuleMap: AppToPlacementRule;
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +const flattenTree = tree => {
add types

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +const badge = (subNames: string[], plsRule: string) => {
```suggestion
const Badge: React.FC = (subNames: string[], plsRule: string) => {
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    const {applicationToPlacementRuleMapping, selectedNames, setSelectedNames} = props;
```suggestion
    const {applicationToPlacementRuleMap, selectedNames, setSelectedNames} = props;
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +        setFilteredApplicationToPlacementRuleMapping(Object.keys(applicationToPlacementRuleMapping)?.reduce((arr, appUniqueName) => (filterApplications(applicationToPlacementRuleMapping[appUniqueName
```suggestion
        setFilteredApplicationToPlacementRuleMap(Object.keys(applicationToPlacementRuleMapping)?.reduce((arr, appUniqueName) => (filterApplications(applicationToPlacementRuleMapping[appUniqueName]?.application, searchValue)? { ...arr, [appUniqueName]: applicationToPlacementRuleMapping[appUniqueName]} : arr), {}));
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            let appToPlsRuleMapping: AppToPlacementRule = {};
```suggestion
            const appToPlsRuleMap: AppToPlacementRule = {};
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                        title={t("DR protection will be applied for all the PVCs under the selected applications.")}
```suggestion
                        title={t("Disaster recovery will be applied for all the persistent volume claims (PVCs) under the selected applications.")}
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      setFilteredApplicationToPlacementRuleMapping(applicationToPlacementRuleMapping);
```suggestion
setFilteredApplicationToPlacementRuleMapping(applicationToPlacementRuleMapping);
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +  dataItem.children ? dataItem.children.some(child => areSomeDescendantsChecked(child, selectedNames)) : isChecked(dataItem, selectedNames);
define types

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +          name: filteredApplicationToPlacementRuleMapping?.[appUniqueName]?.application?.metadata?.name,
lets use shorter -"map" at all places
```suggestion
          name: filteredApplicationToPlacementRuleMap?.[appUniqueName]?.application?.metadata?.name,
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                        title={t("DR protection will be applied for all the PVCs under the selected applications.")}
Ref: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/term_glossary.adoc#persistent-volume-claim-pvc

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                        {t("Select the apps for applying the policy")}
```suggestion
                        {t("Select the applications for applying the  DRPolicy")}
```

2022-04-18 10:41 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            title={t('Apply policy')}
```suggestion
            title={t('Apply DRPolicy')}
```
or

2022-04-18 10:54 UTC, afreen23 requested changes

2022-04-18 10:54 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +export type AppToPlacementRule = {
agree

2022-04-18 10:54 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +};
Mapping -> Map

2022-04-18 10:54 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const [applications, applicationsLoaded, applicationsLoadError] = useK8sGet<ListKind<ApplicationKind>>(
Better to do watch for edge cases!

2022-04-18 10:54 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            setLoading(false)
this will not execute in case of succesful resolution -> modal will close.

2022-04-18 10:54 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                <div className="form-group">
why this class ?

2022-04-18 10:54 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                    <div className="form-group">
why this class ?

2022-04-18 14:15 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +export type AppToPlacementRule = {
ack

2022-04-18 14:52 UTC, GowthamShanmugam commented
https://github.com/red-hat-storage/odf-console/pull/154#discussion_r852030006

@bipuladh Regarding this commit, i really worried about the performance, if number of managed cluster is huge then number of application will be in very high. 

We need to watch application and subscription and placement rule, if anyone changes then it will trigger this treeview logic for all cluster's application.

It will impact the performance. I using watch very rarely on hub UI.

2022-04-18 15:27 UTC, GowthamShanmugam commented
https://github.com/red-hat-storage/odf-console/pull/154#discussion_r852038806
@afreen23 Just watching application is not enough, we need to watch subscription and placement rule also. I feel it might be toomuch load when we have high number of application in very high number of cluster.

2022-04-18 18:43 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +                    <div className="form-group">
Ah! its a mistake, I copied from the Blackpool page

2022-04-19 07:14 UTC, afreen23 requested changes

2022-04-19 07:14 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
```suggestion
  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the persistent volume claims(PVCs) under the selected Applications.",
```

2022-04-19 07:19 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
This is CRD name, as per capitalization we need to use like this

2022-04-19 07:22 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
Its a general reference.
https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#general-references

2022-04-19 07:23 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
Also Disaster recovery(DR) protection -> Disaster recovery(DR)  ? Protection is well understood by Disaster recovery(DR) ?
```suggestion
  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied to all the PersistentVolumeClaims(PVCs) under the selected Applications.",
```

2022-04-19 07:34 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
i discussed this with UX team and they feel like:

Disaster recovery is a process/practice and we don't necessarily apply a process to anything it is rather the protection that is enabled for the PVCs.

2022-04-19 07:35 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
also, i changed Application to application where ever it not mentioned (CRD) specifically

2022-04-19 07:40 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Disaster recovery(DR) protection will be applied for all the PersistentVolumeClaims(PVCs) under the selected Applications.": "Disaster recovery(DR) protection will be applied for all the Persisten
> Its a general reference. https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#general-references

Got it

2022-04-19 07:44 UTC, afreen23 approved these changes

2022-04-19 07:51 UTC, bipuladh requested changes

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +type badgeProps =  {
`BadgeProps`

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +import { AppToPlacementRule } from '../../../../types/types';
Please add a index file. And import it from `types`.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      (item.children = item.children
I don't think we should be modifying item.children directly. A pure function should not directly modify the arguments supplied to it. This could cause problems especially if `item` is passed from a React state.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +        <p key={subName}> {subName} </p>
Why the spaces around `{subName}`

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/types/types.ts
> +  [appUniqueKey in string]: {
Why use `in`?

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/types/types.ts
> +      [placementUniqueKey in string] : {
why use `in`?

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +          const subNames = subscriptions?.map((sub) => sub?.metadata?.name);
`const subNames = subscriptions?.map(getName))`
Also we could take advantage of loaded and loadError to remove the optional chaining.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +            name: (<Badge subNames={subNames} plsRule={placementRules?.metadata?.name}/>),
I feel like we should be adding key to this particular Element.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      const checkedItemTree = options
Since `options` which is a state variable is used I would prefer if we wrap this function into a useCallback.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +        .map(opt => Object.assign({}, opt))
Could we just `deepClone` and run filter. It would make this bit more expressive.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    React.useEffect(() => {
Could we store the React element and just filter them when needed rather than recreating them everytime? This could be a very slow operation for a fairly decent list of applications.

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +export default ApplyDRPolicyModal;
NewLine?

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const {resource} = extraProps;
Why not watch for resources from inside the modal?

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const copyResponse = useDeepCompareMemoize(response, true);
The right term would be `memoizedResponse`

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const submit = (event: React.FormEvent<EventTarget>) => {
Wrap it in a callback

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            width={'650px'}
Why the curly braces?

2022-04-19 07:51 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    const copyResponse = useDeepCompareMemoize(response, true);
`memoizedResponse`

2022-04-19 07:59 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const submit = (event: React.FormEvent<EventTarget>) => {
I dont think a callback is required here, submit no need to memorize anything, anyway we are closing the modal after successful submission.

2022-04-19 07:59 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const copyResponse = useDeepCompareMemoize(response, true);
ack

2022-04-19 08:03 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +    const {resource} = extraProps;
I dont get it, i am watching from FC where i am returning modal only

2022-04-19 08:03 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    const copyResponse = useDeepCompareMemoize(response, true);
ack

2022-04-19 08:03 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/apply-policy-modal.tsx
> +            width={'650px'}
removing it

2022-04-19 08:11 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    React.useEffect(() => {
We can't we dont know which part of the tree is affected, the tree is depending on the Application, subscription, and placement rules, and we can't find which part is changed exactly. The worst case of updating the tree is equal to recreating it.

2022-04-19 08:58 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +    React.useEffect(() => {
I optimized the search, Now it won't recreated every time.

2022-04-19 10:44 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      (item.children = item.children
We are not changing passed arg, instead, it will create a new one. Below code will help you to understand. Please execute and check.

`const filterItems = (item, checkedItem) => {
  if (item.id === checkedItem.id) {
    return true;
  }

  if (item.child) {
    console.log("came")
    return (
      (item.child = item.child
        .map(opt => Object.assign({}, opt))
        .filter(child => filterItems(child, checkedItem))).length > 0
    );
  }
};

const obj = [{
            "id": "a",
            "child": [{
                    "id": "a1",
                    "child": []
            }]
        },
        {
            "id": "b",
            "child": [{
                    "id": "b1",
                    "child": []
            }]
        },
]

const exp = {
            "id": "b1",
            "child": []
        }
const resu = obj
        .map(opt => Object.assign({}, opt))
        .filter(item => filterItems(item, exp));
resu[0].id = "123"

console.log(resu)
console.log(obj)`

2022-04-19 10:45 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +      (item.children = item.children
i tested this code, it is creating new object not modifying existing one

2022-04-19 10:51 UTC, GowthamShanmugam commented on packages/mco/types/types.ts
> +  [appUniqueKey in string]: {
ack, I should not use it unless it is an enum type.

2022-04-19 10:51 UTC, GowthamShanmugam commented on packages/mco/types/types.ts
> +      [placementUniqueKey in string] : {
ack, I should not use it unless it is an enum type.

2022-04-19 11:22 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-actions/apply-policy/application-selector.tsx
> +        .map(opt => Object.assign({}, opt))
as i explained this with example prog, we dont need to deepclone this.

2022-04-19 12:52 UTC, bipuladh commented
/lgtm 
/override ci/prow/odf-console-e2e-aws

2022-04-19 12:54 UTC, merged