DRPolicy Delete action
red-hat-storage/odf-console pull request #155
Opened 2022-03-24 19:14 UTC by GowthamShanmugam

2022-03-24 19:14 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/159993222-f8066b27-1a8a-4410-9b8e-f89fd0ceb488.png)

2022-03-28 11:10 UTC, GowthamShanmugam commented
@bipuladh please review

2022-03-28 11:15 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-03-29 10:20 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +  const kebabItems = defaultKebabItems(t);
If customkeys has the same key as default then custom then default key will be overridden by customkeys props and its modal.

2022-03-29 10:32 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +    [ModalKeys.DELETE]: {
Here i am overriding DELETE, but it will still use the default delete modal. If you want to override the default modal also for delete then pass your modal here: https://github.com/red-hat-storage/odf-console/pull/155/commits/6a1e8db428d172a92583b11fcbe921481879088d#diff-1b32ef98d898b5f4a22e51d9aa49e14d03849959c2d1836f34042b0044acef49R202

With this change, if you want to only override the default action dropdown and its props then it is possible. if you want to override default modal as well, that is also possible.

2022-03-30 02:06 UTC, bipuladh requested changes

2022-03-30 02:06 UTC, bipuladh commented on packages/shared/kebab/kebab.tsx
> +  const kebabItems = defaultKebabItems(t);
Could we use the same modal keys and use Object.assign instead?

2022-04-08 20:34 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-04-12 13:52 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-actions/policy-actions.tsx
> +};
shouldn't this be under constants ??

2022-04-13 06:47 UTC, SanjalKatiyar approved these changes

2022-04-13 06:48 UTC, SanjalKatiyar commented
/lgtm

2022-04-13 08:51 UTC, afreen23 requested changes

2022-04-13 08:51 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Cannot delete while connected to an Application": "Cannot delete while connected to an Application",
```suggestion
  "Cannot delete while connected to an application": "Cannot delete while connected to an Application",
```

2022-04-13 08:51 UTC, afreen23 commented on packages/shared/kebab/kebab.tsx
> +    ).reduce((obj, [k, v]) => (
in case of  {}
```suggestion
    ).?reduce((obj, [k, v]) => (
```

2022-04-13 09:38 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Cannot delete while connected to an Application": "Cannot delete while connected to an Application",
Application is a CR in OCP, its ok to start as capital

2022-04-13 11:06 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Cannot delete while connected to an Application": "Cannot delete while connected to an Application",
Alright then if its a CR.

2022-04-13 11:10 UTC, afreen23 requested changes

2022-04-13 11:10 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'drplacementcontrol',
```suggestion
```
No need to maintain id, they are no  longer used in console

2022-04-13 11:10 UTC, afreen23 commented on packages/mco/constants/dr-policy.ts
> +  DELETE_DR_POLICY = 'Delete DRPolicy',
externalize

2022-04-13 11:10 UTC, afreen23 commented on packages/mco/types/types.ts
> +      Phase: string;
is it `phase` or `Phase` only ??

2022-04-13 11:10 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Create BlockPool": "Create BlockPool",
I dont see these strings externalized in this PR ? You might need to run yarn i18n to update these.

2022-04-13 12:38 UTC, GowthamShanmugam commented on packages/mco/models/models.ts
> +    id: 'drplacementcontrol',
Ah! looks like all PR got affected by these change

2022-04-13 13:59 UTC, afreen23 approved these changes
/lgtm

2022-04-18 11:02 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +    const customResolved = customKebabItems ? customKebabItems(t): {};
UI is breaking when no customkebab item is passed

2022-04-18 11:09 UTC, bipuladh commented on packages/shared/kebab/kebab.tsx
> +    const customResolved = customKebabItems ? customKebabItems(t): {};
ack

2022-04-18 14:29 UTC, afreen23 commented
/lgtm

2022-04-18 14:35 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-19 13:37 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-19 14:55 UTC, afreen23 commented
/lgtm

2022-04-19 16:11 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-19 16:13 UTC, merged