ACM overview dashboard
red-hat-storage/odf-console pull request #156
Opened 2022-03-29 13:54 UTC by SanjalKatiyar

![Screenshot from 2022-03-29 18-34-47](https://user-images.githubusercontent.com/39404641/160627206-9bb6b296-af8a-40d8-8bcb-cb41dde690f5.png)
![Screenshot from 2022-03-29 18-34-42](https://user-images.githubusercontent.com/39404641/160627198-1df7b5fa-09c9-4384-ada9-facb242f9ef1.png)

2022-03-31 14:04 UTC, SanjalKatiyar commented on packages/mco/constants/dr-policy.ts
> +export const ODF_OPERATOR = 'odf-operator';
Added it in this file for now. I saw one other DR related PR which is adding `index.ts` for `constants` directory. Whichever PR gets merged later can handle that while resolving merge conflicts.

2022-04-05 14:25 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> + */
yeah system health metrics `0` means healthy...
whereas in csv_succeded `1` is returned for healthy CSVs...

2022-04-05 14:27 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +    useURLPoll<PrometheusResponse>(`${ACM_ENDPOINT}=${STATUS_QUERIES[StorageDashboard.CSV_STATUS]}`);
already handled it in this PR: https://github.com/red-hat-storage/odf-console/pull/163/files
we can merge this for now, once #163 is merged we can update it or vice versa.

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +  const [normalSysCount, setNormalSysCount] = React.useState(0);
```suggestion
  const [sysCount, setSysCount] = React.useState({});
```

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +    setNormalSysCount(systemHealthCount.normal);
```suggestion
   setSysCount(getSystemHealthCount(systemHealthMap));
```

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +                <SystemHealthCount value={t('Critical')} health={HealthState.ERROR} count={errorSysCount}/>
```suggestion
                <SystemHealthCount value={t('Critical')} health={HealthState.ERROR} count={sysCount?.critical}/>
```

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +  const [runningCount, setRunningCount] = React.useState(0);
you can do the same here: React.useState({})

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +  return negation ? -sortVal : sortVal;
-sortVal?

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +        link={'/multicloud/clusters'}
we need to use ocp cluster PublicURL//odf/cluster, you can fetch this from ManagedCluster CR.

Read all **ManagedCluster** CRs, creating a {managed_cluster_name : obj}  mapping and use cluster name every time to fetch the obj and public url which is present inside the managed cluster object.

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +
(`${ACM_ENDPOINT}=${CAPACITY_QUERIES[StorageDashboard.USED_CAPACITY_FILE_BLOCK]}`);
this line is used is lof placed with diff query, lets move this utils to make it simple

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +      totalCapacity?.data?.result?.find((totalMetric) => {
for each usedCapacity you are looping all total capacity. its better loop usedCapacity and totalCapacity only once and create mapping using a key  storage_system+ cluster

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/constants/dr-policy.ts
> +export const ODF_OPERATOR = 'odf-operator';
ack

2022-04-05 14:51 UTC, GowthamShanmugam commented on packages/mco/models/models.ts
> +export const ODFStorageSystem: K8sModel = {
ODFStorageSystem and OCSStorageClusterModel will be already there on odf/core, if you feel not adding code then move these two to odf/share

2022-04-05 14:52 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +    useURLPoll<PrometheusResponse>(`${ACM_ENDPOINT}=${STATUS_QUERIES[StorageDashboard.CSV_STATUS]}`);
cool

2022-04-08 08:52 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/queries.ts
> +      '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy) group_right(storage_system) odf_system_raw_capacit
okay... good point I just missed noobaa standalone part...
on our current main overview dashboard (single OCP) we have two different cards one `System Capacity` and other `External Object Provider Used Capacity`. Second one was for noobaa standalone that is why I missed that.

I have one doubt though...
for normal internal mode storagesystem (when noobaa is not standalone)... in that case we are using `USED_CAPACITY_FILE_BLOCK & TOTAL_CAP_FILE_BLOCK` so don't we want to show object (noobaa) status in that case ??

2022-04-10 17:37 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +        link={'/multicloud/clusters'}
ack...

2022-04-10 17:38 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +const ACM_ENDPOINT = '/acm-thanos-querier/api/v1/query?query';
it is a ToDo on me... will do once https://github.com/red-hat-storage/odf-console/pull/163/files is merged...

2022-04-10 17:38 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +  const [runningCount, setRunningCount] = React.useState(0);
ack...

2022-04-10 17:39 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +  return negation ? -sortVal : sortVal;
I copied it from here: https://github.com/red-hat-storage/odf-console/blob/ef8e6837f3b4375dbb2875b22c8a6c7725ec86e1/packages/odf/components/odf-dashboard/performance-card/performance-card.tsx#L85

2022-04-10 17:40 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +      totalCapacity?.data?.result?.find((totalMetric) => {
ack...

2022-04-10 17:41 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/queries.ts
> +    [StorageDashboard.CSV_STATUS]: 'csv_succeeded{exported_namespace="openshift-storage"}',
ack... I will update the Jira and will let you know...

2022-04-11 14:29 UTC, bipuladh commented on packages/mco/components/mco-dashboard/queries.ts
> +      '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy) group_right(storage_system) odf_system_raw_capacit
> Doubt: is odf_system_raw_capacity_total_bytes and odf_system_raw_capacity_used_bytes is only for and block? what about nooba standalone case? are ignoring nooba standalone storage system from this dashboard?

In case of MCG Standalone we would not get any values for Total but Used would be provided. So we would just show the consumption. I think we can take the exact logic as used in the ODF Dashboard.

2022-04-11 14:29 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/status-card.scss
> +    margin-top: calc(-1 * var(--pf-global--spacer--md)) !important;
Can't we decrease the margin/padding of the element above it than we pulling this element up?

2022-04-11 17:19 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.scss
> +    margin-top: calc(-1 * var(--pf-global--spacer--md)) !important;
isn't it same decreasing padding/margin of anyone of above or below element ??
both will always render, above element is not conditional.

2022-04-12 09:08 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +        acc[cluster?.metadata?.name] = getClusterURL(cluster?.spec?.managedClusterClientConfigs?.[0]?.url);
you can fetch console url from the status:
https://wtools.io/paste-code/bBdd

2022-04-12 10:06 UTC, GowthamShanmugam approved these changes

2022-04-12 20:59 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/queries.ts
> +      '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy) group_right(storage_system) odf_system_raw_capacit
```suggestion
    [StorageDashboard.TOTAL_CAP_FILE_BLOCK]:
      '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy, cluster) group_right(storage_system) odf_system_raw_capacity_total_bytes',
    [StorageDashboard.USED_CAPACITY_FILE_BLOCK]:
      '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy, cluster) group_right(storage_system) odf_system_raw_capacity_used_bytes',
```

2022-04-12 20:59 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/queries.ts
> +    [StorageDashboard.SYSTEM_HEALTH]: '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy) group_right(storag
```suggestion
    [StorageDashboard.SYSTEM_HEALTH]: '(label_replace(odf_system_map{target_namespace="openshift-storage"} , "managedBy", "$1", "target_name", "(.*)"))  * on (namespace, managedBy, cluster) group_right(storage_system, target_kind) odf_system_health_status',
```

2022-04-13 07:26 UTC, GowthamShanmugam approved these changes

2022-04-13 08:59 UTC, afreen23 requested changes

2022-04-13 08:59 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Openshift Data Foundation": "Openshift Data Foundation",
Why this name again ? It would say Data foundation.
Not blocking the PR, you may check with UXD later

2022-04-13 08:59 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Storage System Status": "Storage System Status",
```suggestion
  "Storage System status": "Storage System Status",
```

2022-04-13 08:59 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +          <StatusPopupSection firstColumn={t('Operator Status')}>
```suggestion
          <StatusPopupSection firstColumn={t('Operator status')}>
```

2022-04-13 08:59 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +        <Flex className="odf-status-popup__text--bold">{t('OpenShift Data Foundation Status')}</Flex>
```suggestion
        <Flex className="odf-status-popup__text--bold">{t('OpenShift Data Foundation status')}</Flex>
```

2022-04-13 08:59 UTC, afreen23 commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.scss
> +  width: 300px;
use rem.

2022-04-13 08:59 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Storage System Capacity": "Storage System Capacity",
```suggestion
  "Storage System capacity": "Storage System Capacity",
```

2022-04-13 08:59 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Cluster Name": "Cluster Name",
```suggestion
  "Cluster Name": "Cluster name",
```

2022-04-13 08:59 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "The OpenShift Data Foundation operator is the primary operator of OpenShift Data Foundation": "The OpenShift Data Foundation operator is the primary operator of OpenShift Data Foundation",
same here, please check the usage of OpenShift.

2022-04-13 09:12 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Openshift Data Foundation": "Openshift Data Foundation",
ack... I can check with UX later... u r right I just checked and main ODF overview dashboard also do not mention "Openshift" term anywhere anymore...
cc @GowthamShanmugam

2022-04-13 09:26 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.scss
> +  width: 300px;
rem is breaking the entire dashboard for me... I have tested px will multiple screen sizes and it is working correctly for all the different screen sizes...

2022-04-13 11:31 UTC, afreen23 requested changes

2022-04-13 11:31 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/status-card.scss
> +    margin-top: calc(-1 * var(--pf-global--spacer--md)) !important;
can we avoid using important here ?

2022-04-13 11:31 UTC, afreen23 commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.scss
> +  width: 300px;
try adjusting rem sizes. why would it break ?

2022-04-13 12:41 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.scss
> +  width: 300px;
nevermind... I meant that px was working for different screen sizes but I have changed it to rem anyways...
updated the PR...

2022-04-14 10:49 UTC, afreen23 requested changes

2022-04-14 10:49 UTC, afreen23 commented on packages/mco/components/mco-dashboard/dashboard.tsx
> +};
```suggestion
export const MCODashboard: React.FC = () => (
      <div className="co-dashboard-body">
        <UpperSection />
      </div>
  );
```

2022-04-14 10:49 UTC, afreen23 commented on packages/mco/components/mco-dashboard/queries.ts
> +    TOTAL_CAP_FILE_BLOCK = 'TOTAL_CAP_FB',
```suggestion
    USED_CAPACITY_FILE_BLOCK = 'USED_CAPACITY_FILE_BLOCK,
    TOTAL_CAPACITY_FILE_BLOCK = 'TOTAL_CAPACITY_FILE_BLOCK ',
```

2022-04-14 10:49 UTC, afreen23 commented on packages/mco/components/mco-dashboard/queries.ts
> +    [StorageDashboard.HEALTH]: 'odf_system_health_status',
import from common odf dashboard queries, its the same queries.
Lets maintain them at a single place

2022-04-14 10:49 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +  healthData.reduce((acc, item) => acc < item?.rawHealthData ? item?.rawHealthData : acc, '0');
define types for args

2022-04-14 10:55 UTC, bipuladh requested changes

2022-04-14 10:55 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +        <Flex className="odf-status-popup__text--bold">{t('Storage System status')}</Flex>
Can't we use Title component here?

2022-04-14 10:55 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +    return (
```suggestion
}) => (
```

2022-04-14 10:55 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +        <Flex className="odf-status-popup__text--bold">{t('OpenShift Data Foundation status')}</Flex>
Title maybe?

2022-04-14 10:55 UTC, bipuladh commented on packages/mco/models/models.ts
>      id: 'drpolicy',
Please export this file from a `index` file.

2022-04-14 10:55 UTC, bipuladh commented on packages/mco/types/types.ts
>      phase: string;
Please export from a `index` file.

2022-04-14 11:14 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/queries.ts
> +    [StorageDashboard.HEALTH]: 'odf_system_health_status',
only metric names are same (odf_system_raw_capacity_total_bytes, odf_system_raw_capacity_used_bytes & odf_system_health_status)... queries are slightly different...
also `mco` package do not have `odf` as dependency, unless we move everything under `shared`, but still queries are little different so I guess it should be fine that each package having there own queries files ?? wdyt ??

2022-04-18 10:34 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +  healthData.reduce((acc, item) => acc < item?.rawHealthData ? item?.rawHealthData : acc, '0');
since we have already defined it on L28 `healthData: SystemHealthMap[]` typescript will know that arg of `reduce` is of `SystemHealthMap` type...

2022-04-18 11:08 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +  healthData.reduce((acc, item) => acc < item?.rawHealthData ? item?.rawHealthData : acc, '0');
intellisense is not supported on github yet !

2022-04-18 11:09 UTC, afreen23 commented on packages/mco/components/mco-dashboard/queries.ts
> +    [StorageDashboard.HEALTH]: 'odf_system_health_status',
Yes the ask was to move to shared if there are same metrics.

2022-04-18 11:15 UTC, afreen23 requested changes

2022-04-18 11:15 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Openshift Data Foundation": "Openshift Data Foundation",
@SanjalKatiyar if main ODF dashboard is not mentioning, then we can remove this in this PR.

2022-04-18 11:15 UTC, afreen23 commented on packages/mco/components/mco-dashboard/queries.ts
> +    [StorageDashboard.HEALTH]: 'odf_system_health_status',
Yes the ask was to move to shared if there are same metrics.

2022-04-18 11:15 UTC, afreen23 commented on packages/mco/components/mco-dashboard/system-capacity-card/capacity-card.tsx
> +    setUnfilteredData(data);
add types

2022-04-18 11:18 UTC, afreen23 requested changes

2022-04-18 11:18 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +  healthData.reduce((acc, item) => acc < item?.rawHealthData ? item?.rawHealthData : acc, '0');
intellisense is not supported on github yet !
Can you add the types for such code editors ?

2022-04-18 12:59 UTC, SanjalKatiyar commented
![Screenshot from 2022-04-18 18-29-03](https://user-images.githubusercontent.com/39404641/163811850-c1e2cc4f-7f20-4f96-9d71-614fe82d5760.png)

2022-04-18 14:40 UTC, afreen23 requested changes

2022-04-18 14:40 UTC, afreen23 commented on packages/shared/models/storage.ts
> +    id: 'cephcluster',
```suggestion
```
ids are not used anymore in console

2022-04-18 14:40 UTC, afreen23 commented on packages/shared/models/storage.ts
> +    id: 'storagesystem',
```suggestion
```

2022-04-18 14:40 UTC, afreen23 commented on packages/shared/models/storage.ts
> +    id: 'storagesystem',
no need to add ids. not used anymore

2022-04-18 14:40 UTC, afreen23 commented on packages/shared/constants/common.ts
> +export const SYSTEM_HEALTH_METRIC = 'odf_system_health_status';
I thought we would maintain as `queries/dashboard.ts` in shared folder.

2022-04-18 14:40 UTC, afreen23 commented on packages/odf/components/utils/common.ts
> +import { IBMFlashSystemModel } from '../../models';
is it not breaking anything ? was it redundant ?

2022-04-18 14:40 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +        <Flex>{t('The Data Foundation operator is the primary operator of OpenShift Data Foundation')}</Flex>
```suggestion
        <Flex>{t('The Data Foundation operator is the primary operator of  Data Foundation')}</Flex>
```

2022-04-18 14:46 UTC, afreen23 requested changes

2022-04-18 14:46 UTC, afreen23 commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +        <Flex>{t('The Data Foundation operator is the primary operator of OpenShift Data Foundation')}</Flex>
Though I think the text can be improved.

2022-04-18 19:15 UTC, SanjalKatiyar commented on packages/odf/components/utils/common.ts
> +import { IBMFlashSystemModel } from '../../models';
imported from different path now...

2022-04-18 19:17 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +        <Flex>{t('The Data Foundation operator is the primary operator of OpenShift Data Foundation')}</Flex>
me as well... it sounded really weird that is why I intentionally kept second instance as "OpenShift Data Foundation" instead of  "Data Foundation"... but will not changing it to "Data Foundation" only... still it seems this entire text is imcomplete/improper IMO as well.

2022-04-19 07:37 UTC, afreen23 requested changes

2022-04-19 07:37 UTC, afreen23 commented on packages/shared/queries/dashboard.ts
> +    CSV_STATUS = 'CSV_STATUS',
This is only for mco.
By defining the whole object here, will restrict now to add individual metrics. We can just keep metrics.

2022-04-19 07:56 UTC, afreen23 approved these changes
Lets check the Data foundation operator text with UXD and make any adjustments . Not blocking the PR.

2022-04-19 07:57 UTC, afreen23 commented
/lgtm cancel
cc @bipuladh @GowthamShanmugam

2022-04-19 09:16 UTC, GowthamShanmugam approved these changes

2022-04-19 09:38 UTC, merged