Add initial setup for AWS S3 SDK
red-hat-storage/odf-console pull request #1569
Opened 2024-09-10 10:10 UTC by SanjalKatiyar

https://issues.redhat.com/browse/RHSTOR-6201

2024-09-10 10:11 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +          endpoint: `http://${routeData.spec.host}`,
have a separate story for this: https://issues.redhat.com/browse/RHSTOR-6222

2024-09-10 10:12 UTC, SanjalKatiyar commented on packages/s3-browser/hooks/bucket-commands.tsx
> +};
adding these commands as a new hook so that we don't have to manually pass `s3Client` everytime...

2024-09-10 10:50 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
Just a suggestion:
This looks like a library, but importing components from odf-core and odf-core will import for the s3 CRUD operations feels like a cycle dependency. 

In case we need to move this with the client console, then it will add 3rd dependency.  

What about implementing this s3 browser as a pure library like shared? so it can be re-used between ODF and client easily?

2024-09-10 10:52 UTC, alfonsomthd commented on packages/s3-browser/hooks/bucket-commands.tsx
> +    (input) => s3Client.send(new ListBucketsCommand(input)),
@SanjalKatiyar We should add [error handling](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/) here.

2024-09-10 11:00 UTC, SanjalKatiyar commented on packages/s3-browser/hooks/bucket-commands.tsx
> +    (input) => s3Client.send(new ListBucketsCommand(input)),
that's the job of the consumer of this callback (entity who will call this hook) IMHO... consumer can set local state on error/success or maybe decide to perform any other use case specific action based on API response... hence callback returns a promise...

ex:
```
const listBuckets  = useListBuckets();
listBuckets(input).then((res) => {
    // do something here
}).catch((err) => {
    // do something here
});
```

2024-09-10 11:05 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
It should be re-used between ODF and Client, I agree. But, I did not get the cyclic dependency part ??

Client itself depends on odf/core and odf/ocs: https://github.com/red-hat-storage/odf-console/blob/master/packages/client/package.json#L6-L7

2024-09-10 11:39 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +  const { isODFNsLoaded, odfNsLoadError } = useODFNamespaceSelector();
isODFNsLoaded and odfNsLoadError also can be a properties to avoid odf-core dependency

2024-09-10 11:39 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +    }));
Same here, either these can be a parameter or by moving useSafeK8sWatchResource to shared we can avoid odf-core dependency.

2024-09-10 11:39 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +  const { isODFNsLoaded, odfNsLoadError } = useODFNamespaceSelector();
again these are all optional comments,  consider this only if we are ready to make this as a library.

2024-09-10 11:39 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +            secretAccessKey: atob(secretData.data?.['AWS_SECRET_ACCESS_KEY']),
these two keys can be a local constants

2024-09-10 11:39 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +        return {} as S3Client;
any todo needed here for handling exceptions?

2024-09-10 11:45 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
I am not sure why we added core to the client, I don't think it is a good design. Then there is no point in keeping a shared library. 

We import some components from odf-core into s3-browser. To display the s3 browser-related components, we invoke the context and command hooks into odf-core. But this s3 and client are out of the odf-core folder. These imports look very weird.

2024-09-10 11:54 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
Reason why there are imports from odf/core because of redux and namespace hooks (these are shared by both odf and client), we can move redux to `shared` but that's illogical as well (ODF/Client specific namespace hooks and redux has nothing to do with the common shared).
Also, most of UI pieces in client is exactly same as ODF (like OB/OBC/NS/BS/BC and few dashboard cards), this imported from ODF directly.

`To display the s3 browser-related components, we invoke the context and command hooks into odf-core` >> I was not planning to import the context back in `odf/core`. If that will be the case we can move this folder inside `core` package directly, I agree.
All object browser related code will be inside this new package, we are not importing anything to odf/core.

2024-09-10 11:57 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
but let me know, if needed I can move `s3-browser` right away under core, instead of a new separate package...
cc @GowthamShanmugam @bipuladh

2024-09-10 12:00 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +  loading?: boolean;
nope, it should not be a mandatory field... it's intentionally optional...

2024-09-10 12:02 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +        return {} as S3Client;
I don't think so...

2024-09-10 12:02 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +        return {} as S3Client;
we could probably, yeah !!

2024-09-10 12:03 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +    }));
`useSafeK8sWatchResource` is ODF specific hook, should not be a part of common `shared`...

2024-09-10 12:10 UTC, GowthamShanmugam commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
ya, i am confused, The Client has a separate console-extension.json, so it adds of-core as a dependency and expenses its own client-related components(Still I have a concern about adding odf-core as as dependency).  

But here, if it is not a library or package, how are we going to expose the s3-browser components? Is it like adding odf-core as a dependency and also updating the console-extension.json of odf-core to expose the s3-browser components?

2024-09-10 12:18 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +import { SecretKind, K8sResourceKind } from '@odf/shared/types';
`console-extension.json` is not part of `core` package, nor it has any package.json of it's own... to me it's totally fine to import from `odf/s3` directly in ODF `console-plugin.json` file and same when we add it for Client (import in it's console-plugin.json file).

But yeah, if that's a concern I can move `s3-browser` under odf/core directly.

2024-09-10 13:36 UTC, alfonsomthd commented on packages/s3-browser/hooks/bucket-commands.tsx
> +    (input) => s3Client.send(new ListBucketsCommand(input)),
If we want this hook to be only a thin wrapper then it's OK, but I was thinking more about handling generic errors like `InvalidSignatureException` or `ResourceNotFoundException` in every place. We'll probably have to add the same checks in almost every call (as certain errors will be meaningful).
If we see the need in the future, we could handle some cases automatically so we don't have to add repetitive code checks everywhere.

2024-09-10 13:38 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +  test?: string;
done

2024-09-10 13:38 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +        return {} as S3Client;
done

2024-09-10 14:16 UTC, SanjalKatiyar commented on packages/s3-browser/hooks/bucket-commands.tsx
> +    (input) => s3Client.send(new ListBucketsCommand(input)),
is this what u r suggesting ??

```
  return React.useCallback(
    (input, onSuccess, onError, onInvalidSignatureError, onResourceNotFoundError ...) => s3Client.send(new ListBucketsCommand(input)).then((res) => {
        onSuccess();
    }).catch((err) => {
        onError();
        if (e instanceof InvalidSignatureException) {
            onInvalidSignatureError?.();
        } else if (e instanceof ResourceNotFoundException) {
            onResourceNotFoundError?.();
        } else if (e instanceof FooServiceException) {
            // Handle all other server-side exceptions from Foo service
        } 
        .
        .
        .
        // similarly if/else for all type of exceptions that SDK supports 
    }),
    [s3Client]
  );
```

2024-09-10 14:19 UTC, SanjalKatiyar commented on packages/s3-browser/hooks/bucket-commands.tsx
> +    (input) => s3Client.send(new ListBucketsCommand(input)),
If no, then can u plz add the snippet ??

If yes, then:
1. We will have to handle each type of exception as we never know what type the consumer will be interested in.
2. We will have to pass too many arguments.
3. I really doubt that handling particular type of exception will be a common case. Might be at few places, but not too many IMO.
4. How we will use `Promise.all`, if we don't return promise ? (this is much more common case).

2024-09-10 14:58 UTC, alfonsomthd commented on packages/s3-browser/hooks/bucket-commands.tsx
> +    (input) => s3Client.send(new ListBucketsCommand(input)),
No, I meant cases like handling a `ResourceNotFoundException` by returning an empty list/object (or null or what we agree upon) instead of having to check on every `catch` if the error is a `ResourceNotFoundException`.
Basically saving boilerplate code.

I'm OK with the current implementation if we interpret my suggestion as a premature optimization.

2024-09-12 07:23 UTC, bipuladh requested changes

2024-09-12 07:23 UTC, bipuladh commented on packages/s3-browser/hooks/object-commands.tsx
> +import * as React from 'react';
Rename the file to `ts`

2024-09-12 07:23 UTC, bipuladh commented on packages/s3-browser/client-context.tsx
> +              endpoint: `http://${routeData.spec.host}`,
Why does this need to be an external endpoint? Can't we bridge it and use the internal noobaa service?

2024-09-12 07:23 UTC, bipuladh commented on packages/s3-browser/hooks/bucket-commands.tsx
> +export const useListBuckets: UseListBuckets = () => {
I would find a class with methods that we need for use cases much more useful than creating these many hooks.

2024-09-12 07:23 UTC, bipuladh commented on packages/s3-browser/client-context.tsx
> +export const NoobaaS3ClientProvider: React.FC<NoobaaS3ClientProviderType> = ({
Why do we need a provider? I think a provider here might just be a overkill.

2024-09-12 07:23 UTC, bipuladh commented on packages/s3-browser/client-context.tsx
> +    useSafeK8sWatchResource<K8sResourceKind>((ns) => ({
I don't think we need to watch a get would suffice.

2024-09-12 07:23 UTC, bipuladh commented
I don't think we should create a seperate package for this. Most of it can reside inside of shared and core.

2024-09-13 05:54 UTC, SanjalKatiyar commented on packages/odf/components/s3-browser/noobaa-context.tsx
> +  );
will do it as part of: https://github.com/red-hat-storage/odf-console/pull/1569#discussion_r1751670603

2024-09-13 05:57 UTC, SanjalKatiyar commented on packages/s3-browser/client-context.tsx
> +              endpoint: `http://${routeData.spec.host}`,
https://github.com/red-hat-storage/odf-console/pull/1569#discussion_r1758224023

2024-09-17 04:23 UTC, bipuladh commented
/lgtm

2024-09-17 04:25 UTC, merged