WIP: added the dr-policy list data
red-hat-storage/odf-console pull request #157
Opened 2022-03-29 16:01 UTC by RishabhKodes

2022-03-30 02:07 UTC, bipuladh requested changes

2022-03-30 02:07 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +        {obj?.status?.conditions[0].type}
```suggestion
        {obj?.status?.conditions[0]?.type}
```

2022-03-30 02:07 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +        {obj?.spec?.drClusterSet?.map(cluster =>  <p key={cluster?.name}> {cluster?.name} </p>)}
Do it in a variable outside of the return function.

2022-04-21 12:37 UTC, RishabhKodes commented
Obsolete pr. Closing

2022-04-21 12:37 UTC, closed without merging