Application status on DRPolicy list page
red-hat-storage/odf-console pull request #158
Opened 2022-03-29 22:27 UTC by GowthamShanmugam

2022-03-29 22:28 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/160717231-671bb4ce-a9ed-4875-afe9-62737cdb629c.png)


![image](https://user-images.githubusercontent.com/15073590/160717302-d1f17619-2ec9-4a52-9f6d-5b1c4696ba09.png)

2022-04-08 20:33 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-04-12 14:02 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Connected Applications": "Connected Applications",
```suggestion
  "Connected Applications": "Connected applications",
```
??

2022-04-12 14:04 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +
```suggestion
```

2022-04-12 14:05 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    application?.spec?.componentKinds.some((componentKind) =>
```suggestion
    application?.spec?.componentKinds?.some((componentKind) => 
```
most probably it will work without adding it as well, but just to be sure in case ` application?.spec?.componentKinds` is `undefined`.

2022-04-12 14:06 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +};
```suggestion
const filterItems = (name: string, searchValue: string) => name.toLowerCase().includes(searchValue.toLowerCase())
```

2022-04-12 14:10 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +            const appMapping: ApplicationMapping = applications?.items.reduce((arr, application) => appFilter(application) ? { ...arr, [application?.metadata?.namespace]: {...arr[application?.metadat
```suggestion
            const appMapping: ApplicationMapping = applications?.items?.reduce((arr, application) => appFilter(application) ? { ...arr, [application?.metadata?.namespace]: {...arr[application?.metadata?.namespace],  [application?.metadata?.name]: application}} : arr, {});
```

2022-04-12 14:10 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +            const subsMapping: SubcsriptionMapping = subscriptions?.items.reduce((arr, subscription) => (subsFilter(subscription)? { ...arr, [subscription?.metadata?.namespace]: {...arr[subscription?
```suggestion
            const subsMapping: SubcsriptionMapping = subscriptions?.items?.reduce((arr, subscription) => (subsFilter(subscription)? { ...arr, [subscription?.metadata?.namespace]: {...arr[subscription?.metadata?.namespace],  [subscription?.metadata?.name]: subscription}} : arr), {});
```

2022-04-12 14:12 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +            };
```suggestion
            if(valid && !appNames.includes(appName)) {
                    appNames.push(appName);
            };
```
or,

```suggestion
            valid && !appNames.includes(appName) && appNames.push(appName);
```

2022-04-12 14:21 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Connected Applications": "Connected Applications",
Application is CR only, we can use captial letter

2022-04-12 14:23 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    }, [drPlacementControls]);
no need for this useCallback... move this fucntion outside the FC...
the useEffect which is calling `subsFilter` already has `drPlacementControls` as a dependency so u can pass that when u call `subsFilter`.

2022-04-12 14:25 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Connected Applications": "Connected Applications",
other places it is in small case... here it is in capital...

2022-04-12 14:44 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Connected Applications": "Connected Applications",
changed in other places also

2022-04-12 15:25 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Mirroring Status": "Mirroring Status",
These are from blockpool list page, looks like it was missed

2022-04-13 07:06 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    }, [applicationMapping, subscriptionMapping]);
one doubt:
u are passing `applicationMapping` in the dependency array and then changing its value in the same useEffect in this function `setApplicationNames`... so isn't it creating a infinite loop for you ? 
because u are updating `applicationMapping` and since it got updated it will run the useEffect again (because it is part of dependency array) and one useEffect will run it will set the value once again in `setApplicationNames` function and so on the process will continue again and again ??
can you open browser's inspect element console and check it it happening or not ?? if it happening inspect tool will notify you about the same...

2022-04-13 07:09 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +          {`${applicationNames.length} Applications`}
```suggestion
          {t('{{length}} Applications', {applicationNames.length})}
```

2022-04-13 07:11 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +                            {t('No matching application found')}
```suggestion
                            {t('No matching Application found')}
```
maybe like this ??

2022-04-13 07:18 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    }, [applicationMapping, subscriptionMapping]);
applicationMapping and setApplicationNames is different

setApplicationNames, setApplicationMapping
setApplicationNames, setApplicationNames

2022-04-13 07:21 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +    }, [applicationMapping, subscriptionMapping]);
yeah okay... got it... I checked it twice with above still I don't know how I get confused...
thanks...

2022-04-13 07:25 UTC, SanjalKatiyar approved these changes

2022-04-13 07:25 UTC, SanjalKatiyar commented
/lgtm

2022-04-13 09:24 UTC, afreen23 requested changes

2022-04-13 09:24 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Mirroring Status": "Mirroring Status",
```suggestion
  "Mirroring Status": "Mirroring status",
```

2022-04-13 09:24 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "UsedCapacity": "UsedCapacity",
```suggestion
  "Used capacity": "Used capacity",
```

2022-04-13 09:24 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Overall Image Health": "Overall Image Health",
```suggestion
  "Overall image health": "Overall Image Health",
```

2022-04-13 09:24 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Compression Savings": "Compression Savings",
```suggestion
  "Compression status": "Compression Status",
  "Compression savings": "Compression Savings",
```

2022-04-13 09:24 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.scss
> +        min-height: 200px;
lets use rem

2022-04-13 09:24 UTC, afreen23 commented on packages/shared/models/common.ts
> +  id: 'acmapplication',
```suggestion
```
They have become legacy now, we dont need to use id

2022-04-13 09:24 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.tsx
> +                                aria-label={t("App list table")}
```suggestion
                                aria-label={t("Application list ")}
```

2022-04-13 09:59 UTC, GowthamShanmugam commented
/retest

2022-04-13 11:22 UTC, afreen23 requested changes
some comments are repetitive from other Prs.

2022-04-13 11:22 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/application-status.scss
> +        min-height: 200px;
use rem

2022-04-13 11:22 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'drplacementcontrol',
```suggestion
```

2022-04-13 11:22 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'acmplacementrule',
```suggestion
```

2022-04-13 11:22 UTC, afreen23 commented on packages/mco/models/models.ts
> +    id: 'acmsubscription',
```suggestion
```

2022-04-13 11:22 UTC, afreen23 commented on packages/mco/types/types.ts
> +      Phase: string;
"phase" ??

2022-04-13 14:06 UTC, afreen23 approved these changes
/lgtm

2022-04-14 05:29 UTC, GowthamShanmugam commented
/retest

2022-04-18 10:30 UTC, afreen23 reviewed
/lgtm

2022-04-18 11:31 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-18 11:33 UTC, merged