Enabling Multicluster dashboard when ACM observability is enabled
red-hat-storage/odf-console pull request #159
Opened 2022-03-29 23:45 UTC by GowthamShanmugam

on top of: https://github.com/red-hat-storage/odf-console/pull/156

2022-03-30 02:17 UTC, bipuladh requested changes

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/queries.ts
> +
new line missing

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +};
Refactor this from ODF package and put it in shared.

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +            health = health < statusMetric?.value[1] ? statusMetric?.value[1] : health;
Ideally reduce should not have side effects to variables outside it's scope. So I don't think reduce or map should be used in this case.

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +            health = health < statusMetric?.value[1] ? statusMetric?.value[1] : health;
health is a string in the outer scope, I am not sure even if intrinsic conversion happens it's a right way to do the comparisons. Use  explicit conversions is required?

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +                {/*<StorageSystemPopup systemHealthMap={healthySystems} />*/}
Why?

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +    return {critical, warning, normal};
Use reduce here.

2022-03-30 02:17 UTC, bipuladh commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +const healthStateToIcon = {
How about using https://github.com/red-hat-storage/odf-console/blob/master/packages/shared/dashboards/status-card/states.tsx#L42 ?

2022-03-30 02:17 UTC, bipuladh commented on packages/odf/features.ts
> +
console.error or do something here.

2022-03-30 02:17 UTC, bipuladh commented on packages/odf/features.ts
> +  let mcokind: K8sModel = {...AcmMultiClusterObservabilityModel}
```suggestion
  let mcokind: K8sModel = AcmMultiClusterObservabilityModel
```
Wouldn't this work?
Same for configMapKind

2022-03-30 06:01 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +import { ACMMultiClusterObservability } from '@odf/mco/types';
https://github.com/red-hat-storage/odf-console/blob/7150378e539894dcb672ef7079487faa1beb7258/packages/odf/package.json#L6
now won't `/odf` be having a dependency on `/mco` as well ??

2022-03-30 06:10 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +};
ack

2022-03-30 06:16 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +            health = health < statusMetric?.value[1] ? statusMetric?.value[1] : health;
there is no type conversion here (implicit or explicit)... I am doing string comparison only...
`health` & `statusMetric?.value[1]` both are strings which can be `0 or 1 or 2` that's all, so even if we do comparison between these strings result will be same like doing comparison between numbers. So, I don't think there is need to do type conversion.

2022-03-30 06:17 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/queries.ts
> +
@SanjalKatiyar

2022-03-30 06:18 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/status-card.tsx
> +                {/*<StorageSystemPopup systemHealthMap={healthySystems} />*/}
It is WIP, we had a discussion regarding this yesterday only... will update this...

2022-03-30 06:19 UTC, SanjalKatiyar commented on packages/mco/components/mco-dashboard/status-card/storage-system-popup.tsx
> +const healthStateToIcon = {
ack...

2022-03-30 06:51 UTC, GowthamShanmugam commented on packages/odf/features.ts
> +import { ACMMultiClusterObservability } from '@odf/mco/types';
yes, mco is seperate packages now, which has only multicluster dashbaord related modals, i.e ACM and ramen models

2022-03-30 06:51 UTC, GowthamShanmugam commented on packages/odf/features.ts
> +
ack

2022-03-30 07:55 UTC, GowthamShanmugam commented on packages/odf/features.ts
> +import { ACMMultiClusterObservability } from '@odf/mco/types';
mmmm. it makesense. i will move this to shared

2022-03-30 08:01 UTC, GowthamShanmugam commented
@SanjalKatiyar @bipuladh changes done on enabling/disabling dashboard part.

2022-03-30 08:08 UTC, GowthamShanmugam commented on packages/shared/models/acm.ts
> +import { K8sModel } from '@openshift-console/dynamic-plugin-sdk/lib/api/common-types';
moved to shared because, it might be required by MCO package also in future

2022-04-08 20:54 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-06-14 05:19 UTC, GowthamShanmugam commented
/hold

2022-06-21 06:53 UTC, closed without merging