Add encryption configuration details to ODF dashboard
red-hat-storage/odf-console pull request #1609
Opened 2024-10-03 11:26 UTC by TimothyAsirJeyasing

https://issues.redhat.com/browse/RHSTOR-5286

2024-10-03 11:30 UTC, TimothyAsirJeyasing commented
MCG deployment without KMS
![Screenshot from 2024-10-02 18-02-07](https://github.com/user-attachments/assets/aec992b4-c12a-4e3d-89ad-fe68fe324aa2)
MCG with KMS
![Screenshot from 2024-10-02 17-56-48](https://github.com/user-attachments/assets/a2f12abd-2810-46d6-b171-1829e2020b6d)
![Screenshot from 2024-10-01 18-33-56](https://github.com/user-attachments/assets/ad2bd5bf-5af2-4e7f-a186-557b06c5b79b)

2024-10-03 13:41 UTC, alfonsomthd commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +            error={ocsError as any}
```suggestion
            error={ocsError}
```

2024-10-03 13:43 UTC, alfonsomthd commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
> +            error={ocsError as any}
```suggestion
            error={ocsError}
```

2024-10-03 13:47 UTC, alfonsomthd commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      aria-label="Encryption summary popover"
```suggestion
      aria-label={t('Encryption summary popover')}
```

2024-10-08 10:00 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  const getKmsTypeDescription = (encryptionKMSType: string, t: any) => {
```suggestion
  const getKmsTypeDescription = (encryptionKMSType: string, t: TFunction) => {
```

2024-10-08 10:00 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +    );
Make this a react component.

2024-10-08 10:01 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  const renderEncryptionDetails = () => {
This can be a function by itself.

2024-10-08 10:04 UTC, bipuladh commented
<img width="1296" alt="Screenshot 2024-10-08 at 3 39 38 PM" src="https://github.com/user-attachments/assets/046f838a-5afb-41a7-bf60-8f237988590a">
As seen in this screenshot wile testing your PR I see that both encryptions are enabled in the popover but the title is not enabled. This is something that needs to be fixed.

2024-10-08 10:08 UTC, bipuladh requested changes

2024-10-08 10:08 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
>              {inTransitEncryptionStatus}
Remove in transit encryption field as well

2024-10-08 10:08 UTC, bipuladh commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +              hasMCGEncryption={true}
If you're always passing true what is the point of having this field?

2024-10-08 10:08 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +        {isKmsEnabled || hasMCGEncryption ? t('Enabled') : t('Not enabled')}
I am not sure why KMS and MCG encryption are determining the status of encryption. We can have encryption without KMS as well.

2024-10-08 10:09 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  inTransitEncryption?: boolean;
in transit encryption is not mandatory / not available for MCG

2024-10-08 11:41 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
>              {inTransitEncryptionStatus}
ack

2024-10-08 12:00 UTC, TimothyAsirJeyasing commented
![image](https://github.com/user-attachments/assets/5ae17aeb-fbd9-4714-8248-840524755da6)

2024-10-09 09:41 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +        {isKmsEnabled || hasMCGEncryption ? t('Enabled') : t('Not enabled')}
Extended the check to also consider other forms of encryption to enable the link in the updated PR

2024-10-09 10:53 UTC, alfonsomthd commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +        {isKmsEnabled || hasMCGEncryption ? t('Enabled') : t('Not enabled')}
> Extended the check to also consider other forms of encryption to enable the link in the updated PR

cc @bipuladh

2024-10-10 08:50 UTC, alfonsomthd commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      return '';
In case we want all the VAULT entries to have the same description, we can do:
```
    case KmsImplementations.VAULT:
    case KmsImplementations.VAULT_TENANT_SA:
    case KmsImplementations.VAULT_TOKENS:
      return t('External Key Management Service: Vault');
```

2024-10-10 08:54 UTC, alfonsomthd commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      <Button variant="link" isInline>
```suggestion
      <Button variant={ButtonVariant.link} isInline>
```

2024-10-10 09:14 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      return '';
Ack, Sure I will add condition for token based and token based with multiple namespace also

2024-10-10 09:35 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +                </Text>
there should be space between this and other texts above this.

2024-10-10 09:37 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +import * as React from 'react';
move this file to `common` folder if u are reusing it between object and block & file...

2024-10-10 09:39 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +  };
move this outside the FC...
```suggestion
  const storageClusterResource = {
    kind: referenceForModel(StorageClusterModel),
    isList: true,
  };
```

2024-10-10 09:41 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +  const storageClusterEncryption = ocsData[0]?.spec?.encryption;
use `getStorageClusterInNs` instead of always reading 0th index...

2024-10-10 09:42 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +  const storageClusterEncryption = ocsData[0]?.spec?.encryption;
always 0th index is wrong...

2024-10-10 09:49 UTC, SanjalKatiyar commented
This PR does not incorporate external mode details card, external mode supports in-transit as well.

2024-10-10 09:50 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +
```suggestion
type EncryptionDetailsType = {
  kms: { enable: boolean };
};

```

2024-10-10 09:51 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +  };
```suggestion
  const encryptionDetails: EncryptionDetailsType = {
    kms: storageClusterEncryption?.kms ?? { enable: false },
  };
```

2024-10-10 09:51 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +  const hasStorageClassEncryption = !!encryptionDetails.storageClass;
```suggestion
```

2024-10-10 09:51 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +              hasStorageClassEncryption={hasStorageClassEncryption}
u don't have StorageClass encryption for object...
```suggestion
              hasStorageClassEncryption={false}
```

2024-10-10 09:56 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +              hasMCGEncryption={hasMCG}
`hasMCG` tell u whether NooBaa CR is existing in the namespace or not...
and from name `hasMCGEncryption` it suggests this flag signifies whether encryption is enabled or not...

both flags are independent of each others... either assumption here is wrong or naming is wrong... 
```suggestion
              hasMCGEncryption={hasMCG}
```

2024-10-10 10:21 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +  kms: { enable: boolean };
```suggestion
  kms?: { enable: boolean };
```

2024-10-10 10:23 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
> +              inTransitEncryption={!!inTransitEncryption}
is `inTransitEncryption` boolean or string ??
```suggestion
              inTransitEncryption={inTransitEncryption}
```

2024-10-10 10:24 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +// React Component for rendering encryption status with icons
```suggestion
```

2024-10-10 10:24 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +// React Component for rendering encryption status with icons
it's obvious...

2024-10-10 10:26 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  );
import existing icons from shared/icons... we should be having green-check-circle etc there...

2024-10-10 10:26 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  );
also, if needed, use PF5 classes... plz don't use PF4 anymore...

2024-10-10 10:31 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      return t('External Key Management Service: Azure Key Vault');
no need to externalise KMS provider names...
create an enum of names under `odf/constants/kms.ts` and import from there and display....
```suggestion
      return t('External Key Management Service: Vault');
    case KmsImplementations.IBM_KEY_PROTECT:
      return t(
        'External Key Management Service: Hyper Protect Crypto Services'
      );
    case KmsImplementations.KMIP:
      return t(
        'External Key Management Service: Thales CipherTrust Manager (using KMIP)'
      );
    case KmsImplementations.AZURE:
      return t('External Key Management Service: {{ provider }}', {provider: <READ_FROM_ENUM> });
```

2024-10-10 10:36 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +                  <StatusIcon enabled={encryptionDetails.clusterWide} />
this is wrong, why are u using clusterwide flag for filesystem encrypted storageclass ??
```suggestion
                  <Text component={TextVariants.h6}>{t('File storage')}</Text>
                </FlexItem>
                <FlexItem align={{ default: 'alignRight' }}>
                  <StatusIcon enabled={} />
```

2024-10-10 10:39 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +    React.useState<string>('');
```suggestion
```

2024-10-10 10:40 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  }, [configLoaded, configLoadError, configMapData, isKmsEnabled, t]);
use `useMemo` directly...

2024-10-10 10:40 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +    React.useState<string>('');
https://github.com/red-hat-storage/odf-console/pull/1609/files#r1795176583

2024-10-10 10:40 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      const kmsData = JSON.parse(configMapData.data.test || '{}');
what is this "test" key ??

2024-10-10 10:41 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      const kmsData = JSON.parse(configMapData.data.test || '{}');
this will never work like this... there are many key-value pairs in this configMap... how are u determining the correct one ??

2024-10-10 10:44 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  hasStorageClassEncryption: boolean,
when `encryptionDetails` already contains this value, why are we passing it again as a separate prop ??
```suggestion
```

2024-10-10 10:45 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  hasMCGEncryption: boolean,
plz rename it to a better name...

2024-10-10 10:46 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  hasStorageClassEncryption,
when `encryptionDetails` already contains this value, why are we passing it again as a separate prop ??
```suggestion
```

2024-10-10 10:46 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  hasMCGEncryption,
plz rename it to a better name...

2024-10-10 10:56 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +  isKmsEnabled: boolean,
`encryptionDetails` already had info about `hasStorageClassEncryption` and `isKmsEnabled`, no need to pass again...
```suggestion
  hasMCGEncryption: boolean,
```

2024-10-11 06:12 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      return t('External Key Management Service: Azure Key Vault');
Sure

2024-10-11 06:25 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-internal/encryption-popover.tsx
> +      const kmsData = JSON.parse(configMapData.data.test || '{}');
got it, the key may be different based on the users input, i will update to dynamically retrieves the key

2024-10-11 06:47 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-external/details-card.tsx
> +    ocsCluster?.spec?.network?.connections?.encryption?.enabled;
Instead of doing same thing again and again in 3 diff files (internal/external and object), why not just move this common part inside `EncryptionPopover` directly ??

If really needed, pass isObjectDashboard, isInternalDashboard, isExternalDashboard as props.

2024-10-11 06:51 UTC, SanjalKatiyar commented on packages/odf/types/kms.ts
> +
move this to `odf/constants/kms.ts` file and use exact names which we are already using on the KMS dropdown: https://github.com/red-hat-storage/odf-console/blob/master/packages/odf/constants/kms.ts#L38

2024-10-11 06:52 UTC, SanjalKatiyar commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +  });
```suggestion
  return !!provider ? t('External Key Management Service: {{ provider }}', {
    provider,
  }) : '';
```

2024-10-11 06:53 UTC, SanjalKatiyar commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +  isKmsEnabled: boolean,
`encryptionDetails` already has info about `isStorageClassEncrypted` & `isKmsEnabled`... no need to pass it again as a separate variables...

2024-10-11 06:54 UTC, SanjalKatiyar commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +        hasMCG,
u are again passing `hasMCG` to variable called `hasMCGEncryption`, both things are un-related to one another...

2024-10-11 06:58 UTC, SanjalKatiyar commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +                {t(
need some spacing between these 2 texts...

2024-10-11 07:01 UTC, SanjalKatiyar commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +        }
this is incorrect, this will just give you first key of the configMap... this configMap contains info of multiple KMS connections, how will you map the one which was set at day 1 installation ??

2024-10-11 07:02 UTC, SanjalKatiyar commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +      isKmsEnabled
why `isKmsEnabled` is needed ??

2024-10-11 07:02 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +        hasMCG,
i want only hasMCG variable only as MCG always encrypted. I will change other place also or use the flag isObjectDashboard

2024-10-11 07:07 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +        }
it finds the  key and checks each key for valid KMS data by attempting to parse the value and looking for the encryptionKMSType field.

However it would be problematic if the ConfigMap contains information for multiple KMS connections with valid encryptionKMSType filed. I have no idea which one to decide in such situation. Any suggestion please ?

2024-10-11 09:17 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +      isKmsEnabled
not required here, will remove this

2024-10-11 09:55 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +                {t(
Sure, added now as follows:
![image](https://github.com/user-attachments/assets/3c5e7f69-e429-45f4-9ab3-03844b2df850)

2024-10-11 10:36 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/persistent-external/details-card.tsx
> +    ocsCluster?.spec?.network?.connections?.encryption?.enabled;
ack

2024-10-11 10:38 UTC, TimothyAsirJeyasing commented on packages/ocs/dashboards/common/details-card/encryption-popover.tsx
> +        }
As discussed i will use ocs-kms-connection-details

2024-10-14 14:43 UTC, alfonsomthd commented
All comment seem to be addressed, so @SanjalKatiyar to finally tag it.

2024-10-15 04:26 UTC, bipuladh approved these changes
/lgtm

2024-10-15 07:22 UTC, merged