DRPolicy creation page
red-hat-storage/odf-console pull request #161
Opened 2022-04-01 22:07 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-04-01 22:07 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/161347425-cbe08587-8734-4d91-97ee-45eb765b1ee8.png)

2022-04-01 23:29 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    if(storageSystemLoaded && cephClusterLoaded  && intialUpdate){
Please suggest me it you any other way without intialUpdate flag, i want to update selectedClusters state  inside useEffect. it is list of object, but i want to update one particular object.

2022-04-01 23:29 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    if(storageSystemLoaded && cephClusterLoaded  && intialUpdate){
without intialUpdate it keep render

2022-04-07 21:57 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/162326585-6fa4235c-06ad-46d3-84ce-0e25933f2c83.png)

2022-04-08 20:32 UTC, GowthamShanmugam commented
/assign bipul

2022-04-08 20:32 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-04-12 07:00 UTC, afreen23 requested changes
will do deep review in sometime but something caught my attention not relevant to this PR but worth pointing.

2022-04-12 07:00 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "Select schedule time format in minutes or hours or days": "Select schedule time format in minutes or hours or days",
```suggestion
  "Select schedule time format in minutes, hours or days": "Select schedule time format in minutes, hours or days",
```

2022-04-12 07:00 UTC, afreen23 commented on package.json
>    "license": "MIT",
The authority is concerning. L5
Plugin is written by a couple of folks working at red hat. cc @bipuladh 
It should be UI data foundation team .

2022-04-12 09:41 UTC, afreen23 requested changes

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/utils/disaster-recovery.ts
> +    });
```suggestion
    names.sort()
```
default sorting is ascending.

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/utils/disaster-recovery.ts
> +export const createUniqueName = (names: string[]) => {
we should choose a better way to create names:
- k8s allows only characters upto 253 I guess
- it can be a very long name

we can create mirror peer with same name as dr policy

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/utils/disaster-recovery.ts
> +    odfVsersion.localeCompare(ODF_MINIMUM_VERSION, undefined, { numeric: true, sensitivity: 'base' }) >= 0
```suggestion
    odfVersion.localeCompare(ODF_MINIMUM_VERSION, undefined, { numeric: true, sensitivity: 'base' }) >= 0 
```

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
>              <DataListItem key="">
lets add key as well.

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +                    !Object.keys(selectedClusters)?.some((scName) => scName === fc.name)
Make sure "selectedClusters" is  never undefined otherwise it will give errors. 
```suggestion
                    !Object.keys(selectedClusters ?? [])?.some((scName) => scName === fc.name)
```

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +          "region": fectchRegion(cluster) ?? ""
```suggestion
          "region": fetchRegion(cluster) ?? ""
```

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +          "region": fectchRegion(cluster) ?? ""
This can be outside , seems like helper

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +  }, []);
This can be outside the component as well.

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +                title={t(`${c?.name} has invalid ODF version, update to ODF ${ODF_MINIMUM_VERSION} or latest version to enable DR protection`)}
```suggestion
                title={t(`{{name}} has invalid ODF version, update to ODF {{version}} or latest version to enable DR protection`, {name: c?.name,  version: ODF_MINIMUM_VERSION})}
```

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +              {(errorMessage as any)?.message}
```suggestion
              {errorMessage}
```

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        {errorMessage && (
```suggestion
        {errorMessage?.message && (
```

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +                title={t(`${c?.name} is not connected to CEPH`)}
correct the externalization format. We need to wrap variables in `{{}}`.

2022-04-12 09:41 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        {!!Object.values(selectedClusters).length && (
same here, ensure selectedClusters are never undefined/null

2022-04-12 12:33 UTC, afreen23 requested changes

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const [ocs, ocsLoaded, ocsLoadError] = useK8sGet<StorageSystemKind>(
```suggestion
  const [odf, odfLoaded, odfLoadError] = useK8sGet<StorageSystemKind>(
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    name
```suggestion
    clusterName
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const { name, region, storageSystem, odfVersion} = cluster;
```suggestion
  const { name, region, storageSystem, odfVersion} = cluster ?? {};
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    cluster?.name
```suggestion
clusterName
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const { name, region, storageSystem, odfVersion} = cluster;
```suggestion
  const { name: clusterName, region, storageSystem, odfVersion} = cluster;
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +          csv.metadata.name.startsWith(ODF_OPERATOR)
There must be a helper already defined.

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +
```suggestion
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    if (Object.keys(selectedClusters)?.length === 2) {
Store keys and values in a variable , we are requiring it often looks like
```suggestion
    if (Object.keys(selectedClusters ?? [])?.length === 2) {
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      setOCSDetected(false);
```suggestion
      setODFDetected(false);
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        };
Use "reduce" its much cleaner 
```suggestion
     const storageClusterIDs = Object.values(selectedClusters)?.reduce((ids, cluster) => {
        if (cluster?.storageClusterId !== "") {
          ids.add(cluster?.storageClusterId);
        };
        return ids;
        }, new Set(''));
```

2022-04-12 12:33 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +  selectedClusters: {[name in string] : Cluster};
you can create a new type for this, similar to MirrorPeerMapping type

2022-04-12 14:57 UTC, GowthamShanmugam commented on package.json
>    "license": "MIT",
what is the exact name i need to use here?

2022-04-12 16:01 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +export const createUniqueName = (names: string[]) => {
we can't use drpolicy name, one mirrorpeer is common between multiple drpolicies, so we can'y update the same mirrorpeer when we create another drpolicy.

i will try to convert thiese name to SHA256

2022-04-12 18:15 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const [ocs, ocsLoaded, ocsLoadError] = useK8sGet<StorageSystemKind>(
its not odf, i am reading ocs-storagecluster-storagesystem type, it is one type in ODF

2022-04-12 18:35 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        };
reduce will loop through all the element, here i want to hard stop the looping and assinging  setReplicationInputManual(true);

here, we dont need to loop further even one selected cluster dont have storageClusterId. i feel every is the best this usecase.

2022-04-12 19:06 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Overall Image Health": "Overall Image Health",
These are blockpool locales, looks like it was missed from last PR

2022-04-12 20:58 UTC, afreen23 requested changes

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +            <DataListItem key="select cluster">
Keys should be unique for each item. It helps react to learn the order when reconciling.
```suggestion
            <DataListItem key={fc?.name}>
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/utils/disaster-recovery.ts
> +export const createUniqueName = (names: string[]) => {
You dont need to do all this, just use `generateName` instead of a specific name , k8s will take care of everything

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        metadata: { name: uniqueName, labels: {"peers": peerNames?.join('_')}},
```suggestion
        metadata: { generateName: "mirror-peer-", labels: {"peers": peerNames?.join('_')}},
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +          Object.values(selectedClusters)?.map((c) => (
Since you are using this at a couple of places
```
         const clusterData =  Object.values(selectedClusters)
         const clusterNames = Object.keys(selectedClusters)
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    if (Object.keys(selectedClusters ?? [])?.length === 2) {
Since you are using this at a couple of places
```
         const clusterData =  Object.values(selectedClusters)
         const clusterNames = Object.keys(selectedClusters)
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const [isReplicationInputManual, setReplicationInputManual] = React.useState(false);
```suggestion
  const [isReplicationInputManual, setIsReplicationInputManual] = React.useState(false);
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      let storageClusterId = new Set('');
```suggestion
      const storageClusterId = new Set('');
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        (acc && cluster?.storageSystem !== "" && cluster?.isValidODFVersion), true));
Why not use filter ?
```suggestion
    setODFDetected(Object.values(selectedClusters)?.every((cluster) => (cluster?.storageSystem !== "" && cluster?.isValidODFVersion)));
```

2022-04-12 20:58 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +        };
Okay,  I missed those setStates below in previous review thinking its outside the loop. if thats the case then you can do something like this as well:
```suggestion
    const clustersData = Object.values(selectedClusters ?? []);
   
      const hasReplicationInputManual = clustersData?.every((cluster) => clustersData?.storageClusterId !== "");
    
      const storageClusterIDs = clustersData?.reduce((ids, cluster) => {
      if (cluster?.storageClusterId !== "") {
	          ids.add(cluster?.storageClusterId);
	        };
	        return ids;
      }, new Set(''));
      
setReplicationInputManual(hasReplicationInputManual);
setReplication(hasReplicationInputManual || storageClusterId.size > 1 ? REPLICATION_TYPE(t)['async'] : REPLICATION_TYPE(t)['sync']);
```

Currently the returned value from every is not utilized anywhere.

2022-04-12 20:59 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const [ocs, ocsLoaded, ocsLoadError] = useK8sGet<StorageSystemKind>(
then better would be to use storage system as the variable name - odf can many things - csv , ss, subscription ??

2022-04-13 04:34 UTC, bipuladh requested changes

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +          storageClusterId: cephCluster?.status?.ceph?.fsid ?? "",
```suggestion
          storageClusterId: cephCluster?.status?.ceph?.fsid ?? "",
```
Do we need optional chaining if the resources is loaded and no error is present?

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      return existingPeerNames.sort().join(',')=== peerNames.sort().join(',')
```suggestion
      return existingPeerNames.sort().join(',') === peerNames.sort().join(',')
```

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +const fetchMirrorPeer = (mirrorPeers: MirrorPeerKind[], peerNames: string[]) => (
```suggestion
const fetchMirrorPeer = (mirrorPeers: MirrorPeerKind[], peerNames: string[]): boolean => (
```

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const [mirrorPeers] = useK8sWatchResource<MirrorPeerKind[]>({
Please use loadError and loaded to avoid overusing optional chaining. Call functions that work on mirrorPeers after the data is sucessfully loaded.

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +    if (clustersData?.length === 2) {
```suggestion
    if (clustersData.length === 2) {
```
Is optional chaining really required?

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      }, new Set(''));
```suggestion
      }, new Set());
```

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      onClick={(e) => setReplication(e.currentTarget.id)}
```suggestion
      onClick={() => setReplication(replType)}
```

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const clustersData =  React.useMemo(() => Object.values(selectedClusters) ?? [], [selectedClusters]);
```suggestion
  const clustersData =  React.useMemo(() => Object.values(selectedClusters), [selectedClusters]);
```
Object.values will pass you an empty array with anything else you will get a type error.

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      setODFDetected(clustersData?.every((cluster) => (cluster?.storageSystem !== "" && cluster?.isValidODFVersion)));
```suggestion
      setODFDetected(clustersData.every((cluster) => (cluster?.storageSystem !== "" && cluster?.isValidODFVersion)));
```
Isn't `clusterData` a guaranteed empty array at the very least. I don't think optional chaining is required.

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +    if (!acc.includes(cluster?.region) && cluster?.region !== "") {
```suggestion
    if (cluster?.region !== "") {
```
Use a set instead.

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      history.push(url.replace(`${drPolicyKind}/~new`, ""));
Are we not supposed to push the details page instead?

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +import { getODFCsv } from '@odf/core/utils';
Why is MCO importing from ODF? If these things are shared utils move it to shared packages?

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +      );
Does this need to be inside of a `useEffect` or even inside the component?

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +          region: region,
```suggestion
          name,
          region,
```

2022-04-13 04:34 UTC, bipuladh commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +      delete sc?.[name]
```suggestion
      let sc = _.cloneDeep(selectedClusters);
      delete sc?.[name]
```
Shallow copy is not enough if you want to work directly on the state object.

2022-04-13 05:08 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +          storageClusterId: cephCluster?.status?.ceph?.fsid ?? "",
fsid is introduced on rook recently, only ODF 4.11 will have this value. Usecase is, if this value is not present or unable to read from the managedclusters then we need to ask the user to input the replication type manually. So user wont blocked on DRPolicy creation operation due to this value.

2022-04-13 05:09 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      return existingPeerNames.sort().join(',')=== peerNames.sort().join(',')
ack

2022-04-13 05:12 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +  const [mirrorPeers] = useK8sWatchResource<MirrorPeerKind[]>({
mirrorPeers value is used only inside OnSubmit function, that why i removed load and loaderror

2022-04-13 05:33 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +    if (!acc.includes(cluster?.region) && cluster?.region !== "") {
I need to avoid duplicate region on same list here, if i set it as set then it need to convert to list. so this check is avoiding duplicate here.

2022-04-13 05:34 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      history.push(url.replace(`${drPolicyKind}/~new`, ""));
We dont have details page for DRPolicy. it is beyond 4.11

2022-04-13 05:34 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +import { getODFCsv } from '@odf/core/utils';
ack, moving these to shared

2022-04-13 07:54 UTC, afreen23 commented on package.json
>    "license": "MIT",
We dont need to add a name here. Just remove L5.

2022-04-13 08:19 UTC, afreen23 requested changes
yarn.lock is showing some changes

2022-04-13 08:19 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +      isReplicationAutoDetectable ? setReplication(storageClusterIDs.size > 1 ? REPLICATION_TYPE(t)['async'] : REPLICATION_TYPE(t)['sync']) : setReplication(REPLICATION_TYPE(t).async);
can't we tweak the conditions and combine them ? Just adding an example:
```suggestion
    setReplication(isReplicationAutoDetectable && storageClusterIDs.size  <= 1 ? REPLICATION_TYPE(t)['sync'] : REPLICATION_TYPE(t)['async']) 
```

2022-04-13 08:19 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +      let sc = _.cloneDeep(selectedClusters);
```suggestion
      const sc = _.cloneDeep(selectedClusters);
```

2022-04-13 08:19 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +
```suggestion
```

2022-04-13 08:43 UTC, afreen23 requested changes

2022-04-13 08:43 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/select-cluster-list.tsx
> +                    Object.keys(selectedClusters)?.length === MAX_ALLOWED_CLUSTERS &&
```suggestion
                    Object.keys(selectedClusters ?? [])?.length === MAX_ALLOWED_CLUSTERS &&
```

2022-04-13 08:43 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +
```suggestion
```

2022-04-13 10:38 UTC, GowthamShanmugam commented on package.json
>    "license": "MIT",
i removed

2022-04-13 11:01 UTC, afreen23 requested changes

2022-04-13 11:01 UTC, afreen23 commented on package.json
> +    "i18n-mco": "i18next \"packages/**/*.{ts,tsx}\" [-oc] -c i18next-parser.config.js"
why this ?

2022-04-13 11:38 UTC, GowthamShanmugam commented on package.json
> +    "i18n-mco": "i18next \"packages/**/*.{ts,tsx}\" [-oc] -c i18next-parser.config.js"
Oh! sorry, i was a mistake

2022-04-13 13:51 UTC, afreen23 approved these changes
@bipuladh had some comments not resolved. Lets resolve those and merge the PR. LGTM

2022-04-13 13:52 UTC, afreen23 commented
/hold
The CI seems pretty smart :D , @bipuladh review the PR and remove hold

2022-04-14 08:03 UTC, bipuladh approved these changes

2022-04-14 08:06 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-15 11:17 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/163564789-6c0c50cc-2cf6-43f8-813c-74a4ece2bb6b.png)

2022-04-18 06:56 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws
/lgtm

2022-04-18 08:12 UTC, bipuladh commented
/hold cancel

2022-04-18 08:15 UTC, merged