Enable provider/consumer dashboard
red-hat-storage/odf-console pull request #163
Opened 2022-04-04 16:19 UTC by SanjalKatiyar

https://issues.redhat.com/browse/RHSTOR-2505

2022-04-18 08:22 UTC, SanjalKatiyar commented on packages/shared/monitoring/useAlert.ts
> +    basePath: basePath || GetPrometheusBasePath(),
passing `basePath` as optional parameter in case we want to override path returned by `GetPrometheusBasePath`...
will be useful for example when we expose this component as a npm package and some other UI plugin wants to use it, in that case it can pass `basePath` to its own external Prometheus.

2022-04-18 08:23 UTC, SanjalKatiyar commented on packages/shared/hooks/use-alerts.ts
> -export default useAlerts;
removed it as it was already present under `packages/shared/monitoring/useAlert.ts`.

2022-04-18 08:24 UTC, SanjalKatiyar commented on packages/shared/hooks/custom-prometheus-poll/utils.ts
> +  useFlag("ODF_MANAGED") ? '/api/proxy/plugin/odf-console/odf-managed-service-prom' : ''
these constants are used at only one place that is why directly added them here instead of `constants` directory.

2022-04-18 09:14 UTC, SanjalKatiyar commented on packages/shared/constants/prometheus.ts
> +export const PROMETHEUS_TENANCY_BASE_PATH = window.SERVER_FLAGS.prometheusTenancyBaseURL;
was giving type error on window object... but window object has `SERVER_FLAGS` flag so it will work during runtime...

2022-04-18 09:15 UTC, SanjalKatiyar commented on packages/shared/dashboards/utilization-card/ConsumerPopover.tsx
> +  basePath?: string;
passing `basePath` as optional parameter in case we want to override path returned by GetPrometheusBasePath...
will be useful for example when we expose this component as a npm package and some other UI plugin wants to use it, in that case it can pass basePath to its own external Prometheus.

2022-04-18 09:15 UTC, SanjalKatiyar commented on packages/shared/dashboards/utilization-card/prometheus-utilization-item.tsx
> +  basePath?: string;
passing `basePath` as optional parameter in case we want to override path returned by GetPrometheusBasePath...
will be useful for example when we expose this component as a npm package and some other UI plugin wants to use it, in that case it can pass `basePath` to its own external Prometheus.

2022-04-18 12:29 UTC, bipuladh commented on packages/shared/constants/prometheus.ts
> +// @ts-ignore (typescript-error: Property 'SERVER_FLAGS' does not exist on type 'Window & typeof globalThis')
Please add a type file that adds SERVER_FLAGS to window object.

2022-04-18 12:29 UTC, bipuladh commented on packages/shared/dashboards/utilization-card/prometheus-utilization-item.tsx
> +import { useCustomPrometheusPoll } from '@odf/shared/hooks/custom-prometheus-poll/custom-prometheus-poll-hook';
Plesae add a index file to the hooks folder and expose everything from there.

2022-04-18 12:31 UTC, bipuladh requested changes

2022-04-18 12:31 UTC, bipuladh commented on packages/shared/hooks/custom-prometheus-poll/utils.ts
> +export const GetPrometheusBasePath = () =>
You can call hooks only inside react hooks. Change this to `usePrometheusBasePath`.

2022-04-18 12:31 UTC, bipuladh commented on packages/shared/hooks/custom-prometheus-poll/utils.ts
> +  useFlag("ODF_MANAGED") ? '/api/proxy/plugin/odf-console/odf-managed-service-prom' : ''
declare a constant in the same file.

2022-04-19 06:42 UTC, GowthamShanmugam commented on packages/ocs/dashboards/block-pool/compression-details-card.tsx
>        endpoint: 'api/v1/query' as any,
you are using 'api/v1/query' also in lot of placed, better declare it as constants

2022-04-19 06:47 UTC, SanjalKatiyar commented on packages/ocs/dashboards/block-pool/compression-details-card.tsx
>        endpoint: 'api/v1/query' as any,
agreed... but let's keep that for another PR:)
it needs changes in all the files of odf-console and is something unrelated to this PR

2022-04-19 06:56 UTC, GowthamShanmugam commented on packages/shared/dashboards/utilization-card/prometheus-utilization-item.tsx
>        endpoint: 'api/v1/query_range' as any,
```suggestion
      endpoint: PrometheusEndpoint.QUERY_RANGE,
```

2022-04-19 07:38 UTC, GowthamShanmugam commented on packages/ocs/dashboards/block-pool/compression-details-card.tsx
>        endpoint: 'api/v1/query' as any,
ack, LGTM

2022-04-19 17:11 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-19 17:12 UTC, bipuladh commented on packages/ocs/block-pool/BlockPoolListPage.tsx
> +      basePath: usePrometheusBasePath(),
Could basePath be an internal property of this hook and the `usePrometheusBasePath()` is called internally directly?

2022-04-20 05:27 UTC, bipuladh commented
/override odf-console-e2e-aws
/approve
/lgtm

2022-04-20 05:30 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-20 05:32 UTC, merged