Generic localization between odf and odfmco
red-hat-storage/odf-console pull request #180
Opened 2022-04-14 10:38 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-04-14 18:02 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Compression Savings": "Compression Savings",
okay, this PR is not specifically adding these texts...

2022-04-14 18:07 UTC, SanjalKatiyar commented on packages/shared/status/statuses.tsx
> +import { useSharedTranslation } from '../useTranslationHook';
nits: useTranslation is already provided by i18n... `useCustomTranslationHook` or `useSharedTranslationHook` as a name for the file would be better IMO.
```suggestion
import { useSharedTranslation } from '../useSharedTranslationHook';
```

2022-04-15 06:03 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Compression Savings": "Compression Savings",
Yep, looks like this was missed in already merged PR. i will change this.

2022-04-15 06:03 UTC, GowthamShanmugam commented on packages/shared/status/statuses.tsx
> +import { useSharedTranslation } from '../useTranslationHook';
ack

2022-04-15 06:51 UTC, GowthamShanmugam commented
@SanjalKatiyar @bipuladh Changes done

2022-04-15 06:51 UTC, GowthamShanmugam commented
/assign @bipuladh

2022-04-15 06:52 UTC, GowthamShanmugam commented
/assign @SanjalKatiyar

2022-04-18 11:06 UTC, afreen23 requested changes

2022-04-18 11:06 UTC, afreen23 commented on packages/shared/useCustomTranslationHook.ts
> +};
```suggestion
export const useCustomTranslation = () => useTranslation(NS);
```

2022-04-18 11:06 UTC, afreen23 commented on packages/shared/useCustomTranslationHook.ts
> +export const NS = process.env.NS;
```suggestion
export const NS = process.env.I8N_NS;
```

2022-04-18 11:06 UTC, afreen23 commented on packages/shared/useCustomTranslationHook.ts
> +export const NS = process.env.NS;
It will give more clarity about NS

2022-04-18 11:06 UTC, afreen23 commented on webpack.config.ts
> +  ['en', 'ja', 'ko', 'zh'].reduce((acc, lang) => ([...acc, { from: path.resolve(dirName, `locales/${lang}/plugin__*.json`), to: `locales/${lang}/${ns}.[ext]`}]), [])
Create a constant for the languages used:
export const LANGUAGES =  ['en', 'ja', 'ko', 'zh'];
```suggestion
 LANGUAGES.reduce((acc, lang) => ([...acc, { from: path.resolve(dirName, `locales/${lang}/plugin__*.json`), to: `locales/${lang}/${ns}.[ext]`}]), [])
```

2022-04-18 13:13 UTC, bipuladh commented
/lgtm
/override ci/prow/odf-console-e2e-aws

2022-04-18 13:13 UTC, bipuladh commented
/approve

2022-04-18 13:16 UTC, merged