DRPolicy empty page
red-hat-storage/odf-console pull request #181
Opened 2022-04-15 15:32 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-04-15 15:33 UTC, GowthamShanmugam commented
![image (4)](https://user-images.githubusercontent.com/15073590/163590275-69e9a609-06d0-4ab6-a995-25c2662ced6e.png)

2022-04-19 06:48 UTC, bipuladh requested changes

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/empty-state-page/emptyPage.scss
> +
Extra line

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/empty-state-page/emptyPage.tsx
> +      <img src={image} className="mco-empty-page__icon"/>
Add `alt` attribute as well.

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/empty-state-page/emptyPage.tsx
> +export const EmptyPage: React.FC<EmptyPageProps> = (props) => {
Can we make this a default export?

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +              onClick={() => props.history.push(createProps)}
Why not use `useHistory` instead of passing history as prop?

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.scss
> +    @media (min-width: 768px){
Please check https://www.patternfly.org/v4/developer-resources/global-css-variables/#breakpoint-variables-and-class-suffixes

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.scss
> +        margin-top: 1rem;
Use standard PF spacers.

2022-04-19 06:48 UTC, bipuladh commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +export const DRPolicyListPage: React.FC<RouteComponentProps> = (props) => {
Unless props are required to be passed lets avoid passing props to components. It makes the component easy to maintain and self-contained. Most of the route props can be accessed via hooks.

2022-04-19 07:47 UTC, GowthamShanmugam commented on packages/mco/components/empty-state-page/emptyPage.tsx
> +export const EmptyPage: React.FC<EmptyPageProps> = (props) => {
ack

2022-04-19 07:48 UTC, afreen23 requested changes

2022-04-19 07:48 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "No disaster recovery policies yet": "No disaster recovery policies yet",
The CR name is DR policy. so we should use that. Also aligning with what we have in console as a not found text.
```suggestion
  "No DRPolicy found": "No disaster recovery policies yet",
```

2022-04-19 07:48 UTC, afreen23 commented on packages/mco/components/empty-state-page/emptyPage.tsx
> +import * as React from 'react';
The convention we use to name component files = empty-page.tsx

2022-04-19 07:48 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +              </Trans>
```suggestion
                Configure recovery to your failover cluster with a disaster recovery policy. Click the <strong> Create DRPolicy </strong> button to get started.
              </Trans>
```

2022-04-19 14:10 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "No disaster recovery policies yet": "No disaster recovery policies yet",
UX does not agree to keep it like this, they said it is similar to ACM's empty page message. so they want to keep it like this.

2022-04-19 14:59 UTC, afreen23 requested changes

2022-04-19 14:59 UTC, afreen23 commented on packages/mco/components/empty-state-page/empty-page.tsx
> +    <img src={image} className="mco-empty-page__icon" alt="Empty page logo" />
```suggestion
    <img src={image} className="mco-empty-page__icon" alt="Empty page logo" />
```
externalize

2022-04-19 15:10 UTC, afreen23 requested changes

2022-04-19 15:10 UTC, afreen23 commented on locales/en/plugin__odf-console.json
> +  "No disaster recovery policies yet to": "No disaster recovery policies yet to",
```suggestion
  "No disaster recovery policies yet": "No disaster recovery policies yet",
```

2022-04-20 06:42 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
> +                  <ListPageCreateLink to={createProps}>
ListPageCreateLink is not accepting any className

2022-04-20 07:17 UTC, GowthamShanmugam commented on packages/mco/components/empty-state-page/empty-page.tsx
> +      <EmptyState variant={EmptyStateVariant.large}>
className="mco-empty-page__background" on EmptyState is affecting the image position, div on top is working fine, div is just to set background color and background width

2022-04-20 10:03 UTC, afreen23 approved these changes
only one comment , approving from my end.

2022-04-20 10:03 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
>  export const DRPolicyListPage: React.FC<RouteComponentProps> = () => {
no props ??

2022-04-20 10:03 UTC, afreen23 commented
/lgtm cancel

2022-04-20 11:39 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
>  export const DRPolicyListPage: React.FC<RouteComponentProps> = () => {
yes, removed as per comment: https://github.com/red-hat-storage/odf-console/pull/181#discussion_r852652520

2022-04-20 20:10 UTC, afreen23 commented on packages/mco/components/data-policies/drpolicy-list-page/drpolicy-list-page.tsx
>  export const DRPolicyListPage: React.FC<RouteComponentProps> = () => {
Is it that some HOC passing down props and we dont require those here ?

2022-04-21 09:36 UTC, afreen23 approved these changes

2022-04-21 09:43 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-21 09:44 UTC, merged