Avoid UI conflict between odf-console and odf-multicluster-console using flags
red-hat-storage/odf-console pull request #183
Opened 2022-04-19 07:14 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-04-19 07:15 UTC, bipuladh commented on console-extensions.json
> +      "flag": "ODR_MODEL"
Where is this used?

2022-04-19 07:21 UTC, GowthamShanmugam commented on console-extensions.json
> +      "flag": "ODR_MODEL"
For DataService navigation on the ACM page. https://github.com/red-hat-storage/odf-console/pull/183/files#diff-2d79046ce9b0f8fda82dd631ce959a36f6c350960d54cf8fdb1579f3c718e83aR88

2022-04-19 07:23 UTC, GowthamShanmugam commented on console-extensions.json
> +      "flag": "ODR_MODEL"
right now we have only one DataPolicies, i.e DisasterRecovery, if the ODR Hub operator is not installed then we dont need to show DataService options.

In future, once we started supporting multiple data services and data policies we will need to hide only the DisasterRecovery tab

2022-04-19 08:00 UTC, afreen23 requested changes

2022-04-19 08:00 UTC, afreen23 commented on console-extensions.json
> +      "flag": "ODR_MODEL"
Is this flag currently defined anywhere ? I cant find that.

2022-04-19 13:14 UTC, GowthamShanmugam commented on console-extensions.json
> +      "flag": "ODR_MODEL"
it is used: https://github.com/red-hat-storage/odf-console/pull/183/files#diff-2d79046ce9b0f8fda82dd631ce959a36f6c350960d54cf8fdb1579f3c718e83aR88

This extension will create this flag based on CRD present

2022-04-19 13:59 UTC, GowthamShanmugam commented on console-extensions.json
> +      "flag": "ODR_MODEL"
@afreen23 ^

2022-04-20 07:28 UTC, bipuladh commented
/approve
/override ci/prow/odf-console-e2e-aws
/lgtm

2022-04-20 07:34 UTC, merged