Remove kubevirt from kms modals
red-hat-storage/odf-console pull request #187
Opened 2022-04-19 09:04 UTC by SanjalKatiyar

2022-04-19 10:36 UTC, afreen23 reviewed
/lgtm
/hold
merge after #186

2022-04-19 10:46 UTC, afreen23 commented
/hold cancel

2022-04-19 11:39 UTC, bipuladh requested changes

2022-04-19 11:39 UTC, bipuladh commented on packages/odf/components/kms-config/vault-config.tsx
> +      <Modal {...modalProps} />
I would prefer if we can mount the Modal somewhere higher up in the DOM tree.

2022-04-19 11:39 UTC, bipuladh commented on packages/odf/modals/advanced-kms-modal/advanced-ibm-kms-modal.tsx
> +  const [tokenUrl, setTokenUrl] = React.useState(kms?.tokenUrl || '');
Please add a loading and errorState.

2022-04-19 11:42 UTC, SanjalKatiyar commented on packages/odf/modals/advanced-kms-modal/advanced-ibm-kms-modal.tsx
> +  const [tokenUrl, setTokenUrl] = React.useState(kms?.tokenUrl || '');
not needed for this modal because:
1. It is not been used anywhere right now. I have added a comment on the top "This Modal is not used anywhere right now. Not removing it though, might be useful in upcoming release."
2. There are no CRUD operations, it is just populating local React state, also all fields are optional & no validation is present.

2022-04-19 12:40 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws
/lgtm

2022-04-19 16:11 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-19 16:12 UTC, bipuladh commented
/approve

2022-04-20 05:47 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-20 05:56 UTC, merged