Create DRPolicy page
red-hat-storage/odf-console pull request #189
Opened 2022-04-20 17:00 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-04-20 17:00 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/164284202-0e2d1626-6893-4928-9c1b-0b5f675d1645.png)

2022-04-20 20:13 UTC, afreen23 requested changes

2022-04-20 20:13 UTC, afreen23 commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +              'Openshift Data Foundation 4.11 or above must be installed on the managed clusters to setup connection for enabling replication/mirroring'
```suggestion
              'Data Foundation 4.11 or above must be installed on the managed clusters to setup connection for enabling replication/mirroring'
```

2022-04-21 07:49 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/create-dr-policy/create-dr-policy.tsx
> +              'Openshift Data Foundation 4.11 or above must be installed on the managed clusters to setup connection for enabling replication/mirroring'
Ack

2022-04-21 09:36 UTC, afreen23 approved these changes

2022-04-21 09:43 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-21 12:30 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-21 12:40 UTC, merged