migrate feature.ts functions
red-hat-storage/odf-console pull request #195
Opened 2022-04-25 15:41 UTC by SanjalKatiyar

2022-04-26 09:33 UTC, bipuladh requested changes

2022-04-26 09:33 UTC, bipuladh commented on packages/odf/features.ts
> +};
Why are we blocking these stuffs?

2022-04-26 09:33 UTC, bipuladh commented on packages/odf/features.ts
> +  );
I don't think this is required here.

2022-04-26 11:46 UTC, SanjalKatiyar commented on packages/odf/features.ts
> +  );
ack...

2022-04-26 11:52 UTC, bipuladh approved these changes

2022-04-29 04:42 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-04-29 04:52 UTC, merged