Bug 1993916: Visual feedback on OBC deletion
red-hat-storage/odf-console pull request #210
Opened 2022-05-16 11:16 UTC by rexagod

Adds a "hoverMessage" field for "ResourceKebab" component, allowing
passing a message to display when the kebab button is disabled (during
deletion) when the user hovers over it.

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
***
![image](https://user-images.githubusercontent.com/33557095/168580402-57797bc2-1bd6-4738-9f23-4bb0d2ec5bfc.png)

2022-05-31 16:18 UTC, rexagod commented
/cc @bipuladh @GowthamShanmugam PTAL, thanks.

2022-06-02 22:37 UTC, rexagod commented
/cc @GowthamShanmugam @bipuladh Can we merge this?

2022-06-16 05:04 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-06-16 07:27 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Disabled because the Object Bucket Claim is being deleted.": "Disabled because the Object Bucket Claim is being deleted.",
```suggestion
  "Disabled because the ObjectBucketClaim is being deleted.": "Disabled because the ObjectBucketClaim is being deleted.",
```

Ref: http://openshift.github.io/openshift-origin-design/conventions/documentation/capitalization.html

2022-06-16 07:27 UTC, GowthamShanmugam commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the Object Bucket Claim is being deleted.'
same here

2022-06-16 07:28 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
you can keep that comment here:
/* hoverMessage is only visible when kebab is disabled, i.e., when its associated resource is being deleted */

2022-06-16 07:35 UTC, rexagod commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
ACK

2022-06-16 07:35 UTC, rexagod commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the Object Bucket Claim is being deleted.'
ACK

2022-06-16 07:35 UTC, rexagod commented on locales/en/plugin__odf-console.json
> +  "Disabled because the Object Bucket Claim is being deleted.": "Disabled because the Object Bucket Claim is being deleted.",
ACK

2022-06-16 07:43 UTC, GowthamShanmugam approved these changes

2022-06-16 09:57 UTC, bipuladh requested changes

2022-06-16 11:32 UTC, cloudbehl commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the ObjectBucketClaim is being deleted.'
Isn't there a design recommended from OCP team? It looks like a generic issue.

2022-06-16 11:35 UTC, rexagod commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the ObjectBucketClaim is being deleted.'
This http://openshift.github.io/openshift-origin-design/conventions/documentation/capitalization.html (provided by Gowtham above) makes sense for the OBC part, but I think @bipuladh meant the UXD approval for the entire wording, right?

2022-06-16 11:37 UTC, cloudbehl commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the ObjectBucketClaim is being deleted.'
Ahh okay, even for that how does wording look for other resources stuck on deletion?

2022-06-16 12:29 UTC, rexagod commented on packages/shared/kebab/kebab.tsx
> +        hoverMessage ? hoverMessage : 'Resource is being deleted.'
Yep, updated.

2022-06-17 05:56 UTC, bipuladh commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the ObjectBucketClaim is being deleted.'
This is a new behavior in OCP altogether

2022-06-18 14:00 UTC, andybraren commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            'Disabled because the ObjectBucketClaim is being deleted.'
Started a discussion thread [here](https://coreos.slack.com/archives/CC4C1BLP7/p1655488223832519).

2022-06-21 01:45 UTC, agarwal-mudit commented
/cherry-pick release-4.11
/cherry-pick release-4.11-compatibility

2022-06-23 05:27 UTC, rexagod commented
Rebasing.

2022-06-23 11:37 UTC, rexagod commented
Rebased.

2022-07-08 10:06 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
isVisible will work for trigger is manual

2022-07-08 11:32 UTC, rexagod commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
Right, changing.

2022-07-08 11:41 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
But if you change it to manual then,  I worried it might display an empty tooltip even if the content is null or empty, 

so remove isVisisble, and keep it like this:
 ```
 <Tooltip
      content={hoverMessage ? hoverMessage : 'Resource is being deleted.'}
      trigger= {isDisabled && !!hoverMessage ? 'mouseenter' : 'manual'}
 ```

2022-07-08 11:42 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
without isVisisble manual wont display any tooltip

2022-07-18 22:41 UTC, rexagod commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
Sorry, I don't get why we need to do [this](https://github.com/red-hat-storage/odf-console/pull/210#discussion_r916736873)? Just using `content` alongwith `manual` trigger and `isVisible` set should work, right?

(I've made the change you suggested above, but just want to clarify)

2022-07-19 06:13 UTC, GowthamShanmugam commented on packages/shared/kebab/kebab.tsx
> +      isVisible={isDisabled && !!hoverMessage}
if it is working just with content along with manual trigger then i am ok

2022-08-04 10:39 UTC, bipuladh approved these changes

2022-08-04 12:11 UTC, merged

2022-08-04 14:28 UTC, rexagod commented
I'll send a PR.