Fix kebab action for OBC and BlockPoolListPage
red-hat-storage/odf-console pull request #283
Opened 2022-06-14 10:41 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-06-14 10:42 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/173559258-c0b5801a-fbad-4540-bebd-e630355e78ce.png)

2022-06-14 13:01 UTC, bipuladh requested changes

2022-06-14 13:01 UTC, bipuladh commented on packages/odf/components/mcg/ObjectBucketClaim.tsx
> +            },
```suggestion
```
Already done by https://github.com/red-hat-storage/odf-console/pull/255

2022-06-21 06:51 UTC, GowthamShanmugam commented
![Screenshot from 2022-06-21 12-16-18](https://user-images.githubusercontent.com/15073590/174735096-6eef3a3e-6201-4bf3-9808-e93053ace96e.png)

2022-06-21 08:06 UTC, GowthamShanmugam commented
/retest

2022-06-21 08:39 UTC, GowthamShanmugam commented
/test

2022-06-21 08:41 UTC, GowthamShanmugam commented
/test build-test

2022-06-21 08:41 UTC, GowthamShanmugam commented
/retest

2022-06-21 08:44 UTC, GowthamShanmugam commented
/test all

2022-06-21 10:56 UTC, bipuladh requested changes

2022-06-21 10:56 UTC, bipuladh commented on packages/ocs/block-pool/BlockPoolDetailsPage.tsx
> +      path: `${location.pathname.split(`/${kind}`)[0]}/overview/block-file`,
```suggestion
      path: `${location.pathname.split(`/${kind}`)[0]}/${kind}`,
```

2022-06-21 11:29 UTC, GowthamShanmugam commented on packages/ocs/block-pool/BlockPoolDetailsPage.tsx
> +      path: `${location.pathname.split(`/${kind}`)[0]}/overview/block-file`,
ack

2022-06-21 13:21 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-06-21 18:07 UTC, merged

2022-06-21 18:13 UTC, GowthamShanmugam commented
/cherry-pick release-4.11-compatibility