Update Cypress webpack and TSC configs
red-hat-storage/odf-console pull request #30
Opened 2021-09-09 08:51 UTC by rexagod

![2021-09-09-133731_2560x1440_scrot](https://user-images.githubusercontent.com/33557095/132654703-df00d01e-0628-4465-a264-4d84a81f5cc1.png)

/cc @bipuladh

2021-09-09 08:53 UTC, bipuladh requested changes

2021-09-09 08:53 UTC, bipuladh commented on cypress/plugin.js
> +        extensions: ['.tsx', '.ts', '.js'],
Why tsx? All our files are going to `spec.ts`.

2021-09-09 08:53 UTC, bipuladh commented on cypress/plugin.js
> +  },
Why are we handling the output file? Do we want create one file which contains all tests?

2021-09-09 09:03 UTC, rexagod commented on cypress/plugin.js
> +        extensions: ['.tsx', '.ts', '.js'],
Fixed this and the regex below, PTAL.

2021-09-09 09:09 UTC, rexagod commented on cypress/plugin.js
> +  },
Cypress folks [recommend bundling](https://github.com/cypress-io/cypress/blob/master/npm/webpack-preprocessor/examples/use-ts-loader/webpack.config.js#L18) to reduce request times for Cypress GET, POST, etc. requests. Nonetheless, this will still show up as different tests in the console same as we see in console.
![2021-09-09-143805_2560x1440_scrot](https://user-images.githubusercontent.com/33557095/132657454-583fc189-e99c-48b9-b68d-b7829a00f420.png)

2021-09-13 09:50 UTC, bipuladh commented on cypress/plugin.js
> +  },
ah okay!

2021-09-13 09:51 UTC, bipuladh approved these changes
/lgtm

2021-09-13 10:13 UTC, merged