Bug 2043572: Deleting namespace store in UI secrets remains
red-hat-storage/odf-console pull request #337
Opened 2022-07-01 11:00 UTC by TimothyAsirJeyasing

Remove secret which was created automatically during
namespace creation and Keep the secret if its created
manually and assigned to namespace.

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2022-07-01 11:00 UTC, TimothyAsirJeyasing commented
@bipuladh , @GowthamShanmugam , @SanjalKatiyar Please review

2022-07-19 11:07 UTC, GowthamShanmugam commented on packages/shared/modals/DeleteModal.tsx
> +      switch (resource['spec']['type']) {
i deleting namespace store should deleted secret using owner ref.

2022-08-02 08:19 UTC, TimothyAsirJeyasing commented on packages/shared/modals/DeleteModal.tsx
> +      switch (resource['spec']['type']) {
Secret named with unique

2022-08-10 08:29 UTC, bipuladh requested changes
Lets do this only if a secret of that particular name exists. We can handle this if we get an error around secret not being present. So the flow would be. 
1) Try and create a secret without the random characters.
2) If the secret is present then we would get an error. If we get such an error then only append these random characters to the name. We could avoid that by adding more intelligence. We could try checking the content of these two secrets and if it matches we could use the same secret instead of creating but this could be later tackled (the matching of secret content).

2022-09-26 04:21 UTC, closed without merging