DR Failover/Recovery action
red-hat-storage/odf-console pull request #347
Opened 2022-07-20 15:15 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-07-20 15:16 UTC, GowthamShanmugam commented
/hold

2022-08-17 11:35 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/185108730-6e34c156-bfcc-4b17-88b3-200c9ccff2df.png)

2022-08-17 15:17 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Cannot initiate {{actionType}} as DR is not enabled, apply DRpolicy to the application to proceed.": "Cannot initiate {{actionType}} as DR is not enabled, apply DRpolicy to the application to proc
```suggestion
  "Cannot initiate {{actionType}} as DR is not enabled, apply DRPolicy to the application to proceed.": "Cannot initiate {{actionType}} as DR is not enabled, apply DRPolicy to the application to proceed.",
```

2022-08-17 15:25 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +        const drPolicyList = await getDRPolicyList(acmToDRState);
```suggestion
        const drPolicyList = getDRPolicyList(acmToDRState);
```
`getDRPolicyList` is not returning any Promise, we don't need async/await here, right ?

2022-08-17 15:26 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +const getDRPolicyList = async (acmToDRState: ACMToDRState[]) => [
```suggestion
const getDRPolicyList = (acmToDRState: ACMToDRState[]) => [
````
`getDRPolicyList` is not handling any Promise...

2022-08-17 15:39 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +        )
```suggestion
        Promise.all(
          drPolicyList.map((drPolicyName) =>  k8sGet({
              model: DRPolicyModel,
              name: drPolicyName,
            })
          )
        )
```

2022-08-17 15:40 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +        )
u can use `await` in front of `Promise.all` but that is not required...

2022-08-17 15:48 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +    setIsOpen(isOpen);
```suggestion
    setIsOpen(!isOpen);
```
don't we want to add `!` ??

2022-08-17 15:51 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +    });
nits: `?.` not required
```suggestion
    const drPolicy: DRPolicyKind = drPolicies[e.currentTarget.id];
    setSelected({
      policyName: getName(drPolicy),
      drClusters: drPolicy.spec?.drClusters,
    });
```

2022-08-17 15:57 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +  t: TFunction;
do we need to pass it to another FC ? can't we use hook again ?
Anyway if we are passing, please check once during runtime there are no i18n error in the developer console... I have seen it some times that if we pass `t` to a normal function and if we don't explicitly specify the namespace like `plugin__odf-console~` then during runtime there are errors in the logs.

2022-08-17 16:54 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +    !!state.selectedSubsGroups.length;
```suggestion
  const canInitiate =
    !findErrorMessage(state.errorMessage, false) &&
    !!state.selectedSubsGroups.length;
```

2022-08-17 16:55 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +        isDisable: !isAbleToInitiate(),
```suggestion
        isDisable: !canInitiate,
```

2022-08-17 16:58 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +    .find((errorMessage) => errorMessage);
are u just returning very first error u r getting ?

2022-08-17 17:00 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +  };
should be done inside useEffect

2022-08-17 17:06 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +    Promise.all(promises)
we only have one Promise for `k8sPatch`, we don't need `promises` list or `Promise.all`...

2022-08-17 17:20 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +) => objectRefList.includes(objectRef?.name);
`objectRefList?.includes(objectRef?.name);`

2022-08-17 17:28 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +      ) &&
if any of these 2 conditions are `false`, `subsMap` will become `false` as well and loop will return a boolean value...

2022-08-17 18:05 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +    return subsMap;
nits: `arr` signify that it is an array
```suggestion
  subscriptions?.reduce((obj, subscription) => {
    const plsRuleName = subscription?.spec?.placement?.placementRef?.name;
    const subsMap =
      isPlacementRuleModel(subscription) &&
      isObjectRefMatching(
        subscription?.spec?.placement?.placementRef,
        drPlacementRules
      ) &&
      matchApplicationToSubscription(subscription, application)
        ? {
            ...obj,
            [plsRuleName]:
              plsRuleName in arr
                ? [...arr[plsRuleName], getName(subscription)]
                : [getName(subscription)],
          }
        : obj;
    return subsMap;
```

2022-08-17 18:17 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +  }, [
nits:
```suggestion
  const drPlacementRules: string[] = React.useMemo(() =>
    // Filtering placementRules which are all controlled by DR opeator
    placementRulesLoaded && !placementRulesLoadError
      ? filterDRPlacementRules(placementRules)
      : []
  , [placementRules, placementRulesLoaded, placementRulesLoadError]);

  const subscriptionMap: SubcsriptionMap = React.useMemo(() =>
    // Filtering subscription using DR placementRules and application selectors
    subscriptionsLoaded && !subscriptionsLoadError
      ? filterDRSubscriptions(application, subscriptions, drPlacementRules)
      : {}
   , [
```

2022-08-17 18:19 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +  const memoizedResponse = useDeepCompareMemoize(response);
even if anyone of three resources changes, hook will return new reference anyway...

2022-08-17 18:28 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +    <>
```suggestion
```

2022-08-18 07:09 UTC, bipuladh requested changes

2022-08-18 07:09 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +  const { title, description, action, isOpen, resource, close, t } = props;
nit: Destructure it in line 75.
Also do not pass `t`.

2022-08-18 07:09 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +    state.acmToDRState.forEach((acmToDRState) => {
What is `acmToDRState`?

2022-08-18 07:09 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/failover-and-relocate-modal.tsx
> +          },
if the type of the action is `FailoverAndRelocateType.SET_ERROR_MESSAGE` then why does the payload need to have `updateErrorMessage` again? It looks like unnecessary repetition to me.

2022-08-18 07:09 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.scss
> +      var(--pf-global--spacer--md) var(--pf-global--spacer--lg);
```suggestion
    padding: var(--pf-global--spacer--md) var(--pf-global--spacer--lg);
```

2022-08-18 07:09 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.scss
> +    --pf-global--FontSize--md: 13px;
Why are we reassigning variables?

2022-08-18 08:11 UTC, SanjalKatiyar commented on packages/mco/constants/dr-policy.ts
> +});
I have a doubt if translation will work this way at runtime...
IMO we will explicitly have to pass the namespace here... if there are no error at runtime in the logs then we should be good... plz check it once...

2022-08-18 08:13 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +});
can't we do this, since all 3 initial statuses are same ?
```suggestion
const initalPeerStatus = (t: TFunction) => ({
  initialStatus: {
    icon: <UnknownIcon />,
    text: t('ns~Unknown'),
  },
});
```

2022-08-18 08:17 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +    text: 'Unknown',
```suggestion
    text: t('ns~Unknown'),
```

2022-08-18 08:18 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +      const status = state.acmToDRState?.reduce((arr, acmToDRState) => {
nits: initial state is an object not array...
```suggestion
      const status = state.acmToDRState?.reduce((obj, acmToDRState) => {
```

2022-08-18 08:25 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +  ]);
I can see this `useEffect` only updating `peerReadiness` (which is a local state for this FC), how other 2 checks will get updated ?

2022-08-18 08:48 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/subscription-group-selector.tsx
> +      setOpen(isOpen);
on toggling state should negate right ?
```suggestion
      setOpen(!isOpen);
```

2022-08-18 08:49 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/subscription-group-selector.tsx
> +    const onSelect = (_, selection) => {
nits:
```suggestion
    const onSelect = (_, selection) =>
```

2022-08-18 11:22 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +    setIsOpen(isOpen);
Both are same here isOpen is arg not state var

2022-08-18 11:27 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +  t: TFunction;
It dont see any error, may be all FC are always rendered in this modal

2022-08-18 11:29 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +    .find((errorMessage) => errorMessage);
exactly, here I am reading errors on priority wise.

2022-08-18 11:55 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/dr-policy-selector.tsx
> +      id={index.toString()}
i am index to fetch the DRPolicy object from the list based on the selection:
 const drPolicy: DRPolicyKind = drPolicyList[e.currentTarget.id];
 i am just trying to avoid one more looping here.

2022-08-18 12:02 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.scss
> +    --pf-global--FontSize--md: 13px;
Ah! i forgot to remove this,

2022-08-18 12:08 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/subscription-group-selector.tsx
> +      setOpen(isOpen);
the same here, selector will pass this as arg, we are using  state variable

2022-08-18 12:08 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +  ]);
Yes, other two are dummy values for now, DR team is working on that

2022-08-18 12:52 UTC, GowthamShanmugam commented on packages/mco/constants/dr-policy.ts
> +});
i tested this, run time dont see any issue when Unknown | Peer ready | Peer not ready appears

2022-08-18 12:56 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +    resources()
no need to call it as a function, we can make `resources` as an object...

2022-08-18 12:58 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +    resources()
Ah yes, i can change to object, right now i am using as function

2022-08-18 13:01 UTC, SanjalKatiyar commented on packages/mco/constants/dr-policy.ts
> +});
ok...

2022-08-18 13:01 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +  ]);
ack !

2022-08-19 10:43 UTC, GowthamShanmugam commented
@SanjalKatiyar @bipuladh all changes are done

2022-08-23 07:44 UTC, bipuladh requested changes

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +              : obj.peerReadiness.text;
Please create a `getPeerReadiness` function.

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/peer-status.tsx
> +                peerReadiness === PEER_READINESS(t).PEER_READY ? (
```suggestion
                peerReadiness === PEER_READINESS(t).PEER_READY ? (
```
I don't think this a right approach where we need to resolve translations even for performing string comparisons.  We should have intermediate values and use translations only on places that are visible to the end user.

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/subscription-group-selector.tsx
> +    // To avoid re-rendering when a new drpcState object is generated with same props
```suggestion
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/subscription-group-selector.tsx
> +    // To avoid re-rendering when a new selectedTargetCluster object  is generated with same props
```suggestion
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/subscription-group-selector.tsx
> +    // To avoid re-rendering when a new selectedDRPolicy object is generated with same props
```suggestion
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +  const { isClusterAvailable } = props;
```suggestion
const TargetClusterStatus: React.FC<TargetClusterStatusProps> = ({isClusterAvailable}) => {

```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +  const [isOpen, setIsOpen] = React.useState(false);
```suggestion
  const [isOpen, setOpen] = React.useState(false);
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +  const memoizedDRPolicy = useDeepCompareMemoize(state.selectedDRPolicy, true);
Why do we need to memoize state values?

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +      const drClusters = drClusterList.map((drCluster) => drCluster);
What are we doing with this map?

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +  subscriptions?.reduce((obj, subscription) => {
```suggestion
  subscriptions?.reduce((acc, subscription) => {
```
nit: stick to commonly used variable names with reduce such as `acc`, curr` or something relevant to make it easier to understand.

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +    const plsRuleName = subscription?.spec?.placement?.placementRef?.name;
```suggestion
    const placementRuleName = subscription?.spec?.placement?.placementRef?.name;
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +                : [getName(subscription)],
```suggestion
 [...(obj[plsRuleName] || {}), getName(subscription)]

```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +    namespace: namespace,
```suggestion
    namespace,
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +      // Filtering placementRules which are all controlled by DR opeator
```suggestion
```

2022-08-23 07:44 UTC, bipuladh commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/modal-body.tsx
> +  [placementRuleName in string]: string[];
```suggestion
  [placementRuleName: string]: string[];
```
nit: use in when you are working with enums or interfaces.

2022-08-25 10:26 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
> +  return cephFSIDs?.size <= 1 ? REPLICATION_TYPE.SYNC : REPLICATION_TYPE.ASYNC;
no it should be either 1 or greater than one, even for 0 providing SYNC is not correct

2022-08-25 11:43 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +  const memoizedDRPolicy = useDeepCompareMemoize(state.selectedDRPolicy, true);
Ah! i think its a mistake

2022-08-25 11:51 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/applications/failover-and-relocate-modal/target-cluster-selector.tsx
> +      const drClusters = drClusterList.map((drCluster) => drCluster);
ManagedClusters is ACM CR, and DR is using very similar CR DRClusters But it has only DR level info. Here, We use has to select the ManagedCluster and we are displaying the health of the selected managed cluster. 

Once managed cluster is selected, we are checking its DR level status using its equal DRCluster CR. We are checking whether the cluster is fenced or not, and whether are we able to Relocate / Failover.

Summary:
  ManagedCluster CR is providing: Actual cluster health 
   DRCluster CR is providing: DR level health

2022-08-25 13:06 UTC, GowthamShanmugam commented
@bipuladh Done with all the changes

2022-08-25 17:31 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "All system workloads and their available resources will be transferred back to the recovery (failover) site.": "All system workloads and their available resources will be transferred back to the r
```suggestion
  "All system workloads and their available resources will be transferred to the recovery (failover) site.": "All system workloads and their available resources will be transferred to the recovery (failover) site.",
```
does transfer "back" to recovery site make sense ?? transfer back to origin sounds good, but is it same for this case as well ??

2022-08-25 17:34 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "All system workloads and their available resources will be transferred back to the recovery (failover) site.": "All system workloads and their available resources will be transferred back to the r
or this origin and recovery sites are relative ?? any one cluster can act as origin and other will be recovery site ??

2022-08-29 06:41 UTC, GowthamShanmugam commented
/hold cancel

2022-08-29 06:45 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "All system workloads and their available resources will be transferred back to the recovery (failover) site.": "All system workloads and their available resources will be transferred back to the r
yes, one cluster is the origin and another one is the recovery site. Once the user is done with Failover to the recovery site, they will relocate the workload back to the origin cluster when the origin cluster is back to a healthy state.

2022-08-29 06:47 UTC, bipuladh requested changes

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/dr-policy-selector.tsx
> +  const [drPolicies, drPoliciesLoaded, drPoliciesLoadedError] =
```suggestion
  const [drPolicies, drPoliciesLoaded, drPoliciesLoadError] =
```
nit

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/dr-policy-selector.tsx
> +  };
```suggestion
  const onToggle = (isOpen) => setOpen(isOpen);
```

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/dr-policy-selector.tsx
> +  const onSelect = (e) => {
types

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/dr-policy-selector.tsx
> +        className="mco-dr-action-body__dropdown-width"
```suggestion
        className="mco-dr-action-body__dropdown--width"
```
rather than `width` use `wide` or `narrow` to define the type of Modifier it is.

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
> +    const subscriptionMap: SubcsriptionMap = React.useMemo(
Will `useMemo` suffice? Since these are not equal by  reference it would always return a new object.

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
> +      response.placementRules
```suggestion
      response.placementRules, true
```

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
> +    );
```suggestion
    const memoizedSubscriptions = useDeepCompareMemoize(response.subscriptions);
    const memoizedDRPlacementControls = useDeepCompareMemoize(
      response.drPlacementControls
    );
```
You prolly would want to pass the second arg as `true` to compare string values.

2022-08-29 06:47 UTC, bipuladh commented on packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal.tsx
> +    !!state.selectedSubsGroups.length;
nit new line.

2022-08-29 06:47 UTC, bipuladh commented on packages/shared/selectors/k8s.ts
> +export const getErrorMessage = (error: Error) => error?.message;
```suggestion
export const getErrorMessage = (error: Error) => error?.message;
```
Not a generic K8s selector move it to a different file.

2022-08-29 07:47 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/app-failover-relocate/failover-relocate-modal-body.tsx
> +    const subscriptionMap: SubcsriptionMap = React.useMemo(
We can't avoid that I think, end of the day i am generating drPolicyControlState from this file and it has memorize on other files

2022-09-01 13:58 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/app-failover-relocate/dr-policy-selector.tsx
> +  );
Yes, only this object is created by processing the ACM and DR objects. Reset all are derived from this object. When something changes on ACM or DR CR, this object is re-created, but the content of this object is sometimes the same.
So only for this custom object I am using memorize, so other object won't be crated again and again unnecessarily.

2022-09-01 14:19 UTC, SanjalKatiyar commented
/approve
/lgtm

2022-09-05 12:10 UTC, SanjalKatiyar commented
/lgtm

2022-09-05 20:03 UTC, GowthamShanmugam commented
/retest

2022-09-06 06:19 UTC, agarwal-mudit commented
/retest

2022-09-06 08:08 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-06 10:51 UTC, SanjalKatiyar commented
/lgtm

2022-09-06 12:21 UTC, merged