Fix Overview tab is present under Storage section
red-hat-storage/odf-console pull request #351
Opened 2022-07-28 12:37 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-07-28 12:42 UTC, GowthamShanmugam commented
/retest

2022-07-28 12:45 UTC, GowthamShanmugam commented
With ODF-MCO console and ODF-console

![image](https://user-images.githubusercontent.com/15073590/181508161-2b52d0fa-96f8-4a30-bfe7-dfb1962cd340.png)

2022-07-29 06:50 UTC, GowthamShanmugam commented on packages/ocs/block-pool/BlockPoolListPage.tsx
> +  const loaded = blockPoolsLoaded && (cephLoaded || scLoaded);
Fix for blockpool page shows not found, I am fixing this part of this because this is also related to hybrid console and this is also a blocker issue

2022-07-29 06:50 UTC, GowthamShanmugam commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +              systemLoadError?.message ||
same here object dashbaord goes blank

2022-08-01 15:02 UTC, bipuladh requested changes

2022-08-01 15:02 UTC, bipuladh commented on console-extensions.json
> -  {
Lets move this file also inside of odf and make console-extension a generated file. Also add it to gitignore as well. Also make it part of install so that it doesn't cause users confusion. We also need to update the readme about adding extensions to packages instead of in the main console-extensions file.

2022-08-03 06:25 UTC, bipuladh commented on scripts/generatePluginPackage.ts
> +/* Copyright Contributors to the Open Cluster Management project */
```suggestion

```

2022-08-03 06:25 UTC, bipuladh commented on webpack.config.ts
> +    path: path.resolve('./dist'),
Lets compile it to one place? Or is that going to be an issue to run the two plugins concurrently?

2022-08-03 06:25 UTC, bipuladh commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
```suggestion
    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve",
```
Webpack should recursively look for the config file? Is it not able to find it?

2022-08-03 06:38 UTC, GowthamShanmugam commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
it is not finding, becuase not it is invoked from plugins directory, not root directory

2022-08-03 07:08 UTC, SanjalKatiyar commented on plugins/mco/console-plugin.json
> +  "description": "Console plugin for ODF",
```suggestion
  "displayName": "MCO Plugin",
  "description": "Console plugin for MCO",
```

2022-08-03 07:11 UTC, SanjalKatiyar commented on webpack.config.ts
> +import MergeJsonWebpackPlugin from 'merge-jsons-webpack-plugin';
```suggestion
```
not used anywhere ?

2022-08-03 07:19 UTC, SanjalKatiyar commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
`NODE_ENV={MODE}` this "MODE" is it some default env variable ? because we are not exporting it ourselves anywhere...

2022-08-03 07:21 UTC, SanjalKatiyar commented on package.json
> +    "build-dev": "NODE_ENV=production PLUGIN=odf I8N_NS=plugin__odf-console yarn build:plugin",
"yarn build" and "yarn build-dev" are exactly same...

2022-08-03 07:27 UTC, SanjalKatiyar commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
also do we need to `NODE_ENV={MODE} I8N_NS=${I8N_NS}` again during serving ? we are already exporting these during build command...

2022-08-03 07:27 UTC, GowthamShanmugam commented on webpack.config.ts
> +    path: path.resolve('./dist'),
right now we dont have a concurrent use case, but ya with this solution concurrent is also possible. I am compiling inside corresponding plugin folder and it is considered as a root folder

2022-08-03 07:34 UTC, GowthamShanmugam commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
I tried, but I am getting errors


Can't resolve './src' in '/home/gshanmug/Workspace/Openshift/odf-console/plugins/mco
Can't resolve './src' in '/home/gshanmug/Workspace/Openshift/odf-console/plugins/odf

2022-08-03 07:35 UTC, GowthamShanmugam commented on package.json
> +    "build-dev": "NODE_ENV=production PLUGIN=odf I8N_NS=plugin__odf-console yarn build:plugin",
build-dev should not have NODE_ENV=production

2022-08-03 07:37 UTC, GowthamShanmugam commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
build command is for production and service is for dev setup which we are running locally, so yes we need this on both the places

2022-08-03 07:41 UTC, SanjalKatiyar commented on package.json
> +    "server:plugin": "cd plugins/${PLUGIN} && ts-node ../../scripts/generatePluginPackage.ts && yarn clean && NODE_ENV={MODE} I8N_NS=${I8N_NS} yarn ts-node ../../node_modules/.bin/webpack serve -c ..
okay... but "MODE" we have not initialized this variable anywhere...

2022-08-04 10:30 UTC, bipuladh commented
/approve
/lgtm

2022-08-04 10:31 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-08-04 10:47 UTC, bipuladh commented
/test images
/test odf-console-e2e-aws

2022-08-04 14:12 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-08-04 16:00 UTC, merged

2022-08-04 16:00 UTC, bipuladh commented
/cherrypick release-4.11
/cherrypick release-4.11-compatibility

2022-08-04 16:17 UTC, bipuladh commented
/cherrypick release-4.11-compatibility