Bug 2089446 - Handle leftover rook-ceph-external-cluster-details secret
red-hat-storage/odf-console pull request #360
Opened 2022-08-03 10:34 UTC by TimothyAsirJeyasing

Resolves bz#2089446
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2022-08-03 10:35 UTC, TimothyAsirJeyasing commented
@bipuladh , @GowthamShanmugam Please review

2022-08-04 06:33 UTC, bipuladh requested changes

2022-08-04 06:33 UTC, bipuladh commented on packages/odf/components/create-storage-system/footer.tsx
> +      await deleteSecret(secretResource.name);
Why are we deleting secret without checking if the secret actually exists? If the secret exists could we patch it and update it instead of deleting it?

2022-08-04 06:36 UTC, TimothyAsirJeyasing commented on packages/odf/components/create-storage-system/footer.tsx
> +      await deleteSecret(secretResource.name);
deleteSecret functionn is checking the secret availability. Do you mean we will rename the existing one and let the flow creates new one.

2022-09-02 09:27 UTC, SanjalKatiyar commented
/close
closing for now as https://bugzilla.redhat.com/show_bug.cgi?id=2089446#c6

2022-09-02 09:27 UTC, closed without merging