Add admin flag (for hiding Data Foundation section from non-admin users)
red-hat-storage/odf-console pull request #361
Opened 2022-08-04 11:18 UTC by SanjalKatiyar

**Admin:**
![Screenshot from 2022-08-04 15-08-46](https://user-images.githubusercontent.com/39404641/182834392-3c3959b0-7e09-429f-ba29-dc5375f93b9d.png)
**Non-Admin:**
![Screenshot from 2022-08-04 15-05-43](https://user-images.githubusercontent.com/39404641/182834384-722c951a-8710-498f-9492-5e0456d1977a.png)

2022-08-04 11:25 UTC, bipuladh requested changes
Please perform a SSAR check on the StorageSystem CR instead.

2022-08-17 13:19 UTC, SanjalKatiyar commented on packages/odf/features.ts
> -export const LSO_FLAG = 'LSO';
removed this flag as well...

2022-08-18 11:15 UTC, bipuladh commented
/lgtm

2022-08-18 11:20 UTC, SanjalKatiyar commented
/cherrypick release-4.11

2022-08-18 11:20 UTC, SanjalKatiyar commented
/cherrypick release-4.11-compatibility

2022-08-18 11:20 UTC, merged

2022-08-18 15:33 UTC, SanjalKatiyar commented
Need to manually backport to 4.11, 4.10 and 4.9