[WIP] Integration with Thales enterprise key management
red-hat-storage/odf-console pull request #389
Opened 2022-08-23 14:11 UTC by SanjalKatiyar

2022-08-25 16:36 UTC, SanjalKatiyar commented
![Screenshot from 2022-08-25 21-30-43](https://user-images.githubusercontent.com/39404641/186721200-6b5c32f2-fa31-49bd-97b3-94bd4526ab52.png)
![Screenshot from 2022-08-25 21-30-54](https://user-images.githubusercontent.com/39404641/186721204-dae63297-9675-411e-a47f-c25909a92532.png)
![Screenshot from 2022-08-25 21-31-06](https://user-images.githubusercontent.com/39404641/186721208-859f9387-1fe6-4311-8527-515cbc0cc39a.png)

2022-08-26 12:24 UTC, SanjalKatiyar commented
@GowthamShanmugam @bipuladh PTAL.

2022-08-29 05:33 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/kms-config.tsx
> +      dispatch({
Do we really need two different states here? can we make it one

2022-08-29 05:36 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/kms-config.tsx
> +      dispatch({
Also, why you are re-factored again? this might leads to new regressions.  I dont think its a good idea to refactor KMS again.

2022-08-29 05:37 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/name-address-port.tsx
> +import * as React from 'react';
This design is not scalable, if new KMS comes with a name and without an address and port it leads to re-factor again, I feel it's ok to keep it redundant between different KMS.

2022-08-29 05:40 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/kms-config.tsx
> +      dispatch({
we will test it thoroughly, this refactor is required.
currently we have one big state for KMS, irrespective of what provider user is choosing, object will always contain state for all the providers. Now, after refactor object will contain the state of only selected KMS, hence reducing state's size.

2022-08-29 05:43 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/thales-config.tsx
> +      {uploadInputItems(t).map((uploadItem: UploadInputItem) => (
I prefer to move this under an advanced Thales configured file, but keep these as mandatory fields. Design-wise no changes, just moving this to keep a similar file structure to other KMS file structures. If we want to support HTTP way on the future then changes are effortless.

2022-08-29 05:46 UTC, GowthamShanmugam commented on packages/odf/types/kms.ts
> +export type CommonKMSConfig = VaultConfig | ThalesConfig;
What is CommonKMSConfig? you can use KMSConfiguration right? why we need this

2022-08-29 05:46 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/name-address-port.tsx
> +import * as React from 'react';
it is a minor refactor...
we can pass new prop to this component if that happens... or for that new KMS, instead of using this NameAddressPort we can create new component for it depending upon need... 
but NameAddressPort component is shared/common between Thales and Vault both, so IMO make sense not repeat same code twice:)

2022-08-29 05:46 UTC, GowthamShanmugam commented on packages/odf/types/kms.ts
> +  providerState: VaultConfig | HpcsConfig | ThalesConfig;
```suggestion
  providerState: KMSConfiguration
```

2022-08-29 05:48 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/name-address-port.tsx
> +import * as React from 'react';
also, that is why I did not add this component under `shared` because this will not be used at many places... but atleast it is used twice, so keeping it under `kms-config` as a common component...

2022-08-29 05:51 UTC, GowthamShanmugam commented on packages/odf/types/kms.ts
> +  };
you can group this to KMSTLSConfig? these fields are always common for the KMS provider which are all supporting https.

2022-08-29 05:51 UTC, SanjalKatiyar commented on packages/odf/types/kms.ts
> +export type CommonKMSConfig = VaultConfig | ThalesConfig;
`CommonKMSConfig` is used in `NameAddrPort` component thus only supporting Vault and Thales... whereas `KMSConfiguration` is for all the providers...

2022-08-29 05:51 UTC, GowthamShanmugam commented on packages/odf/types/kms.ts
> +  KMIP = 'kmip', // used by both rook & ceph-csi
KMIP?

2022-08-29 05:56 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +        kmsObj.name.valid &&
are we sure about removing this optional param? I hope it won't break when QE changes anything directly  on  existing configMap or creating new one.

2022-08-29 05:59 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +    KMIP_ENDPOINT: `${`${parsedAddress.protocol}//${parsedAddress.hostname}`}:${
This is used on more than one placed, create a utils function for this

2022-08-29 05:59 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +  return keySecret.metadata.name;
getName(keySecret)

2022-08-29 06:02 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +    KMIP_SECRET_NAME: secretName || keySecret.metadata.name,
getName(keySecret)

2022-08-29 06:04 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +  }
```suggestion

```

2022-08-29 06:05 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +    );
```suggestion
    );
     if (!secretName) {
    // not required, while setting up storage cluster.
    // required, while creating new storage class.
    keySecret = generateThalesSecret(kms);
    csiKmsResources.push(k8sCreate({ model: SecretModel, data: keySecret }));
  }
```

2022-08-29 06:05 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +    name: `thales-kmip-kms-${Math.random().toString(36).substring(7)}`,
create utils function to generate random name, which will receive prefix as param

2022-08-29 06:08 UTC, GowthamShanmugam commented on packages/odf/types/kms.ts
> +export type CommonKMSConfig = VaultConfig | ThalesConfig;
we can't group with NameAddrPort port always when we need to handle which has NameAddrPort differently.

2022-08-29 06:08 UTC, GowthamShanmugam commented on packages/odf/types/kms.ts
> +export type CommonKMSConfig = VaultConfig | ThalesConfig;
since we have separate state for each, I dont think we have any necessary to introduce one more grouping relationship

2022-08-29 06:12 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/name-address-port.tsx
> +import * as React from 'react';
I feel it's ok to keep redundant fields between these two. if we do not support anyone  in the future then it is meaning less, also introducing grouping like this makes the KMS structure even more complex.

2022-08-29 06:15 UTC, bipuladh requested changes

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/utils.tsx
> +    KMIP_ENDPOINT: `${`${parsedAddress.protocol}//${parsedAddress.hostname}`}:${
```suggestion
    KMIP_ENDPOINT: `${parsedAddress.protocol}//${parsedAddress.hostname}}:${
```
why not?

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/utils.tsx
> +    name: `thales-kmip-kms-${Math.random().toString(36).substring(7)}`,
```suggestion
    name: `thales-kmip-kms-${getRandomChars(7)}`,
```
Can we please refactor this logic out for others as well?

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/utils.tsx
> +  csiKmsResources: Promise<K8sResourceKind>[],
Could we keep this a bit more functional. Rather than polluting the argument `csiKmsResources` could we return an array instead. It would be nice to have these helper functions as pure functions.

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/utils.tsx
> +) => {
```suggestion
): SecretKind['metadata']['name'] => {
```

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/utils.tsx
> +const createClusterThalesResources = (
The return value of the function and the name of the function really do not add up.

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/utils.tsx
> +    case ProviderNames.THALES: {
We could instead return the function directly than to update a local variable here and then pass it in the end. Could we please refactor the parent function.

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/vault-config.tsx
> +  ) as VaultConfig;
```suggestion
  );
```

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/components/kms-config/vault-config.tsx
> +  const vaultState = useDeepCompareMemoize(
```suggestion
  const vaultState = useDeepCompareMemoize<VaultConfig>(
```

2022-08-29 06:15 UTC, bipuladh commented on packages/odf/constants/kms.ts
> +export const ThalesEmptyState: ThalesConfig = Object.seal({
```suggestion
const ThalesEmptyState: ThalesConfig = Object.seal({
```
Let's make `ProviderStateMap` the only way to access these empty states outside of the file.

2022-08-29 06:16 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/name-address-port.tsx
> +import * as React from 'react';
Vault and Thals are two different KMS providers. If you are grouping something between the same KMS provider is fine, for example, Vault Token and Vault SA. 

Our design should work like, whatever changes happening on one KMS in the future then another one should work fine.

2022-08-29 13:53 UTC, SanjalKatiyar commented on packages/odf/types/kms.ts
> +  };
okay, on re-checking, I remember now... I kept this way intentionally...
here in Thales these are required fields and I have added validations to them as well... whereas in Vault there are no such validations (not sure why, assuming that maybe because there fields are optional in Vault)... so "error" key will be redundant in case of Vault and we will be maintaining extra variables which are not used... so keep it separate from Vault I did this...
let me know if u still think we should combine I can do so ??

2022-08-29 13:57 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +    KMIP_ENDPOINT: `${`${parsedAddress.protocol}//${parsedAddress.hostname}`}:${
because we have `//` between protocol and hostname, so "protocol//hostname" is one string then we need `:` between port and previous string...
may be I am missing something ?

2022-08-29 14:15 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +    );
sorry I did not get it... looks to me at correct place...

2022-08-29 14:18 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +    KMIP_ENDPOINT: `${`${parsedAddress.protocol}//${parsedAddress.hostname}`}:${
maybe I am missing something ?
`protocol` + `//` + `hostname` is one string... then this previous string + `:` + `port` is another string... looks okay to me...

2022-08-29 14:19 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +    KMIP_ENDPOINT: `${`${parsedAddress.protocol}//${parsedAddress.hostname}`}:${
ack !

2022-08-29 14:21 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +    );
we can't have it here in else part... during updation as well we can create a new KMS connection, hence new Secret...

2022-08-29 14:37 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/vault-config.tsx
> +  const vaultState = useDeepCompareMemoize(
if I do `useDeepCompareMemoize<VaultConfig>`, still typescript will not be happy about it as `state.kms.providerState` is of type `KMSConfiguration` and `KMSConfiguration` = `VaultConfig | HpcsConfig | ThalesConfig`

2022-08-29 14:38 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/vault-config.tsx
> +  const vaultState = useDeepCompareMemoize(
so I had to use `as` explicitly...

2022-08-29 14:40 UTC, SanjalKatiyar commented on packages/odf/constants/kms.ts
> +export const ThalesEmptyState: ThalesConfig = Object.seal({
ack...

2022-08-29 14:41 UTC, SanjalKatiyar commented on packages/odf/types/kms.ts
> +  providerState: VaultConfig | HpcsConfig | ThalesConfig;
ack !

2022-08-29 15:04 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +    );
updation means adding new connection details to csi configMap...

2022-08-29 15:30 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +  csiKmsResources: Promise<K8sResourceKind>[],
ack !

2022-08-29 15:32 UTC, SanjalKatiyar commented on packages/odf/components/kms-config/utils.tsx
> +const createClusterThalesResources = (
ack...

2022-08-30 06:26 UTC, SanjalKatiyar commented
@bipuladh @GowthamShanmugam changes done, PTAL.

2022-08-30 06:29 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +    );
Ah yes, leave this comment

2022-08-30 09:19 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/name-address-port.tsx
> +import * as React from 'react';
i agree, it leads to more redundant code

2022-08-30 09:21 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/thales-config.tsx
> +      {uploadInputItems(t).map((uploadItem: UploadInputItem) => (
Ah! in the future we need to keep each KMS-related components its own directory, only shared one should be in common directly.

2022-08-30 09:26 UTC, GowthamShanmugam commented on packages/odf/components/kms-config/utils.tsx
> +        kmsObj.name.valid &&
ok

2022-08-30 09:39 UTC, SanjalKatiyar commented on packages/odf/types/kms.ts
> +  };
also, I forgot to mention... in Vault this `value` is of `SecretKind` where in Thales this `value` is of type `string`... that is one more difference...

2022-09-01 08:48 UTC, humblec commented
@GowthamShanmugam @bipuladh can you please review this in priority?

2022-09-01 08:52 UTC, GowthamShanmugam approved these changes

2022-09-01 10:32 UTC, merged