Application wise data policies status
red-hat-storage/odf-console pull request #390
Opened 2022-08-24 11:29 UTC by GowthamShanmugam

2022-08-24 11:35 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/186408378-db029f50-5356-4796-87d7-b335666eb327.png)
![image](https://user-images.githubusercontent.com/15073590/186408453-08ea6a6b-9927-414f-b928-011874cd949f.png)

2022-08-25 13:57 UTC, GowthamShanmugam commented
@bipuladh @SanjalKatiyar Please review

2022-08-25 17:38 UTC, SanjalKatiyar commented on packages/mco/utils/disaster-recovery.ts
> +  [placementRuleName in string]: string[];
nits: `[placementRuleName: string]: string[];`

2022-08-25 17:58 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
> +                  onClick={() => onClick(index)}
add `key` as well...

2022-08-25 19:29 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
> +        component: (props) => <DRPoliciesStatusTable drPolicies={props} />,
add `key` here as well...

2022-08-25 19:32 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +        drPolicyName in Object.keys(obj)
`drPolicyName in obj` or use `hasOwnProperty`...

2022-08-25 19:36 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +    namespace: namespace,
nits:
just pass `namespace` instead of `namespace: namespace`

2022-08-25 19:44 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +    );
we can combine these two `useMemo` into one and return two things simultaneous:
const [dataPoliciesStatus, count] = ... return [ {drPolicies: getDRPolicies(activeDRPC)}, count] ...

2022-08-25 20:09 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +        <DataPoliciesStatusModal {...{ isOpen, dataPoliciesStatus, close }} />
are we sure here that every time `DataPoliciesStatusPopover` is re-rendering this format is not creating a new object and changing the reference of props everytime ?? (actually I am little confused with this format of passing props, so confirming once)...

2022-08-25 20:12 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +        <DataPoliciesStatusModal {...{ isOpen, dataPoliciesStatus, close }} />
also, instead of managing your own `setOpen`, `close`, `onClick` fucntions in this component, can't we directly use modalLauncher hook ??

2022-08-25 20:17 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +    (arr, drPlacementControl) =>
accumulator here is not an array...

2022-08-25 20:26 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +      {getStatusSummary(t('Relocate'), statusSummary?.failover, t)}
it is not exactly wrong, but let's treat this as a FC rather than a function...
else React will treat it as a one large component instead of combination of multiple smaller components...

2022-08-25 20:27 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +      {getStatusSummary(t('Relocate'), statusSummary?.failover, t)}
we don't need to pass `t` function, `GetStatusSummary` can use its own hook...

2022-08-29 05:58 UTC, bipuladh requested changes

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
> +              {navItems.map((item, index) => (
Can't we directly render it as there is only one item in the array?

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +    }, [response, resource]);
Not going to work. You need to use `deepCompareMemoize` instead.

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +      <React.Fragment>
```suggestion
      <>
```

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +        <>
Shouldn't this be `FlexItem`?

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +        [].concat(...Object.values(drPolicies).map((policies) => policies))
Why is `concat`  used here? Are you trying to create a copy?

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/utils/disaster-recovery.ts
> +                : [getName(subscription)],
```suggestion
            [plsRuleName]:  [...(obj?.[plsRuleName] || {}), getName(subscription)]
```

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/utils/disaster-recovery.ts
> +export const filterDRPlacementRules = (
```suggestion
export const getfilteredDRPlacementRuleNames = (
```
The name of the function should match the action it is performing.

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/utils/disaster-recovery.ts
> +) => objectRefList?.includes(objectRef?.name);
```suggestion
): boolean => objectRefList?.includes(objectRef?.name);
```
nit: return type

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/types/common.ts
>          [key in string]: string;
```suggestion
        [key: string]: string;
```
please update this.

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
> +      <React.Fragment>
```suggestion
      <>
```
Use `React.Fragment` only when you need to pass key

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
> +        component: (props) => <DRPoliciesStatusTable drPolicies={props} />,
```suggestion
        component: DRPoliciesStatusTable,
```
Use this directly as `<component {...props}/>` where required.

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +  Object.keys(drPolicies || {})?.length;
I am not sure we should export a helper function from a Component file. Move it to a helpers file or do not export it.

2022-08-29 05:58 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +  [policyName in string]: DRPlacementControlKind[];
```suggestion
  [policyName: string]: DRPlacementControlKind[];
```

2022-08-29 11:43 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +        <DataPoliciesStatusModal {...{ isOpen, dataPoliciesStatus, close }} />
if the DR CR watch has any changes it will create dataPoliciesStatus. and it will render with a new object.

2022-08-29 11:45 UTC, SanjalKatiyar commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-popover.tsx
> +        <DataPoliciesStatusModal {...{ isOpen, dataPoliciesStatus, close }} />
I meant, say `dataPoliciesStatus` same so does DR CR, but parent component re-renders...
then ideally ref of `dataPoliciesStatus` in child `DataPoliciesStatusModal` should also remain same... but is it so by above de-structuring method ? that was my doubt...

2022-08-29 12:29 UTC, GowthamShanmugam commented on packages/mco/components/data-policies/app-data-policies-status/data-policies-status-modal.tsx
> +              {navItems.map((item, index) => (
Data policies are generic, under data policies we have only today, but in the future, we might add more. But i agreed for now we can keep logic without looping

2022-08-29 12:57 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +        [].concat(...Object.values(drPolicies).map((policies) => policies))
i am trying to merge multiple list to single list

2022-08-29 13:18 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/187210320-a76f5801-1392-46d2-bc4d-af844ccb8278.png)
![image](https://user-images.githubusercontent.com/15073590/187210389-d219ddc6-0658-42ed-94c5-13411e7192ae.png)

2022-08-29 13:24 UTC, GowthamShanmugam commented
@bipuladh @SanjalKatiyar changes done

2022-08-30 06:28 UTC, GowthamShanmugam commented
/retest

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +        <>
@GowthamShanmugam ^^?

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +    <React.Fragment>
```suggestion
    <>
```

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.tsx
> +};
nit
```suggestion
const getSortableRowValues = (drStatus: DRCurrentStatusType): string[] => [
    drStatus?.drPolicyName,
    drStatus?.lastSync,
    drStatus?.currentStatus?.text,
  ];
```

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.tsx
> +    'asc' | 'desc'
Use an enum here for `asc` and `desc`

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.tsx
> +        currentStatus: getDRStatus(getCurrentStatus(drPolicies[policyName])),
```suggestion
      Object.entries(drPolicies).map(([policyName, policyValue])) => ({
        drPolicyName: policyName,
        // TODO:Gowtham Once it is available on DRPC CR
        lastSync: '',
        recommenedAction: '',
        currentStatus: getDRStatus(getCurrentStatus(policyValue)),
```

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/utils/disaster-recovery.ts
> +export type SubcsriptionMap = {
```suggestion
export type SubscriptionMap = {
```

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/utils/disaster-recovery.ts
> +export type DRPoliciesType = {
```suggestion
export type DRPolicyMap = {
```

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.tsx
> +import { DRPlacementControlKind } from 'packages/mco/types';
```suggestion
import { DRPlacementControlKind } from 'packages/mco/types';
```
This import looks wrong to me.

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-card.tsx
> +}>;
```suggestion
export type DRStatusSummaryType = {
  relocate?: DRStatusSummaryCountType;
  failover?: DRStatusSummaryCountType;
};
```
nit

2022-09-01 12:48 UTC, bipuladh commented on packages/mco/components/disaster-recovery/application-dr-status/dr-status-table.tsx
> +      : newStatus;
```suggestion
    return [DRPC_STATUS.Relocating, DRPC_STATUS.FailingOver].includes(newStatus)
        ? newStatus
        : prevStatus || newStatus;
```
Reading multiple ternary operators is hard. Would the above suggestion be sufficient to achieve the original logic?

2022-09-01 14:17 UTC, SanjalKatiyar commented
/approve
/lgtm

2022-09-01 15:19 UTC, merged