Bug: 2115037: Text correction in DR policy creation
red-hat-storage/odf-console pull request #396
Opened 2022-09-02 12:05 UTC by TimothyAsirJeyasing

Signed-off-by: Timothy Asir <tjeyasin@redhat.com>

2022-09-02 12:05 UTC, TimothyAsirJeyasing commented
@bipuladh , @SanjalKatiyar Please review

2022-09-02 12:25 UTC, SanjalKatiyar commented
/retitle Bug 2115037: Text correction in DR policy creation

2022-09-05 06:00 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "Enables mirroring/replication between the two selected clusters and ensures failover or relocate from primary cluster to secondary cluster in the event of an outage or planned maintenance.": "Enab
Is UX is already reviewed this?

2022-09-05 07:35 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "Enables mirroring/replication between the two selected clusters and ensures failover or relocate from primary cluster to secondary cluster in the event of an outage or planned maintenance.": "Enab
@TimothyAsirJeyasing please ping Chandan once and confirm with him...

2022-09-05 07:35 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-09 08:24 UTC, TimothyAsirJeyasing commented on locales/en/plugin__odf-console.json
> +  "Enables mirroring/replication between the two selected clusters and ensures failover or relocate from primary cluster to secondary cluster in the event of an outage or planned maintenance.": "Enab
chandkum@redhat.com Please review

2022-09-09 08:30 UTC, Chandan141996 requested changes
@TimothyAsirJeyasing @GowthamShanmugam 
I would suggest changing the description text to: 
Enables mirroring/replication between two selected clusters, ensuring failover or relocation between the two clusters in the event of an outage or planned maintenance.

2022-09-13 07:10 UTC, GowthamShanmugam approved these changes

2022-09-13 07:11 UTC, SanjalKatiyar commented
/approve

2022-09-13 08:51 UTC, merged