Bug fix on failover and relocate modal
red-hat-storage/odf-console pull request #409
Opened 2022-09-09 11:12 UTC by GowthamShanmugam

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

2022-09-09 11:12 UTC, GowthamShanmugam commented
![image](https://user-images.githubusercontent.com/15073590/189337566-cd8c2c4c-8f1a-4d05-88ad-e5a520685e76.png)

2022-09-09 12:51 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/app-dr-status/dr-status-table.tsx
>        : acc;
this is doing anything, I mean `: acc` part of ternary condition... either we can change it to `: null` or something like
```
if (status === currentStatus) {
    ([DRPC_STATUS.Relocating, DRPC_STATUS.Relocated].includes(status) &&
          acc.add(drpc?.spec?.preferredCluster)) ||
    ([DRPC_STATUS.FailingOver, DRPC_STATUS.FailedOver].includes(status) &&
          acc.add(drpc?.spec?.failoverCluster))
}
return acc;
```

2022-09-09 13:06 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
>    obj.peerReadiness.text !== PEER_READINESS.PEER_NOT_READY
so I have a doubt, `obj.peerReadiness.text` contains translated string... but `PEER_READINESS.PEER_NOT_READY` this is not translated... so in case user changes browser's language, this will always be true... is that okay ?

2022-09-09 13:11 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
>      : obj.peerReadiness;
also, instead of always looping over entire list (we are using `reduce` currently in `getPeerStatusSummary`), we can return as soon as we find very first instance of DRPC which is not Ready... we can try to use `every`...

2022-09-09 13:25 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
>      : obj.peerReadiness;
may not be required in this PR, just a suggestion...

2022-09-09 13:42 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
>      : obj.peerReadiness;
getPeerStatusSummary has a reduced becuase, we need to makesure all ready from the subscription groups are all matching with selected DRPolicy.

So there is some subgroup that can have non-matching DRPolicy name also, we need to find all matching first and makesure all matching are peer ready.

also, we need to find the last lastHealthCheck which is from a subs group that has recent health check time, and also recent lastSnapshotTakenOn time.

All three can come from different subs groups also. so we need to loop through all

2022-09-09 13:45 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/app-failover-relocate/peer-cluster-status.tsx
>      : obj.peerReadiness;
first one loop through all and make sure all peers are ready,
the second  loop through all and fetch which has the least last health check.
third loop through all and fetch which has the least last lastSnapshotTakenOn.

single complete  looping will cover all above three cases.

2022-09-09 13:47 UTC, GowthamShanmugam commented
@SanjalKatiyar Changes done

2022-09-12 07:00 UTC, bipuladh requested changes

2022-09-12 07:00 UTC, bipuladh commented on packages/mco/utils/disaster-recovery.ts
>  export const findPeerCondition = (drPolicyControl: DRPlacementControlKind) =>
Shouldn't this function name be `isPeerReady`? `findPeerCondition` should return a condition as per the name.

2022-09-12 08:23 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/app-failover-relocate/subscription-group-selector.tsx
> +                        ],
Under valid options:
    yes order matters, all options with valid peer status will be checked by default, and invalid will be unchecked. I need all checked should be displayed first and unchecked will be displayed last.

Under invalid options:
   all disabled.

2022-09-12 09:27 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/app-failover-relocate/subscription-group-selector.tsx
> +          setOptions(allOptions);
I am converting all options object to list, which will have all valid option on top and invalid options at the end

2022-09-12 09:32 UTC, GowthamShanmugam commented on packages/mco/utils/disaster-recovery.ts
>  export const findPeerCondition = (drPolicyControl: DRPlacementControlKind) =>
yes

2022-09-12 10:24 UTC, bipuladh commented
/lgtm

2022-09-12 10:24 UTC, bipuladh commented
/approve

2022-09-12 15:01 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-09-12 18:35 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2022-09-12 20:06 UTC, merged