update ODF version to 4.11 - CI
red-hat-storage/odf-console pull request #430
Opened 2022-09-26 13:21 UTC by SanjalKatiyar

2022-09-26 15:04 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-27 17:49 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-27 19:51 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-28 04:40 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-28 05:36 UTC, vbnrh requested changes

2022-09-28 05:36 UTC, vbnrh commented on packages/odf/components/namespace-store/namespace-store-form.tsx
> +          data-test="namespacestore-provider"
i dont see this id being passed down to the dropdown ?

2022-09-28 05:38 UTC, SanjalKatiyar commented on packages/odf/components/namespace-store/namespace-store-form.tsx
> +          data-test="namespacestore-provider"
it will... check https://github.com/red-hat-storage/odf-console/pull/430/files/e7661c08b9183c95a4ff4d94fdbcf20b6c50d7d5#diff-8adfa67001c080b994ad6e8cc465b3263a9dcd9459dcafe0ff68d81ce08fc395 StaticDropdown.tsx

2022-09-29 05:44 UTC, bipuladh commented
/lgtm

2022-09-29 07:39 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-29 09:28 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-29 10:01 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-29 10:18 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-09-29 10:19 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-09-29 11:17 UTC, SanjalKatiyar commented
/lgtm cancel
updating ODF to 4.12 instead of 4.11

2022-09-29 14:56 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-09-30 04:42 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-09-30 04:42 UTC, bipuladh commented
/lgtm

2022-09-30 04:44 UTC, merged

2022-09-30 07:16 UTC, SanjalKatiyar commented
/cherry-pick release-4.12

2022-09-30 07:16 UTC, SanjalKatiyar commented
/cherry-pick release-4.12-compatibility