fix: moved getAlertsAndRules inside of useAlerts hook
red-hat-storage/odf-console pull request #441
Opened 2022-09-28 11:39 UTC by debjyoti-pandit

fixes: https://github.com/red-hat-storage/odf-console/issues/368

2022-09-28 11:42 UTC, debjyoti-pandit commented
/assign @GowthamShanmugam
/assign @bipuladh
/assign @SanjalKatiyar

2022-09-28 13:24 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-09-28 16:03 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-09-29 05:57 UTC, bipuladh commented
To be merged after branch cut.
/hold

2022-10-03 12:00 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-10-04 07:23 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2022-10-06 07:32 UTC, bipuladh commented on packages/shared/monitoring/useAlert.ts
> +export type PrometheusRulesResponse = {
```suggestion
type PrometheusRulesResponse = {
```

2022-10-06 08:02 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-10-06 12:00 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-10-07 07:59 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-10-10 07:27 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-10-11 11:14 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-10-13 11:59 UTC, bipuladh requested changes

2022-10-13 11:59 UTC, bipuladh commented on locales/en/plugin__odf-console.json
> +  "No Limit": "No Limit",
Where is this coming from?

2022-10-13 12:23 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "No Limit": "No Limit",
got missed here: https://github.com/red-hat-storage/odf-console/pull/414
we can think about having some precommit check/CI build check for i18n as well...

2022-10-13 17:38 UTC, debjyoti-pandit commented on locales/en/plugin__odf-console.json
> +  "No Limit": "No Limit",
It is gone, as I rebase it with the master branch. 
I agree with @SanjalKatiyar regarding adding a check in the CI as it shouldn't get missed.

2022-10-17 08:23 UTC, GowthamShanmugam commented on packages/shared/monitoring/useAlert.ts
>      endpoint: 'api/v1/rules' as any,
replace 'api/v1/rules'  with PrometheusEndpoint.RULES

2022-10-17 10:32 UTC, GowthamShanmugam commented on packages/shared/monitoring/useAlert.ts
> +  const groups = (data as unknown as PrometheusRulesResponse)?.data?.groups;
usePrometheusBasePath is always returning ProemetheusResponse type and converting to PrometheusRulesResponse type is not make much sense.

instead, convert the useCustomPrometheusPoll to receive the interface type.

```
import {
  DEFAULT_PROMETHEUS_SAMPLES,
  DEFAULT_PROMETHEUS_TIMESPAN,
  PrometheusEndpoint,
} from '@odf/shared/constants';
import { PrometheusResponse, PrometheusRule } from '@openshift-console/dynamic-plugin-sdk';
import { getPrometheusURL } from './helpers';
import { useURLPoll, } from './use-url-poll';

type CustomPrometheusResponse = PrometheusResponse | PrometheusRulesResponse;

type CustomPrometheusPollProps = {
  delay?: number;
  endpoint: PrometheusEndpoint;
  endTime?: number;
  namespace?: string;
  query: string;
  samples?: number;
  timeout?: string;
  timespan?: number;
  basePath?: string;
  cluster?: string;
};

type UseCustomPrometheusPoll = <P extends CustomPrometheusResponse>(
  props: CustomPrometheusPollProps
) => [P, any, boolean];

type Group = {
  rules: PrometheusRule[];
  file: string;
  name: string;
};

type PrometheusRulesResponse = {
  data: {
    groups: Group[];
  };
  status: string;
};


export const useCustomPrometheusPoll: UseCustomPrometheusPoll = <P extends CustomPrometheusResponse>({
  delay,
  endpoint,
  endTime,
  namespace,
  query,
  samples = DEFAULT_PROMETHEUS_SAMPLES,
  timeout,
  timespan = DEFAULT_PROMETHEUS_TIMESPAN,
  basePath,
  cluster,
}) => {
  const url = !!basePath
    ? getPrometheusURL(
        { endpoint, endTime, namespace, query, samples, timeout, timespan },
        basePath
      )
    : getPrometheusURL({
        endpoint,
        endTime,
        namespace,
        query,
        samples,
        timeout,
        timespan,
      });

  return useURLPoll<P>(url, delay, cluster, query, timespan);
};

```

2022-10-17 10:33 UTC, GowthamShanmugam commented on packages/shared/monitoring/useAlert.ts
> +  const groups = (data as unknown as PrometheusRulesResponse)?.data?.groups;
just invoking useCustomPrometheusPoll<PrometheusResonse> (or) useCustomPrometheusPoll<PrometheusRuleResonse> will takecare of the response type.

2022-10-18 06:55 UTC, GowthamShanmugam commented on packages/shared/monitoring/useAlert.ts
> +  const groups = (data as unknown as PrometheusRulesResponse)?.data?.groups;
@bipuladh Is this change too much or useful?

2022-11-08 09:41 UTC, bipuladh approved these changes
/lgtm

2022-11-08 09:41 UTC, bipuladh commented on packages/shared/monitoring/useAlert.ts
> +  const groups = (data as unknown as PrometheusRulesResponse)?.data?.groups;
I like this suggestion. Let's create a different issue for this.

2022-11-08 09:43 UTC, bipuladh commented
/test ci/prow/odf-console-e2e-aws

2022-11-08 09:44 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-11-08 11:46 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-11-14 02:36 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-11-14 03:29 UTC, bipuladh commented
/lgtm

2022-11-14 10:02 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-12-05 11:13 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-12-05 13:49 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-12-05 16:06 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-12-05 20:38 UTC, merged