patch pull-secret in openshift-config namespace
red-hat-storage/odf-console pull request #457
Opened 2022-10-02 11:55 UTC by SanjalKatiyar

2022-10-03 05:13 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-10-03 06:48 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-10-03 09:58 UTC, alfonsomthd commented
/assign @bipuladh

2022-10-03 09:59 UTC, alfonsomthd commented
@SanjalKatiyar Can yo ucheck this error log?
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/red-hat-storage_odf-console/457/pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws/1576857661092139008/artifacts/odf-console-e2e-aws/tests/build-log.txt

2022-10-03 10:10 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-10-03 10:11 UTC, SanjalKatiyar commented
> @SanjalKatiyar Can you please check this error log? https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/red-hat-storage_odf-console/457/pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws/1576857661092139008/artifacts/odf-console-e2e-aws/tests/build-log.txt

catalog was still connecting, hence CSV was never created.

2022-10-03 13:33 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-10-03 15:54 UTC, bipuladh commented
/approve
/lgtm

2022-10-03 15:54 UTC, bipuladh commented
/hold

2022-10-03 15:58 UTC, bipuladh requested changes

2022-10-03 15:58 UTC, bipuladh commented on test-prow-e2e.sh
> +PULL_SECRET="cmhvY3MtZW5nOjhRZVUvbDdqL0lLTk9aMEtidU5OYVlHbjdWUmNnVkxlMURrODB2OUhza05VMk4rSWZtNGYxYmJDQVZZMHJObks="
I guess we can remove this.

2022-10-03 15:58 UTC, bipuladh commented on test-prow-e2e.sh
> +  jq -c '.auths."quay.io".auth = "'${PULL_SECRET}'"' secret.json > temp-auth.json
are we passing `PULL_SECRET` as env var?

2022-10-03 16:06 UTC, bipuladh approved these changes

2022-10-03 16:06 UTC, bipuladh commented
/lgtm
/hold cancel

2022-10-03 16:26 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-10-03 16:34 UTC, merged

2022-10-04 07:10 UTC, SanjalKatiyar commented
/cherry-pick release-4.12

2022-10-04 07:10 UTC, SanjalKatiyar commented
/cherry-pick release-4.12-compatibility

2022-10-11 07:25 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

On Mon, 3 Oct 2022, 00:14 openshift-ci[bot], ***@***.***>
wrote:

> @SanjalKatiyar <https://github.com/SanjalKatiyar>: The following test
> *failed*, say /retest to rerun all failed tests or /retest-required to
> rerun all mandatory failed tests:
> Test name Commit Details Required Rerun command
> ci/prow/odf-console-e2e-aws 2922e12
> <https://github.com/red-hat-storage/odf-console/commit/2922e12891ad2aeb8020d173c59430def3db3710>
> link
> <https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/red-hat-storage_odf-console/457/pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws/1576622614124695552>
> true /test odf-console-e2e-aws
>
> Full PR test history
> <https://prow.ci.openshift.org/pr-history?org=red-hat-storage&repo=odf-console&pr=457>.
> Your PR dashboard
> <https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:SanjalKatiyar>
> .
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/red-hat-storage/odf-console/pull/457#issuecomment-1264708068>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJMUIYPNLOODG7VNIYL7DVLWBHJ2DANCNFSM6AAAAAAQ235ODE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>