Cleanup: enable no-extraneous-dependencies & no-unused-imports
red-hat-storage/odf-console pull request #466
Opened 2022-10-04 14:51 UTC by alfonsomthd

Signed-off-by: Alfonso Martínez <almartin@redhat.com>

2022-10-04 15:19 UTC, alfonsomthd commented
/test odf-console-e2e-aws

2022-10-05 06:36 UTC, alfonsomthd commented
/assign @bipuladh

2022-10-05 21:46 UTC, SanjalKatiyar commented on package.json
> +    "@openshift-console/dynamic-plugin-sdk": "0.0.15",
it is actually a dev-dependency, it only have types required by the modules, actual components are still served by OCP during runtime...

2022-10-05 22:32 UTC, SanjalKatiyar commented on package.json
> +  ],
instead of here, shouldn't we add `bundleDependencies` to the respective package's  `package.json` file ?? root itself is a mono-repo...

2022-10-05 22:39 UTC, SanjalKatiyar commented on package.json
> +  ],
also, do we even need this ?? I don't think we will ever publish mco/ocs/odf package. We can publish shared package if ever required, but that is independent of any other package. Is there any use case I maybe missing ??

2022-10-06 03:41 UTC, bipuladh requested changes

2022-10-06 03:41 UTC, bipuladh commented on cypress/helpers/add-capacity.ts
> +import * as _ from 'lodash-es';
Rather than doing this. Let's replace all module usage of `lodash` with `lodash-es` in webpack.

2022-10-06 03:41 UTC, bipuladh commented on .eslintrc.js
> +  plugins: ['react', '@typescript-eslint', 'import', 'unused-imports'],
`@typescript-eslint` should have `unused-imports` rules.

2022-10-06 03:41 UTC, bipuladh commented on package.json
> +  "bundleDependencies": [
I do not see this required for us as we are not going to publish it to npmjs.

2022-10-06 03:41 UTC, bipuladh commented on package.json
> +    "redux": "^4.0.0",
Why `redux`?

2022-10-06 03:41 UTC, bipuladh commented on package.json
> +    "victory-core": "^35.4.4"
Why `victory core`?

2022-10-06 03:41 UTC, bipuladh commented on package.json
> +    "js-yaml": "^3.13.1",
Why these packages?

2022-10-06 03:41 UTC, bipuladh commented on package.json
> +    "@openshift-console/dynamic-plugin-sdk": "0.0.15",
Lets keep it as `devDependency` it only exposes types.

2022-10-06 06:31 UTC, alfonsomthd commented on cypress/helpers/add-capacity.ts
> +import * as _ from 'lodash-es';
Is that not a dirty trick? IMHO is better to have the correct imports than to do a trick in webpack....

2022-10-06 06:34 UTC, alfonsomthd commented on package.json
> +  "bundleDependencies": [
This is only to tell the linter that the imports from @odf/shared are inside the project.

2022-10-06 06:37 UTC, bipuladh commented on cypress/helpers/add-capacity.ts
> +import * as _ from 'lodash-es';
IMO we will keep on missing this during reviews and people will definitely keep on messing the package name. Doing that would make sure we always use es modules.

2022-10-06 06:37 UTC, alfonsomthd commented on package.json
> +    "redux": "^4.0.0",
It's being imported here:
https://github.com/red-hat-storage/odf-console/blob/master/packages/ocs/dashboards/persistent-internal/raw-capacity-card/raw-capacity-card.tsx#L8

2022-10-06 06:38 UTC, bipuladh commented on package.json
> +  "bundleDependencies": [
Doesn't linter also lint code on `@odf/shared`? I am not sure how we are helping linter with this directive.

2022-10-06 06:40 UTC, alfonsomthd commented on package.json
> +    "js-yaml": "^3.13.1",
Because there are explicit imports like in:
packages/shared/utils/SecretValue.tsx
packages/shared/yaml-editor/YAMLEditor.tsx

2022-10-06 06:42 UTC, alfonsomthd commented on package.json
> +  ],
This is only to tell the linter that the imports from @odf/shared are inside the project.

2022-10-06 06:44 UTC, alfonsomthd commented on .eslintrc.js
> +  plugins: ['react', '@typescript-eslint', 'import', 'unused-imports'],
I'll look at it!

2022-10-06 06:45 UTC, alfonsomthd commented on package.json
> +    "victory-core": "^35.4.4"
It's being imported:
packages/shared/charts/tooltip.tsx

2022-10-06 06:51 UTC, alfonsomthd commented on cypress/helpers/add-capacity.ts
> +import * as _ from 'lodash-es';
This approach defeats the purpose of the `no-extraneous-dependencies` which forbids imports not declared...

2022-10-06 10:21 UTC, alfonsomthd commented on package.json
> +    "@openshift-console/dynamic-plugin-sdk": "0.0.15",
Addressed.

2022-10-06 10:26 UTC, alfonsomthd commented on package.json
> +  "bundleDependencies": [
I updated the linter config so we no longer require this.

2022-10-06 10:27 UTC, alfonsomthd commented on package.json
> +    "@openshift-console/dynamic-plugin-sdk": "0.0.15",
Done.

2022-10-06 10:51 UTC, alfonsomthd commented on cypress/helpers/add-capacity.ts
> +import * as _ from 'lodash-es';
As per our previous chat conversation, we agree on using the imports from our dependencies.
The linter will throw an error if someone tries to import from a non-existing dependency so the pre-commit and PR checks will fail.

2022-10-06 10:54 UTC, alfonsomthd commented
/test odf-console-e2e-aws

2022-10-06 12:37 UTC, alfonsomthd commented
/test odf-console-e2e-aws

2022-10-07 08:05 UTC, bipuladh approved these changes
/lgtm

2022-10-07 08:06 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-10-07 12:38 UTC, merged