fix: made wizard body height fixed to avoid outte scroll
red-hat-storage/odf-console pull request #481
Opened 2022-10-11 10:16 UTC by debjyoti-pandit

fixes: https://issues.redhat.com/browse/RHSTOR-2161

2022-10-11 10:17 UTC, debjyoti-pandit commented
/assign @SanjalKatiyar 
/assign @bipuladh

2022-10-11 11:14 UTC, bipuladh commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
> +    <Form className="odf-capacity-and-node-form">
Why not on the wizard?

2022-10-11 11:16 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
> +    <Form className="odf-capacity-and-node-form">
Wizard is common for all the screens, I thought the one which is causing the issue can have custom height.

2022-10-11 12:49 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2022-10-13 11:58 UTC, bipuladh requested changes

2022-10-13 11:58 UTC, bipuladh commented on packages/odf/components/create-storage-system/create-storage-system.scss
> +  max-height: 60vh;
Is this the max we can go? we should be able to go more? Also please do not override PF class instead pass a className to Wizard and use that here.

2022-10-17 07:09 UTC, GowthamShanmugam commented on packages/odf/components/create-storage-system/create-storage-system.scss
> +  max-height: 66vh;
cc: @bipuladh @SanjalKatiyar Please take a look this CSS change

2022-10-18 12:33 UTC, SanjalKatiyar commented
can you try once by zooming the tab to around 125-150% and see if it is still working as expected ??

2022-10-18 17:58 UTC, debjyoti-pandit commented
> can you try once by zooming the tab to around 125-150% and see if it is still working as expected ??

Did try with increasing it to 110%. There was 2 scroll bar. Increasing it to 125% will definitely add one extra scroll bar.
If we want to remove the extra scroll bar when in 110% then we have to reduce the height to 60vh which I initially had. I was also considering it.

But the point, it are we going to support 110%. If yes then we should also plan for 125%. In that case, we have to reduce it to 54vh.

Let me know about this. 

In my opinion, we can develop based on 100% as we can control how much % of users we see in their browser.

2022-10-19 06:31 UTC, debjyoti-pandit commented
@SanjalKatiyar If we need to support 150% then it will look as below 

![image](https://user-images.githubusercontent.com/22158580/196613905-ac98daaf-d77e-43f5-80c3-34f84b57edb3.png)

The footer and the heading is also increasing when we are increasing the zoom level. Which is bringing the scrollbar.

2022-12-05 11:15 UTC, bipuladh commented
/approve
/lgtm

2022-12-05 12:15 UTC, bipuladh commented
/hold cancel

2022-12-05 13:44 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-12-07 10:06 UTC, merged