Add documentation links for ceph-based alerts
red-hat-storage/odf-console pull request #496
Opened 2022-10-17 06:29 UTC by rexagod

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

2022-10-17 06:31 UTC, bipuladh requested changes
Need to perform similar check for Noobaa.

2022-10-17 06:31 UTC, bipuladh commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            documentationLink={alert?.annotations?.storage_type === "ceph" ? `https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.12/html-single/troubleshooting_openshif
Decompose this to multiple functions. One to  generate the alert link other to verify its a ceph storage_type. And one more which takes those two functions and either passes documentationLink or `undefined`

2022-10-17 07:40 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +  };
let's move generateDocumentationLink and getDocumentationLink outside the FC.

2022-10-17 07:47 UTC, rexagod commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            documentationLink={alert?.annotations?.storage_type === "ceph" ? `https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.12/html-single/troubleshooting_openshif
ACK.

2022-10-17 07:47 UTC, rexagod commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +  };
Done.

2022-11-07 13:47 UTC, rexagod commented
@bipuladh Do you know when is the next dynamic SDK release queued for (as we want https://github.com/openshift/console/pull/12059/files to be there in the SDK for this merge to happen)? Should I ask Sam to accelerate the process, if possible, so that we can do this before freeze? Or, since this is only on our end now (console-side PR is in) can we wait for the release to happen without the need to push the console team?

2022-11-09 06:38 UTC, bipuladh commented
@rexagod lets get this merged.

2022-11-09 11:38 UTC, rexagod commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            // @ts-ignore
@bipuladh I think we can go ahead with the merge now.

2022-11-09 11:38 UTC, rexagod commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            // @ts-ignore
cc @SanjalKatiyar

2022-11-09 11:59 UTC, SanjalKatiyar commented
need to run "yarn format", looks like "lint-staged" working as intended...

2022-11-09 12:00 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            // @ts-ignore
just to be sure, did u test it once on latest OCP ?

2022-11-10 14:21 UTC, rexagod commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            // @ts-ignore
Getting this on OCP 4.10.

<details>
<summary>Dashboard</summary>


![image](https://user-images.githubusercontent.com/33557095/201112163-6f34f4e6-42dd-4232-84e1-2380ccc324e4.png)


</details>

2022-11-10 15:35 UTC, rexagod commented on packages/ocs/dashboards/persistent-internal/status-card/status-card.tsx
> +            // @ts-ignore
On OCP 4.10 (tested with `console` on r-4.10 and master) on this PR, I'm getting this. Not sure why https://github.com/openshift/console/pull/11976 isn't being picked up as this is in `console#master` already, maybe something's disabling it? Last time I checked this feature, I used 4.12, so maybe it's probable that 4.10 could be blocking it?

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/33557095/201124125-fd3eb7b0-03ff-4c20-b248-959251d19315.png)

</details>

2022-11-11 11:04 UTC, rexagod commented
Verified.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/33557095/201327414-7db1c028-3529-48af-8490-4f22cbe35418.png)
![image](https://user-images.githubusercontent.com/33557095/201327459-f4d2fd91-1c02-4d74-b39d-e4e43cb4b862.png)
![Screenshot from 2022-11-11 16-34-05](https://user-images.githubusercontent.com/33557095/201327511-2db4b9f5-3f19-43d4-8195-a1fa17543ae6.png)

</details>

2022-11-11 11:05 UTC, rexagod commented
/test odf-console-e2e-aws

2022-11-14 06:28 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-11-14 06:28 UTC, SanjalKatiyar commented
/cherry-pick release-4.12

2022-11-14 06:29 UTC, SanjalKatiyar commented
/cherry-pick release-4.12-compatibility

2022-11-14 12:44 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-11-14 14:43 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-11-14 17:05 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-11-14 18:55 UTC, rexagod commented
/test odf-console-e2e-aws

2022-11-15 06:15 UTC, SanjalKatiyar commented
/approve
/lgtm

2022-11-15 08:24 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-11-15 10:34 UTC, merged