add custom extension for external vendor
red-hat-storage/odf-console pull request #557
Opened 2022-12-08 08:44 UTC by SanjalKatiyar

![Screenshot from 2022-12-08 13-52-29](https://user-images.githubusercontent.com/39404641/206399117-979549a1-6332-4af2-826e-d05159fb8999.png)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**External Ceph Storage:**
![Screenshot from 2022-12-08 13-54-04](https://user-images.githubusercontent.com/39404641/206399124-02f4cc45-b6fc-4f77-98e5-9b82128793bb.png)
![Screenshot from 2022-12-08 13-54-21](https://user-images.githubusercontent.com/39404641/206399126-a8966873-e4c9-43d7-89b9-786f7607516c.png)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**External Storage Vendor (non-ceph):**
![Screenshot from 2022-12-08 13-54-50](https://user-images.githubusercontent.com/39404641/206399131-51059125-ed30-4984-82f6-831077ea4c3d.png)
![Screenshot from 2022-12-08 14-03-25](https://user-images.githubusercontent.com/39404641/206399139-ed26bdb2-c835-41f1-88bd-893395a76a81.png)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**External Storage Vendor (non-ceph) when RHCS already exists on cluster:**
![Screenshot from 2022-12-08 14-04-34](https://user-images.githubusercontent.com/39404641/206399145-5efab35c-6416-4e57-9e6e-117abaec9837.png)
![Screenshot from 2022-12-08 14-06-51](https://user-images.githubusercontent.com/39404641/206399149-5b9e04a2-386a-4061-a949-020b9dbcc689.png)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2022-12-12 12:08 UTC, GowthamShanmugam commented on packages/external-storage/index.tsx
> +} from '@odf/external/external-system-types';
Let's create a proper directly called component and place this file like ibm-external-storage.tx

2022-12-12 12:09 UTC, GowthamShanmugam commented on packages/external-storage/index.tsx
> +} from '@odf/shared/plugin-custom-extensions/properties/storageClassStepProps';
Rename plugin-custom-extensions to custom-extensions

2022-12-13 04:36 UTC, bipuladh requested changes

2022-12-13 04:36 UTC, bipuladh commented on packages/external-storage/external-system-types.ts
> +import { K8sResourceCommon } from '@openshift-console/dynamic-plugin-sdk';
Let's rename the package as IBM. Eventually to be moved to IBM repo.

2022-12-13 04:36 UTC, bipuladh commented on packages/external-storage/index.tsx
>  import {
The filename really doesn't reflect the intent of the file. Index files should be exporting all the files from that dir.

2022-12-13 04:36 UTC, bipuladh commented on packages/external-storage/package.json
> +  "name": "@odf/external",
```suggestion
  "name": "@odf/ibm",
```

2022-12-13 04:36 UTC, bipuladh commented on packages/odf/components/create-storage-system/external-storage/README.md
> -### Contributing to the ODF UI:
We should move this files to extensions.

2022-12-13 04:36 UTC, bipuladh commented on packages/shared/plugin-custom-extensions/extensions/ExternalStorage.ts
> +import {
Extensions should be a package of its own.

2022-12-13 13:27 UTC, SanjalKatiyar commented on packages/external-storage/package.json
> +    "@odf/core": "0.0.0"
done...

2022-12-13 13:41 UTC, SanjalKatiyar commented on packages/external-storage/external-system-types.ts
> +export type FlashSystemState = {
all IBM related types they will handle and all ODF related types we will handle in our code...
since IBM will be moving this entire package to their repo, so all the common exports from "shared" package, they will have to add them to their repo as well (it won't be too much)...

2022-12-13 13:43 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/external-storage/README.md
> -### Contributing to the ODF UI:
ack !

2022-12-13 13:44 UTC, SanjalKatiyar commented on packages/shared/plugin-custom-extensions/extensions/ExternalStorage.ts
> +import {
Had a discussion with @GowthamShanmugam, he suggested to have separate "custom-extensions" directory for "mco" and "odf".
So that all MCO related extensions (maybe we introduce in future) can be added under "packages/mco/custom-extensions" and all ODF related under "packages/odf/custom-extensions".

what do u suggest should we do ?? cc @bipuladh

2022-12-13 13:44 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/payloads.ts
> -
true this could be temporary change (that is why I have added it as an optional property for the extension...
but what I was thinking was: we can let consumer of the extension decide whatever resources they wants to create (which could be specific to their operators and unrelated to ODF) and UI will wait for them to get created and once done we will redirect to system-list page (as normal)...
no need to add any check related to IBM in our ODF code !!

cc @bipuladh @GowthamShanmugam please let me know your thoughts on this...

2022-12-13 13:44 UTC, SanjalKatiyar commented on packages/shared/plugin-custom-extensions/extensions/ExternalStorage.ts
> +  StorageClassStepProps
So, right now we are injecting UI specifically to "Create Storage Class" step of wizard flow, hence the name `odf.wizard/storageclass`... in future lets say we want to add new extension for injecting UI to say "Review and create" step then we can call our extension `odf.wizard/reviewCreate` and so on...

`ExternalStorage.ts` file will export all such extension declarations related to wizard flow steps.

accordingly I have named `storageClassStepProps.ts` file, which contains corresponding extension definition for storage class step... in future if we add new extension we can add separate property file for that under properties directory.

Please let me know if it does not look good ?? cc @GowthamShanmugam @bipuladh

2023-01-13 09:00 UTC, bipuladh commented on packages/shared/plugin-custom-extensions/extensions/ExternalStorage.ts
> +import {
we should have a `packages/extensions` package.

2023-01-13 09:28 UTC, bipuladh commented on packages/shared/plugin-custom-extensions/extensions/ExternalStorage.ts
> +  StorageClassStepProps
`odf.install/wizard/storagelcass` wizard is too generic of a name. We should generate schemas to make things easier for end users.

2023-01-13 09:28 UTC, bipuladh commented on packages/external-storage/external-system-types.ts
> +import { K8sResourceCommon } from '@openshift-console/dynamic-plugin-sdk';
These should be part of `packages/extensions/types` folder.

2023-01-13 09:42 UTC, alfonsomthd commented on packages/shared/custom-extensions/properties/StorageClassWizardStepProps.ts
> +  /** A function returing a promise, resolving any resources which should be created (if any) before creation of external sub-system */
```suggestion
  /** A function returning a promise, resolving any resources which should be created (if any) before creation of external sub-system */
```

2023-01-13 09:43 UTC, alfonsomthd commented on packages/ibm/package.json
> +  "description": "IBM External Storage Platfrom",
```suggestion
  "description": "IBM External Storage Platform",
```

2023-03-09 09:24 UTC, SanjalKatiyar commented
closing this PR as have raised another one: https://github.com/red-hat-storage/odf-console/pull/676

2023-03-09 09:24 UTC, closed without merging