CSV Chores
red-hat-storage/odf-console pull request #59
Opened 2021-10-20 06:17 UTC by rexagod

Increase timeout, replace csv by subscription, and check CatalogSource
readiness.

2021-10-20 06:45 UTC, bipuladh commented on test-prow-e2e.sh
> +timeout 15m bash <<-'EOF'
Poll rather than arbitrary waits.

2021-10-20 07:01 UTC, vbnrh commented on test-prow-e2e.sh
> +timeout 15m bash <<-'EOF'
@bipuladh Like pranshu mentioned . It is an upper limit to avoid endless waits

2021-10-20 07:15 UTC, vbnrh requested changes

2021-10-20 07:15 UTC, vbnrh commented on test-prow-e2e.sh
> +done
Move this to the top. This needs to be checked at the start

2021-10-20 07:15 UTC, vbnrh commented on test-prow-e2e.sh
> +export ODF_CSV_NAME="$(oc get subscription -n openshift-storage -o=jsonpath='{.items[?(@.metadata.name=="odf-operator")].status.installedCSV}')"
This needs another wait. It won't be populated initially

2021-10-20 10:30 UTC, rexagod commented on test-prow-e2e.sh
> +export ODF_CSV_NAME="$(oc get subscription -n openshift-storage -o=jsonpath='{.items[?(@.metadata.name=="odf-operator")].status.installedCSV}')"
Added wait here: https://github.com/red-hat-storage/odf-console/pull/59/files#diff-bf3590087e59ba96ab84c865a37047c28148e7cc0139d06de34ca53a282b0642R24

2021-10-20 10:31 UTC, rexagod commented on test-prow-e2e.sh
> +done
Moved here: https://github.com/red-hat-storage/odf-console/pull/59/files#diff-bf3590087e59ba96ab84c865a37047c28148e7cc0139d06de34ca53a282b0642R21

2021-10-21 05:33 UTC, bipuladh commented on test-prow-e2e.sh
> +timeout 15m bash <<-'EOF'
okay!

2021-10-21 05:41 UTC, vbnrh requested changes

2021-10-21 05:41 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get catalogsource -n openshift-storage -o yaml > ${ARTIFACT_DIR}/catalogsource.yaml
```suggestion
  oc get catalogsource -n openshift-storage -o yaml > ${ARTIFACT_DIR}/catalogsource.yaml
```
```suggestion
  oc get catalogsource -n openshift-storage -o yaml >> ${ARTIFACT_DIR}/catalogsource.yaml
```
for appending

2021-10-21 05:41 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get installplan -n openshift-storage -o yaml > ${ARTIFACT_DIR}/installplan.yaml
```suggestion
  oc get installplan -n openshift-storage -o yaml > ${ARTIFACT_DIR}/installplan.yaml
```
```suggestion
  oc get installplan -n openshift-storage -o yaml >> ${ARTIFACT_DIR}/installplan.yaml
```

2021-10-21 05:41 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get nodes -o yaml > ${ARTIFACT_DIR}/node.yaml
```suggestion
  oc get nodes -o yaml > ${ARTIFACT_DIR}/node.yaml
```
```suggestion
  oc get nodes -o yaml >> ${ARTIFACT_DIR}/node.yaml
```

2021-10-21 05:41 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get storageclusters ocs-storagecluster -n openshift-storage -o yaml > ${ARTIFACT_DIR}/storagecluster.yaml
```suggestion
  oc get storageclusters ocs-storagecluster -n openshift-storage -o yaml > ${ARTIFACT_DIR}/storagecluster.yaml
```
```suggestion
  oc get storageclusters ocs-storagecluster -n openshift-storage -o yaml >> ${ARTIFACT_DIR}/storagecluster.yaml
```

2021-10-21 05:41 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get storagesystems -n openshift-storage -o yaml > ${ARTIFACT_DIR}/storagesystem_details.yaml
```suggestion
  oc get storagesystems -n openshift-storage -o yaml > ${ARTIFACT_DIR}/storagesystem_details.yaml
```
```suggestion
  oc get storagesystems -n openshift-storage -o yaml >> ${ARTIFACT_DIR}/storagesystem_details.yaml
```

2021-10-21 05:41 UTC, vbnrh commented on test-prow-e2e.sh
>    oc get subscriptions -n openshift-storage -o yaml > ${ARTIFACT_DIR}/subscription_details.yaml
```suggestion
  oc get subscriptions -n openshift-storage -o yaml > ${ARTIFACT_DIR}/subscription_details.yaml
```
```suggestion
  oc get subscriptions -n openshift-storage -o yaml > >${ARTIFACT_DIR}/subscription_details.yaml
```

2021-10-21 08:22 UTC, vbnrh requested changes

2021-10-21 08:22 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get catalogsource -n openshift-storage -o wide > ${ARTIFACT_DIR}/catalogsource.yaml
```suggestion
  oc get catalogsources -A  > ${ARTIFACT_DIR}/catalogsource.yaml
```
can check all resources for this

2021-10-21 08:22 UTC, vbnrh commented on test-prow-e2e.sh
> +  oc get pods -n openshift-storage -o yaml >> ${ARTIFACT_DIR}/pod_details.yaml
can segregate olm and openshift pods into different files

2021-10-21 14:44 UTC, merged