Rhstor 2516 in transit encryption
red-hat-storage/odf-console pull request #593
Opened 2023-01-12 13:29 UTC by debjyoti-pandit

2023-01-17 10:34 UTC, debjyoti-pandit commented
/assign @bipuladh 
/assign @SanjalKatiyar 
/assign @GowthamShanmugam

2023-01-17 11:06 UTC, bipuladh requested changes

2023-01-17 11:06 UTC, bipuladh commented on packages/odf/components/utils/common.ts
> +  };
Can we group all the changes to this field in one place? Feel free to create a function that returns a network configuration object and assign it to here. Make it handle creating the whole network object so that we can keep the logic from L393-411 in there as well.

2023-01-17 11:06 UTC, bipuladh commented on packages/odf/components/create-storage-system/footer.tsx
> +          canGoToNextStep(connectionDetails, storageClass.name)
```suggestion
          canGoToNextStep(connectionDetails, storageClass.name)
```

2023-01-17 11:06 UTC, bipuladh commented on packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
> +  _,
what is _?

2023-01-17 18:12 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
> +  _,
since we don't need the 4th parameter, I used that in order to avoid any un-used variable.

2023-01-30 11:48 UTC, GowthamShanmugam commented on locales/en/plugin__odf-console.json
> +  "In-transit Encryption": "In-transit Encryption",
```suggestion
  "In-transit Encryption": "In-transit encryption",
```

2023-01-30 12:08 UTC, GowthamShanmugam commented on packages/odf/components/system-list/odf-system-list.tsx
> +  const { apiGroup, apiVersion, kind } = getGVK(obj?.spec.kind);
```suggestion
  const { apiGroup, apiVersion, kind } = getGVK(obj?.spec?.kind);
```

2023-01-30 12:15 UTC, GowthamShanmugam commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
is external type does not required encryption.hasHandled && kms.providerState.hasHandled &&
        hasConfiguredNetwork check?

2023-01-30 12:28 UTC, GowthamShanmugam commented on packages/odf/components/create-storage-system/create-storage-system-steps/review-and-create-step/review-and-create-step.tsx
> +              {t('In-transit Encryption: {{hasInTransitEncryption}}', {
```suggestion
              {t('In-transit encryption: {{hasInTransitEncryption}}', {
```

2023-01-30 12:29 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
> +            title={t('In-transit Encryption')}
```suggestion
            title={t('In-transit encryption')}
```
Please check this with UX team

2023-01-30 12:30 UTC, GowthamShanmugam commented on packages/ocs/dashboards/persistent-external/details-card.tsx
> +            title={t('In-transit Encryption')}
```suggestion
            title={t('In-transit encryption')}
```

2023-02-06 05:32 UTC, SanjalKatiyar commented
@debjyoti-pandit plz update the PR with list page changes...

2023-02-06 15:17 UTC, debjyoti-pandit commented
enabled encryption
![image](https://user-images.githubusercontent.com/22158580/217007890-f46c3d06-ecd0-4164-88be-e2ff890aa10e.png)

![image](https://user-images.githubusercontent.com/22158580/217010346-bc828cfb-6f66-4867-9327-f13a2ea5033e.png)

![image](https://user-images.githubusercontent.com/22158580/217009901-45f2d76c-dab6-420a-921a-bdb797277448.png)

disabled encryption
![image](https://user-images.githubusercontent.com/22158580/217010086-7fef9ccc-d018-431a-8e2a-39ed9905c8ca.png)

![image](https://user-images.githubusercontent.com/22158580/217010165-91e7ecf0-6544-4cb0-8f8f-84d32cb66458.png)

![image](https://user-images.githubusercontent.com/22158580/217010244-0537aff0-d5ae-47a2-b4de-86fd9e9dfc14.png)

2023-02-15 14:00 UTC, SanjalKatiyar commented
@debjyoti-pandit we need to add the kebab item at one more place: default StorageSystem list page (check "Add Capacity", exactly same as that)...

2023-02-17 06:26 UTC, SanjalKatiyar commented
/hold
need to remove kebab item as per new requirements (no after deployment scenario now)...

2023-02-21 12:57 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-external/details-card.tsx
> +  const inTransitChecked = getNetworkEncryption(resourcesObj['ocs'].data?.[0])
nits:
```suggestion
  const inTransitstatus = getNetworkEncryption(resourcesObj['ocs'].data?.[0])
```

2023-02-21 12:58 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
> +  const cluster: StorageClusterKind = (ocsData as StorageClusterKind[])?.find(
use `useK8sList<StorageClusterKind> instead...
```suggestion
  const cluster: StorageClusterKind = ocsData?.find(
```

2023-02-21 12:59 UTC, SanjalKatiyar commented on packages/ocs/utils/common.ts
> +  cluster?.spec?.network?.connections?.encryption?.enabled || false;
just to conform: r u sure it is `enabled` only not `enable`

2023-02-21 13:24 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          state={state}
don't pass entire state... only pass what u need... make other fields optional...
ex: here we only need `state.securityAndNetwork` so only pass that...
where we need `state.connectionDetails` at that place pass that...
and handle this in `SecurityAndNetwork` accordingly...

2023-02-21 13:25 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          state={state}
don't pass entire state... only pass what u need... make other fields optional...
ex: here we need state.connectionDetails at that place pass that...
if any where we need state.securityAndNetwork so only pass that...
and handle this in SecurityAndNetwork accordingly...

2023-02-21 13:26 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          state={state}
each FC has it's own function, and props are passed down in a logical way to address that functionality...
don;t break this flow...

2023-02-21 13:26 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          state={state}
each FC has it's own function, and props are passed down in a logical way to address that functionality...
don;t break this flow...

2023-02-21 13:33 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
> +  _,
please don't do this...
handle it in `footer` file accordingly... `isRhcs ? inTransit : storageClass.name`

2023-02-21 13:35 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
```suggestion
        return canGoToNextStep && canGoToNextStep(connectionDetails, storageClass.name);
```

2023-02-21 13:37 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
don't just add new things... if older things are deprecated remove those conditions...
if this is not this needed it then, same at other places as well (if any):
```
    case StepsName(t)[Steps.ConnectionDetails]:
      return (
        canGoToNextStep && canGoToNextStep(connectionDetails, storageClass.name)
      );
```

2023-02-21 13:37 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        inTransitChecked
this is not the correct way to handle this...

2023-02-21 13:40 UTC, SanjalKatiyar commented on packages/odf/components/utils/common.ts
> +  const tempNetwork =
```suggestion
  const multusNetwork =
```

2023-02-21 13:41 UTC, SanjalKatiyar commented on packages/shared/utils/common.ts
> +  const apiVersion = label?.slice(label.indexOf('/') + 1, label.length);
why is this comment resolved, even though I can see changes still not made yet ?

2023-02-21 13:43 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        inTransitChecked
please don't do this...
maybe `isRhcs ? inTransit : storageClass.name`...

2023-02-21 13:43 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
> +  _,
> please don't do this... handle it in `footer` file accordingly... maybe `isRhcs ? inTransit : storageClass.name`...

2023-02-21 13:45 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +      if (type === BackingStorageType.EXTERNAL) {
don't just add new things... if older things are deprecated remove those conditions...
if this is not this needed it then, same at other places as well (if any):
```
    case StepsName(t)[Steps.ConnectionDetails]:
      return (
        canGoToNextStep && canGoToNextStep(connectionDetails, storageClass.name)
      );
```

2023-02-21 13:45 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
don't just add new things... if older things are deprecated remove those conditions...
if this is not this needed it then, same at other places as well (if any):
```
    case StepsName(t)[Steps.ConnectionDetails]:
      return (
        canGoToNextStep && canGoToNextStep(connectionDetails, storageClass.name)
      );
```

2023-02-21 14:32 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
> +  _,
if we send it from the footer then there are 2 prob - 

IBM storage type requires - the name which is a string type
RHCS needs a boolean.

Also if we pass like you mention, it would be difficult to name the param in 'CreatePayload'.
If we name it in transit, it's misleading for IBM type, and if we name it name then it's misleading for RHCS

2023-02-21 14:40 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
we need to add it for the Security and Network step under an if statement for the external mode of deployment.

Scenario 1 - renaming just the text connection details to S&N
We can reuse the existing ConnectionDetails step but then we have to rename the text which we are showing to security and Network. But then it's misleading as inside the Connection Details component we are showing user S&N.

Scenario 2 - now external mode has S&N step, so add the Connection details check only for them (current one)

Though we can now remove the connection details if the statement it is covered in the S&N step.
But I feel in no way we can avoid adding something to the current S&N step.

2023-02-21 14:42 UTC, debjyoti-pandit commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
> +  const inTransitChecked = getNetworkEncryption(cluster)
changed to inTransitEncryptionStatus

2023-02-21 14:42 UTC, debjyoti-pandit commented on packages/ocs/dashboards/persistent-internal/details-card.tsx
> +  const inTransitChecked = getNetworkEncryption(cluster)
@SanjalKatiyar

2023-02-21 14:43 UTC, debjyoti-pandit commented on packages/ocs/dashboards/persistent-external/details-card.tsx
> +  const inTransitChecked = getNetworkEncryption(resourcesObj['ocs'].data?.[0])
https://github.com/red-hat-storage/odf-console/pull/593#discussion_r1113159205

2023-02-21 15:04 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
got a review comment for the same - 
https://github.com/red-hat-storage/odf-console/pull/593#discussion_r1072067933

2023-02-21 15:05 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/footer.tsx
> +        inTransitChecked
https://github.com/red-hat-storage/odf-console/pull/593#discussion_r1113145970

2023-02-21 15:06 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/footer.tsx
> +      if (type === BackingStorageType.EXTERNAL) {
We can remove this, but we can't avoid adding the same logic in S&N under an if block.

2023-02-21 15:07 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/footer.tsx
> +      if (type === BackingStorageType.EXTERNAL) {
https://github.com/red-hat-storage/odf-console/pull/593#discussion_r1113156491

2023-02-21 15:14 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/external-storage/red-hat-ceph-storage/index.tsx
> +  _,
I added "maybe" in my comment for a reason... feel free to try other ways... passing `_` is not correct, what if in future we need to pass more arguments to this function... what if we only want to pass them for IBM not RHCS or vice versa...

also, if type is the only issue there is a `|` (or) condition in types as well...

2023-02-21 15:14 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        inTransitChecked
I added "maybe" in my comment for a reason... feel free to try other ways... passing `_` is not correct, what if in future we need to pass more arguments to this function... what if we only want to pass them for IBM not RHCS or vice versa...

also, if type is the only issue there is a `|` (or) condition in types as well...

2023-02-21 15:16 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +      if (type === BackingStorageType.EXTERNAL) {
I can understand... I am only suggesting to remove the things we don;t need along with addition of new contents !!
If we keep on adding new things without removing older part which are not needed, it will be a mess moving forward as functionality will expand...

2023-02-21 15:17 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        return canGoToNextStep(connectionDetails, storageClass.name);
I can understand... I am only suggesting to remove the things we don;t need along with addition of new contents !!
If we keep on adding new things without removing older part which are not needed, it will be a mess moving forward as functionality will expand...

2023-02-21 15:19 UTC, debjyoti-pandit commented on packages/odf/components/create-storage-system/footer.tsx
> +      if (type === BackingStorageType.EXTERNAL) {
ack. sorry as I forgot to remove the connection details block.

2023-02-22 11:43 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          securityAndNetworkState={state.securityAndNetwork}
```suggestion
          securityAndNetworkState={securityAndNetwork}
```

2023-02-22 11:44 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-steps.tsx
> +          backingStoreState={state.backingStorage}
```suggestion
          securityAndNetworkState={securityAndNetwork}
          dispatch={dispatch}
          infraType={infraType}
          isExternal={state.backingStorage.type === BackingStorageType.EXTERNAL}
          connectionDetailState={connectionDetails}
          externalStorage={backingStoreState.externalStorage}
```

2023-02-22 11:50 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/footer.tsx
> +        extraParams
make it an object...
example:
while passing arguments:
```
const subSystemPayloads = createPayload({
subSystemName,
subSystemState,
model,
storageClass.name,
inTransitChecked
})
```
while receiving arguments:
```
export const rhcsPayload: CreatePayload<RHCSState> = ({
  systemName,
  state,
  model,
  inTransitChecked
}) 
```

2023-02-23 14:47 UTC, debjyoti-pandit commented
![image](https://user-images.githubusercontent.com/22158580/220938616-622f429a-af46-4455-929a-72bcdf82bc9d.png)

![image](https://user-images.githubusercontent.com/22158580/220938941-678071b8-1547-429c-833b-0a1d192f4ce1.png)

![image](https://user-images.githubusercontent.com/22158580/220939021-bd3b88ac-a912-4b8d-8bd9-d375f8cbc150.png)

![image](https://user-images.githubusercontent.com/22158580/220939152-dcd9ba9a-c797-4e34-b4e6-1ff727d1c97b.png)

button disabled as the connection details were not entered
![image](https://user-images.githubusercontent.com/22158580/220939999-d4bf326f-0cb9-4e05-95b2-439c3ec5aa04.png)

the button is still disabled as encryption is optional
![image](https://user-images.githubusercontent.com/22158580/220940210-a32ee14a-c8d4-42ea-a63e-97199c7091ce.png)

![image](https://user-images.githubusercontent.com/22158580/220940370-03654763-3ea5-4ef8-85a3-78af6aa4dfb3.png)

![image](https://user-images.githubusercontent.com/22158580/220940516-2467007a-72b3-4340-a0bc-38d5f7137c80.png)

![image](https://user-images.githubusercontent.com/22158580/220940620-743e4589-f1b7-4707-8ec1-583792a39d5d.png)

2023-02-23 15:15 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
> +  );
```suggestion
```

2023-02-23 15:15 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
> +    setInTransitChecked(checked);
```suggestion
```

2023-02-23 15:15 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
> +          data-checked-state={inTransitChecked}
```suggestion
          isChecked={encryption.inTransit}
          data-checked-state={encryption.inTransit}
```

2023-02-23 15:16 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
> +  );
can't we use  encryption.inTransit directly ??

2023-02-23 15:19 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/security-and-network-step.tsx
> +  connectionDetails,
nits: just to be consistent with "securityAndNetworkState" naming...
```suggestion
  connectionDetailsState,
```

2023-02-23 15:21 UTC, SanjalKatiyar commented on packages/odf/components/create-storage-system/create-storage-system-steps/security-and-network-step/encryption.tsx
> +  );
why do we need extra state ??

2023-02-27 07:20 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-02-27 12:52 UTC, agarwal-mudit commented
@SanjalKatiyar can we remove hold label now?

2023-02-27 12:54 UTC, SanjalKatiyar commented
> @SanjalKatiyar can we remove hold label now?

/hold cancel

2023-02-27 13:09 UTC, SanjalKatiyar commented
/approve
/lgtm

2023-02-27 14:27 UTC, SanjalKatiyar commented
/lgtm

2023-02-27 14:35 UTC, debjyoti-pandit commented
/test images

2023-02-27 16:33 UTC, agarwal-mudit commented
/test ci/prow/odf-console-e2e-aws

2023-02-27 16:33 UTC, agarwal-mudit commented
/test odf-console-e2e-aws

2023-02-28 04:37 UTC, agarwal-mudit commented
/retest

2023-02-28 06:30 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-02-28 07:39 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-02-28 07:58 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-02-28 09:41 UTC, agarwal-mudit commented
@SanjalKatiyar can we check if the failure is because of the fix or not?

2023-02-28 09:48 UTC, debjyoti-pandit commented
> > @SanjalKatiyar can we check if the failure is because of the fix or not?
> 
> yesterday our odf-console CI was broken, so all the failures were due to that... CI is fixed now, so now it is mostly infra related issues... let;s wait for one more round, if it fails again @debjyoti-pandit rebase the PR once with latest master and push again.

Please re-tag it now, I have rebased it

2023-02-28 10:21 UTC, SanjalKatiyar commented
/lgtm

2023-02-28 13:57 UTC, agarwal-mudit commented
/retest

2023-02-28 16:08 UTC, agarwal-mudit commented
/retest

2023-02-28 16:08 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-02-28 17:51 UTC, agarwal-mudit commented
Merging as the ci is flaky.

2023-02-28 17:51 UTC, merged