fix: removed the subversion check for the mco operator
red-hat-storage/odf-console pull request #620
Opened 2023-02-02 10:42 UTC by debjyoti-pandit

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2165128

![image](https://user-images.githubusercontent.com/22158580/216303129-dfad55e1-9168-4149-8869-f224a735a462.png)

2023-02-02 10:42 UTC, debjyoti-pandit commented
/assign @SanjalKatiyar

2023-02-06 05:27 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
> +  );
```suggestion
  const odfMCOVersion = getMajorVersion(csv?.spec?.version);
```
useMemo is for expensive operations. No need here...

2023-02-06 05:28 UTC, SanjalKatiyar commented on packages/mco/utils/common.ts
> +  return version ? major(version) + '.' + minor(version) + '.0' : '';
```suggestion
  return !!version ? major(version) + '.' + minor(version) + '.0' : '';
```

2023-02-06 11:07 UTC, SanjalKatiyar commented on package.json
> +    "semver": "^7.3.8",
```suggestion
```

2023-02-06 11:08 UTC, SanjalKatiyar commented on package.json
> +    "@types/semver": "^7.3.13",
```suggestion
```

2023-02-06 11:12 UTC, SanjalKatiyar commented on package.json
> +    "semver": "^7.3.8",
@GowthamShanmugam we need to backport this PR, do u think it is okay to add new dependency ??

2023-02-07 09:16 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-02-08 08:14 UTC, SanjalKatiyar commented on package.json
> +    "semver": "^7.3.8",
@GowthamShanmugam if so we need to make sure we won't break the new 4.12.z builds...

2023-02-08 16:06 UTC, debjyoti-pandit commented on packages/mco/utils/common.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
It was throwing eslint error as it is not part of the dependencies list.

2023-02-08 16:21 UTC, SanjalKatiyar commented on packages/mco/utils/common.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
it is part of dependency list (as per what I see in ur PR)... we need to check why we are getting this right...
we can't just ignore and add a comment without figuring out the reasoning behind it...

2023-02-22 08:44 UTC, GowthamShanmugam commented on package.json
> +    "semver": "^7.3.8",
I think it is ok, we are not changing any existing dependency, so we are good here,

2023-02-22 08:47 UTC, GowthamShanmugam commented on packages/mco/utils/common.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
it might be due to cache

2023-02-22 08:48 UTC, SanjalKatiyar commented on package.json
> +    "semver": "^7.3.8",
actually it will change... many libraries are internally using "semver" as an internal dependency, now since we added "semver" as our own dependency, those internal versions will get updated as well...
I hope it won't cause any issue. We have CI for ODF so we might be good, but for MCO it is good to test that it won;t break older release-4.12 !!

2023-02-22 08:49 UTC, SanjalKatiyar commented on package.json
> +    "semver": "^7.3.8",
it is good to merge this for master, but for backport to 4.12, just make sure we don't introduce any regression...

2023-02-22 08:49 UTC, SanjalKatiyar commented on packages/mco/utils/common.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
cc @GowthamShanmugam

2023-02-22 09:17 UTC, GowthamShanmugam commented on package.json
> +    "semver": "^7.3.8",
agreed, atleast do some basic test.

2023-02-22 09:18 UTC, GowthamShanmugam commented on packages/mco/utils/common.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
try to clean cache and node_modules and try

2023-02-22 11:22 UTC, bipuladh commented on package.json
> +    "semver": "^7.3.8",
build teams use cachito so messing with dependencies can cause issues on that side.

2023-02-22 11:23 UTC, bipuladh requested changes
I really don't see the need to add a new package for this use case.

2023-02-22 11:24 UTC, debjyoti-pandit commented on package.json
> +    "semver": "^7.3.8",
@GowthamShanmugam https://github.com/red-hat-storage/odf-console/pull/620#pullrequestreview-1309043223

2023-02-27 07:56 UTC, GowthamShanmugam approved these changes

2023-02-27 10:14 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-03-07 04:31 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-03-07 12:31 UTC, debjyoti-pandit commented
/retest-required

2023-03-07 14:15 UTC, bipuladh commented
/retest

2023-03-09 09:23 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-03-13 07:37 UTC, SanjalKatiyar commented
@debjyoti-pandit plz update PR title properly...

2023-03-14 06:52 UTC, GowthamShanmugam approved these changes

2023-03-14 06:54 UTC, bipuladh commented
/lgtm

2023-03-14 12:32 UTC, debjyoti-pandit commented
/retest

2023-03-14 13:54 UTC, debjyoti-pandit commented
/retest

2023-03-15 06:56 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2023-03-15 10:53 UTC, merged

2023-03-15 11:02 UTC, GowthamShanmugam commented
/cherry-pick release-4.13

2023-03-15 11:02 UTC, GowthamShanmugam commented
/cherry-pick release-4.13-compatibility