fix redirect link to operator details page
red-hat-storage/odf-console pull request #633
Opened 2023-02-09 15:34 UTC by SanjalKatiyar

2023-02-09 16:05 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-02-10 05:56 UTC, vbnrh commented
Adding a test coverage for this issue is very important so that we don't get it again.

2023-02-10 06:04 UTC, SanjalKatiyar commented
> Adding a test coverage for this issue is very important so that we don't get it again.

created: https://github.com/red-hat-storage/odf-console/issues/634 for this.

2023-02-10 06:07 UTC, SanjalKatiyar commented
/cherry-pick release-4.12

2023-02-10 06:07 UTC, SanjalKatiyar commented
/cherry-pick release-4.12-compatibility

2023-02-10 06:10 UTC, vbnrh requested changes
Mostly looks good. Just one comment

2023-02-10 06:10 UTC, vbnrh commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +            {csvLoaded && !csvLoadError ? (
We are either showing 'Data Foundation' or the link for it. 
Is it ok to remove the loading part if we are backporting it ?

2023-02-10 06:17 UTC, SanjalKatiyar commented on packages/ocs/dashboards/object-service/details-card/details-card.tsx
> +            {csvLoaded && !csvLoadError ? (
by loading part do u mean "isLoading={false}" ??
it was always false so doesn't seem to be useful
if csv is loaded we will show link now... meanwhile it is loading it will just display name without any redirect link

2023-02-10 06:20 UTC, vbnrh commented
/lgtm

2023-02-10 06:23 UTC, merged