Topology: Add sidebar tabs for StorageClusterKind
red-hat-storage/odf-console pull request #654
Opened 2023-02-23 09:47 UTC by alfonsomthd

2023-02-23 10:20 UTC, alfonsomthd commented
/retest

2023-02-23 10:38 UTC, bipuladh requested changes

2023-02-23 10:38 UTC, bipuladh commented on packages/shared/topology/sidebar/TopologySideBarContent.tsx
>  import * as React from 'react';
Move these files to packages/odf/topology

2023-02-23 10:38 UTC, bipuladh commented on packages/shared/topology/sidebar/TopologySideBarContent.tsx
> +import StorageClusterResources from '../../../odf/components/topology/sidebar/storage-cluster/StorageClusterResources';
These are wrong imports.

2023-02-23 11:51 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-external/utilization-card.tsx
> +        title={t('Used Capacity')}
nits:
```suggestion
        title={t('Used capacity')}
```

2023-02-23 12:20 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/storage-efficiency-card/storage-efficiency-card.tsx
>          <CardTitle>{t('Storage Efficiency')}</CardTitle>
nits:
```suggestion
        <CardTitle>{t('Storage efficiency')}</CardTitle>
```

2023-02-23 12:20 UTC, SanjalKatiyar commented on packages/ocs/dashboards/persistent-internal/utilization-card/utilization-card.tsx
> +        title={t('Used Capacity')}
nits:
```suggestion
        title={t('Used capacity')}
```

2023-02-23 12:25 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +import { getCephNodes, getOperatorVersion } from '@odf/ocs/utils';
"odf" is not dependent on "ocs" as of now... so either we need to re think the imports or re think dependency that we set in "package.json"...

2023-02-23 12:32 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +  const ocsName = ocsLoaded && _.isEmpty(ocsError) ? getName(cluster) : '-';
nits:
we have "DASH" constant under "shared" for "-"

2023-02-23 12:32 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +      : '-';
nits:
we have "DASH" constant under "shared" for "-"

2023-02-23 12:35 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +    csvLoaded && _.isEmpty(csvError) ? getOperatorVersion(csv) : '-';
nits: "DASH"

2023-02-23 12:37 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +  const nodesData = (clusterResources?.nodes?.data ?? []) as K8sResourceKind[];
```suggestion
  const [nodesData, nodesLoaded, nodesLoadError] = useK8sWatchResource(nodesResource);
```

2023-02-23 12:37 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +            <dd>{ocsName || '-'}</dd>
```suggestion
            <dd>{ocsName || DASH}</dd>
```

2023-02-23 12:38 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +            <dt>{t('Storage Efficiency')}</dt>
nits:
```suggestion
            <dt>{t('Storage efficiency')}</dt>
```

2023-02-23 12:49 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterResources.tsx
> +              <NodesOverviewList nodes={nodes}></NodesOverviewList>
nits:
```suggestion
              <NodesOverviewList nodes={nodes} />
```

2023-02-23 12:49 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterResources.tsx
> +              ></DeploymentOverviewList>
```suggestion
              <DeploymentOverviewList
                deployments={deployments}
              />
```

2023-02-23 12:50 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterResources.tsx
> +          <div className="text-secondary">{t('Not available')}</div>
we have a FC `DataUnavailableError` under "shared" for this...

2023-02-23 12:50 UTC, SanjalKatiyar commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterResources.tsx
> +          <div className="text-secondary">{t('Not available')}</div>
we have a FC `DataUnavailableError` under "shared" for this...

2023-02-23 13:18 UTC, alfonsomthd commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterDetails.tsx
> +import { getCephNodes, getOperatorVersion } from '@odf/ocs/utils';
As per our previous conversation with @bipuladh , this will be addressed in another PR.

2023-02-23 17:44 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2023-02-27 10:47 UTC, alfonsomthd commented on packages/shared/topology/sidebar/TopologySideBarContent.tsx
>  import * as React from 'react';
Done.

2023-02-27 10:48 UTC, alfonsomthd commented on packages/shared/topology/sidebar/TopologySideBarContent.tsx
> +import StorageClusterResources from '../../../odf/components/topology/sidebar/storage-cluster/StorageClusterResources';
Addressed.

2023-02-27 11:00 UTC, bipuladh approved these changes

2023-02-27 11:00 UTC, bipuladh commented
/hold

2023-02-27 11:09 UTC, bipuladh commented
/hold cancel

2023-02-27 12:03 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2023-02-27 12:07 UTC, merged