Fix rerender issues for Alerts tab
red-hat-storage/odf-console pull request #667
Opened 2023-03-02 08:05 UTC by bipuladh

![Screenshot from 2023-03-02 13-50-16](https://user-images.githubusercontent.com/54092533/222368174-52c3e3d1-bc36-4c9f-b493-5c69d00f6c96.png)

- Removes usage of Drawer
- Starts using PFTopologySideBar

2023-03-03 14:28 UTC, alfonsomthd commented on packages/odf/components/topology/sidebar/TopologySideBar.tsx
> -    <DrawerPanelContent isResizable minSize="450px" defaultSize="500px">
The SideBar now is not resizable and the font size of the tabs name is smaller.

2023-03-03 14:29 UTC, alfonsomthd commented on packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
> +          title={<TabTitleText>{t('Resource')}</TabTitleText>}
```suggestion
          title={<TabTitleText>{t('Resources')}</TabTitleText>}
```

2023-03-07 06:43 UTC, SanjalKatiyar commented on packages/odf/components/topology/Topology.tsx
>    React.useEffect(() => {
plz add "setSelectedElement" to dependency list or add a "eslint-disable" (so that we can suppress these warnings that we get).

2023-03-07 06:52 UTC, SanjalKatiyar commented on packages/shared/utils/Tabs.tsx
> +      {elements || children}
`const temp = tabs.map((tab, i) => (` >> if `tabs` is optional it means it can be `undefined` as well right ??
we should use `?.` above for that....

2023-03-07 11:02 UTC, alfonsomthd requested changes

2023-03-07 11:02 UTC, alfonsomthd commented on packages/odf/components/topology/sidebar/TopologySideBar.tsx
> -            additionalClassName="odf-topology-sidebar__button-close"
`odf-topology-sidebar__button-close` CSS class should be deleted if not used anymore.

2023-03-07 11:41 UTC, alfonsomthd commented on packages/odf/components/topology/sidebar/TopologySideBarContent.tsx
> +      <Tabs activeKey={activeTab} onSelect={onSelect} unmountOnExit>
@bipuladh Tested locally: we get the same tabs Look'N'Feel (for consistency) by adding `odf-tabs` class
`import '@odf/shared/utils/tabs.scss';`

```suggestion
      <Tabs className="odf-tabs" activeKey={activeTab} onSelect={onSelect} unmountOnExit>
```

2023-03-13 11:33 UTC, bipuladh commented on packages/shared/utils/Tabs.tsx
> +      {elements || children}
removing these changes

2023-03-13 11:33 UTC, bipuladh commented on packages/odf/components/topology/Topology.tsx
>    React.useEffect(() => {
added

2023-03-13 11:34 UTC, bipuladh commented on packages/odf/components/topology/sidebar/storage-cluster/StorageClusterObserve.tsx
> +export const StorageClusterObserve: React.FC<{ resource: K8sResourceCommon }> =
ack

2023-03-13 13:06 UTC, SanjalKatiyar commented
/lgtm

2023-03-14 06:19 UTC, bipuladh commented
/test odf-console-e2e-aws

2023-03-14 08:47 UTC, merged

2023-03-14 10:33 UTC, bipuladh commented
/cherrypick release-4.13

2023-03-14 10:33 UTC, bipuladh commented
/cherrypick release-4.13-compatibility