Removed sync interval update for mirror peer
red-hat-storage/odf-console pull request #669
Opened 2023-03-02 14:31 UTC by GowthamShanmugam

2023-03-07 06:06 UTC, GowthamShanmugam commented
/hold

2023-03-07 07:03 UTC, SanjalKatiyar commented
> /hold
mco opr PR: https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/150 needs to be merged before this change.

2023-03-08 15:06 UTC, GowthamShanmugam commented
/hold

2023-03-13 13:16 UTC, GowthamShanmugam commented
/bugzilla refresh

2023-03-16 17:13 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2023-03-16 20:21 UTC, GowthamShanmugam commented
/retest

2023-03-17 05:39 UTC, SanjalKatiyar commented on packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
> +const getDRPolicyLispPageLink = (url: string) =>
```suggestion
const getDRPolicyListPageLink = (url: string) =>
```

2023-03-17 07:18 UTC, GowthamShanmugam commented on packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
> +const getDRPolicyLispPageLink = (url: string) =>
ack

2023-03-17 07:27 UTC, SanjalKatiyar commented
> > /hold
> > mco opr PR: [red-hat-storage/odf-multicluster-orchestrator#150](https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/150) needs to be merged before this change.

/hold cancel
mco PR is merged...

2023-03-17 07:27 UTC, SanjalKatiyar commented
/approve
/lgtm

2023-03-17 07:29 UTC, SanjalKatiyar commented
/cherry-pick release-4.13

2023-03-17 07:29 UTC, SanjalKatiyar commented
/cherry-pick release-4.13-compatibility

2023-03-17 07:54 UTC, vbnrh requested changes

2023-03-17 07:54 UTC, vbnrh commented on packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
> +              namespace: CEPH_STORAGE_NAMESPACE,
Are we assuming this to be constant ? Should probably be fetched from via clusterClaim be possible

2023-03-17 07:54 UTC, vbnrh commented on packages/mco/components/disaster-recovery/create-dr-policy/create-dr-policy.tsx
> +        metadata: { generateName: 'mirror-peer-' },
```suggestion
        metadata: { generateName: 'mirrorpeer-' },
```

nit

2023-03-17 09:08 UTC, vbnrh commented
/approve
/lgtm

2023-03-17 09:11 UTC, vbnrh commented
Should be followed up by adding a cluster claim in ocs operator for the storage cluster namespace.

2023-03-17 09:13 UTC, GowthamShanmugam commented
> Should be followed up by adding a cluster claim in ocs operator for the storage cluster namespace.

ack

2023-03-20 05:53 UTC, GowthamShanmugam commented
/test odf-console-e2e-aws

2023-03-20 07:39 UTC, merged