Bug 2166869 Update version of consoleplugin to odf operator
red-hat-storage/odf-console pull request #679
Opened 2023-03-10 17:48 UTC by TimothyAsirJeyasing

2023-03-10 17:49 UTC, TimothyAsirJeyasing commented
![Screenshot from 2023-03-10 22-38-26](https://user-images.githubusercontent.com/6670284/224387650-0c48e151-58c0-4341-9dfb-0690fbff673d.png)

2023-03-10 17:49 UTC, TimothyAsirJeyasing commented
@SanjalKatiyar Please review

2023-03-13 07:40 UTC, SanjalKatiyar commented
@TimothyAsirJeyasing plz update title correctly...

2023-03-15 06:58 UTC, bipuladh requested changes

2023-03-15 06:58 UTC, bipuladh commented on plugins/odf/console-plugin.json
> +  "version": "4.13.0",
Make a script set this up based on some env variable. Keep the build team aware of the ENV_VAR and also update yarn build to run that script.

2023-03-15 18:00 UTC, TimothyAsirJeyasing commented on plugins/odf/console-plugin.json
> +  "version": "4.13.0",
Sure, build team agreed to set the environment variable for main and compatibility
https://gitlab.cee.redhat.com/ceph/rhodf/-/commit/010143930adf3b2e1308e47069178fef81d4527c

2023-03-16 05:38 UTC, SanjalKatiyar commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
what will be the format of the value of "ODF_CONSOLE_VERSION" ??

2023-03-16 05:38 UTC, SanjalKatiyar commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
will it change based on z-stream ??

2023-03-16 06:16 UTC, SanjalKatiyar commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
is it possible to check if "ODF_CONSOLE_VERSION" is a valid semver or not ??
if not valid we will set it to default value...
I don;t want plugin to fail, in case there is a bug on build script side !! (say they pass incorrect format of the version)....
cc @bipuladh

2023-03-16 06:27 UTC, b-ranto commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
Yes, it will always match the current z-stream version, we always use the same X.Y.Z version for all the components during the build.

2023-03-16 06:33 UTC, SanjalKatiyar commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
cool... thanks !

2023-03-16 09:48 UTC, TimothyAsirJeyasing commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
Ok, How about the validation
[[ $ODF_CONSOLE_VERSION && $ODF_CONSOLE_VERSION =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]] || ODF_CONSOLE_VERSION="0.0.0"
sed -i -e 's/\"version\": .*/\"version\": \"'$ODF_CONSOLE_VERSION'\",/g' test.json

2023-03-16 13:03 UTC, SanjalKatiyar commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
cc @alfonsomthd what do u think would be best practice here...
it's a small command so does not make sense to have a separate script file for this...
still long enough to be added directly to package.json...
another thing is we have utilities like `semver.valid()` which we can use, but that would mean adding a new dependency...

2023-03-16 15:11 UTC, alfonsomthd commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
After a conversation we agree on creating a script that runs the semver validation and it's invoked during `yarn build`

2023-03-20 08:45 UTC, TimothyAsirJeyasing commented on package.json
> +    "build:version": "sed -i -e 's/\"version\": .*/\"version\": \"'${ODF_CONSOLE_VERSION:=0.0.0}'\",/g'",
ack

2023-03-20 11:17 UTC, bipuladh requested changes

2023-03-20 11:17 UTC, bipuladh commented on versionCheck.js
> +var fs = require('fs');
This should be a typescript file. 
It should use import statements instead of require. 
It should live under `scripts/` directory. 
For reference please check https://github.com/red-hat-storage/odf-console/blob/master/scripts/generatePluginPackage.mts

2023-03-20 11:17 UTC, bipuladh commented on versionCheck.js
> +const version = process.env['ODF_CONSOLE_VERSION'] ?? defaultVer;
```suggestion
const version = process.env['ODF_CONSOLE_VERSION'] || defaultVer;
```

2023-03-20 11:17 UTC, bipuladh commented on versionCheck.js
> +file &&
```suggestion
if (file === undefined) {
    console.error("usage: mts versionCheck <pluginName>");
```

2023-03-20 11:17 UTC, bipuladh commented on versionCheck.js
> +const file = process.argv[2];
```suggestion
const pluginName = process.argv[2];
```

2023-03-20 11:17 UTC, bipuladh commented on versionCheck.js
> +      );
It's a JSON file you can resolve it as a object and then update the field. Why use REGEX?

2023-03-20 11:17 UTC, bipuladh commented on versionCheck.js
> +      });
You can later serialize the JSON and write again.

2023-03-20 11:44 UTC, TimothyAsirJeyasing commented on versionCheck.js
> +var fs = require('fs');
Thank you, will update accordingly

2023-03-20 16:24 UTC, TimothyAsirJeyasing commented on versionCheck.js
> +file &&
Will update

2023-03-20 16:24 UTC, TimothyAsirJeyasing commented on versionCheck.js
> +const version = process.env['ODF_CONSOLE_VERSION'] ?? defaultVer;
Done the changes

2023-03-20 16:24 UTC, TimothyAsirJeyasing commented on versionCheck.js
> +const file = process.argv[2];
Done

2023-03-20 16:24 UTC, TimothyAsirJeyasing commented on versionCheck.js
> +      );
Sure will use JSON only and agree JSON will be much suitable one here.

2023-03-20 16:24 UTC, TimothyAsirJeyasing commented on versionCheck.js
> +      });
Sure will do that

2023-03-20 18:15 UTC, TimothyAsirJeyasing commented
/retest

2023-03-21 06:03 UTC, TimothyAsirJeyasing commented
/retest

2023-03-21 15:46 UTC, SanjalKatiyar commented
once backport PRs are up (after this master PR is merged), add the BZ number to the title of both PRs and make sure both PRs are added to "Links" section of the BZ... after that we can move BZ to "POST" and need to ask for "qa_ack" on the BZ... once done we can merge the backport PRs and move BZ to MODIFIED...

2023-03-21 15:46 UTC, SanjalKatiyar commented
fix the build tests...

2023-03-21 15:47 UTC, SanjalKatiyar commented
/cherry-pick release-4.13

2023-03-21 15:47 UTC, SanjalKatiyar commented
/cherry-pick release-4.13-compatibility

2023-03-23 12:42 UTC, TimothyAsirJeyasing commented
/retest

2023-03-23 14:01 UTC, alfonsomthd requested changes

2023-03-23 14:01 UTC, alfonsomthd commented on scripts/versionCheck.mts
> +  process.exit(1);
According to [Node.js documentation](https://nodejs.org/api/process.html#process_process_exit_code): `If it is necessary to terminate the Node.js process due to an error condition, throwing an uncaught error and allowing the process to terminate accordingly is safer than calling process.exit().`

```suggestion
  throw new Error(`Invalid argument: '${pluginToBeProcessed}'`);
```

2023-03-23 15:06 UTC, TimothyAsirJeyasing commented on scripts/versionCheck.mts
> +  process.exit(1);
Sure, will do that

2023-03-24 07:15 UTC, alfonsomthd commented
/approve

2023-03-24 07:57 UTC, alfonsomthd commented
/approve

2023-03-24 08:46 UTC, alfonsomthd commented
> /approve

@TimothyAsirJeyasing it does not work for me.

2023-03-27 11:09 UTC, alfonsomthd commented
@TimothyAsirJeyasing Please rebase.

2023-03-27 11:09 UTC, SanjalKatiyar commented
@TimothyAsirJeyasing plz resolve the conflicts...

2023-03-27 11:12 UTC, SanjalKatiyar commented on scripts/versionCheck.mts
> +const version = process.env['ODF_CONSOLE_VERSION'] || defaultVer;
we are using same script for mco/odf...
`ODF_CONSOLE_VERSION` is specific to odf only...

2023-03-28 05:41 UTC, b-ranto commented on scripts/versionCheck.mts
> +const version = process.env['ODF_CONSOLE_VERSION'] || defaultVer;
No worries there. We use the same ENV variable DS for both odf and mco builds. In fact, we use the exact same `X.Y.Z` version for all the components that we build in ODF. (we could override it for MCO if we wanted to but no reason really)

2023-03-28 05:55 UTC, SanjalKatiyar commented on scripts/versionCheck.mts
> +const version = process.env['ODF_CONSOLE_VERSION'] || defaultVer;
@b-ranto can we please use generic name instead like `PLUGIN_VERSION" ??
because mco and odf console are 2 different plugins, using `ODF_CONSOLE_VERSION` for both is a incorrect naming convention (even though logically correct)...

2023-03-28 15:47 UTC, b-ranto commented on scripts/versionCheck.mts
> +const version = process.env['ODF_CONSOLE_VERSION'] || defaultVer;
Ack, I agree that `ODF_CONSOLE_VERSION` might like weird for MCO console. Let's use `PLUGIN_VERSION` instead.

2023-03-29 11:15 UTC, alfonsomthd commented
/lgtm

2023-03-29 18:01 UTC, TimothyAsirJeyasing commented
/test odf-console-e2e-aws

2023-03-30 12:10 UTC, SanjalKatiyar commented
plz resolve the conflicts...

2023-03-30 13:01 UTC, bipuladh approved these changes

2023-03-30 14:22 UTC, merged

2023-04-04 09:15 UTC, TimothyAsirJeyasing commented
Manually its applying now to the branches, Could you please cherry pick one more time

2023-04-10 14:31 UTC, SanjalKatiyar commented
/cherry-pick release-4.13

2023-04-10 14:31 UTC, SanjalKatiyar commented
/cherry-pick release-4.13-compatibility