Adds upstream catalog source for odf and script changes
red-hat-storage/odf-console pull request #73
Opened 2021-11-23 04:01 UTC by vbnrh

Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>

2021-11-23 05:18 UTC, bipuladh requested changes

2021-11-23 05:18 UTC, bipuladh commented on openshift-ci/odf-catalog-source.yaml
> +  image: quay.io/rhceph-dev/ocs-registry:4.9.0-236.ci
```suggestion
  image: quay.io/rhceph-dev/ocs-registry:latest-stable-4.9.0
```

2021-11-23 05:18 UTC, bipuladh commented on test-prow-e2e.sh
> +echo "Enabling Console Plugin for ODF Operator"
This should be done from Operator Hub.

2021-11-23 05:33 UTC, vbnrh commented on test-prow-e2e.sh
> +echo "Enabling Console Plugin for ODF Operator"
this was added previously last time itself since we removed operator installation from the cy.install(). Lets change it later on if required or we'll need to change the install again

2021-11-23 06:02 UTC, vbnrh commented on openshift-ci/odf-catalog-source.yaml
> +  image: quay.io/rhceph-dev/ocs-registry:4.9.0-236.ci
changed

2021-11-23 06:09 UTC, vbnrh commented on my-script.sh
> +#!/usr/bin/env bash
Please ignore this file. This is exact duplicate of test-prow-e2e.sh with few changes to run on CI side by side.

2021-11-24 06:47 UTC, bipuladh approved these changes
/lgtm

2021-11-24 06:48 UTC, merged