[WIP] Migration: Moves Storage System List Page and Add Capacity Modal
red-hat-storage/odf-console pull request #75
Opened 2021-11-30 12:30 UTC by bipuladh

2021-12-10 09:01 UTC, bipuladh commented
/assign @afreen23 @vbnrh

2021-12-10 10:31 UTC, bipuladh commented
/hold 
Get more eyes on it

2021-12-10 10:37 UTC, bipuladh commented
/assign @vbnrh

2021-12-10 11:01 UTC, vbnrh commented
![Screenshot from 2021-12-10 16-21-33](https://user-images.githubusercontent.com/57935785/145563829-1b3c4556-494e-4d63-b60a-6463c6e04602.png)

Working ! 

Will take some time for code reviews

2021-12-10 11:33 UTC, afreen23 requested changes

2021-12-10 11:33 UTC, afreen23 commented on package.json
> +    "@openshift-console/dynamic-plugin-sdk": "0.0.3",
is this required in this PR ?
Its a good practice to bump the  versions in separate PR /commit.

2021-12-10 11:33 UTC, afreen23 commented on packages/odf/modals/add-capacity/add-capacity-modal.scss
> +.ceph-add-capacity__current-capacity {
We should change these css prefixes now.

2021-12-10 11:49 UTC, bipuladh commented on package.json
> +    "@openshift-console/dynamic-plugin-sdk": "0.0.3",
We need to add kubevirt package and kubevirt has dependency on this version.

2021-12-10 11:49 UTC, bipuladh commented on packages/odf/modals/add-capacity/add-capacity-modal.scss
> +.ceph-add-capacity__current-capacity {
yeah we should definitely do it. It would be easy to do in a follow up PR though.

2021-12-10 12:01 UTC, bipuladh commented on packages/odf/modals/add-capacity/add-capacity-modal.scss
> +.ceph-add-capacity__current-capacity {
I will create an issue in the repo.

2021-12-13 09:21 UTC, SanjalKatiyar commented on packages/shared/status/StatusIconAndText.tsx
> +const DASH = '-';
very small things...
since we are using this variable in multiple files we can import it from some common file exporting constants.

2021-12-15 07:35 UTC, bipuladh commented
Currently I have not added AddCapacity extension for CSV pages. Need some more code for it. So will do it in a different PR. Will create an issue to track it.

2021-12-15 07:37 UTC, bipuladh commented
> Currently I have not added AddCapacity extension for CSV pages. Need some more code for it. So will do it in a different PR. Will create an issue to track it.

https://github.com/red-hat-storage/odf-console/issues/85

2021-12-15 08:56 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/dashboard.tsx
> +    },
just a doubt... can't we add it as a extension here in `odf-console` as well ?
like we were doing in `console` repo...

2021-12-15 09:35 UTC, bipuladh commented on packages/odf/components/odf-dashboard/dashboard.tsx
> +    },
We can, but why would we do it? The reason we did that is because we couldn't directly put it here.

2021-12-15 09:41 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/dashboard.tsx
> +    },
ack...

2021-12-15 10:17 UTC, SanjalKatiyar commented
/hold cancel

2021-12-15 10:25 UTC, SanjalKatiyar commented
> ![Screenshot from 2021-12-10 16-21-33](https://user-images.githubusercontent.com/57935785/145563829-1b3c4556-494e-4d63-b60a-6463c6e04602.png)
> 
> Working !
> 
> Will take some time for code reviews

/lgtm

2021-12-15 10:44 UTC, merged