Remove view-details link for DR alerts
red-hat-storage/odf-console pull request #763
Opened 2023-04-03 09:33 UTC by TimothyAsirJeyasing

2023-04-03 09:41 UTC, TimothyAsirJeyasing commented
https://github.com/openshift/console/pull/12701

2023-04-03 14:12 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
> +  alerts['hideView'] = true;
I don't think this is going to work. This might not trigger a rerender.

2023-04-03 14:55 UTC, TimothyAsirJeyasing commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
> +  alerts['hideView'] = true;
This is only a new property I want to just add for now.

2023-04-03 14:56 UTC, TimothyAsirJeyasing commented
![Screenshot from 2023-04-03 20-20-47](https://user-images.githubusercontent.com/6670284/229547928-2acaee63-a417-4fea-8ec5-95ec5bcadd9f.png)

2023-04-03 16:52 UTC, alfonsomthd commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
> +  alerts['hideView'] = true;
IMHO show/hide view belongs to AlertsProps (not to the alerts) so you can add a new field:
```
type AlertsProps = {
  alerts: Alert[];
  [...]
  hideViewLink?: boolean;
};
```
and pass the flag to [`Alertitem` (if it's what you were planning)](https://github.com/openshift/console/pull/12701/files#r1156198116).

2023-04-04 05:32 UTC, TimothyAsirJeyasing commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
> +  alerts['hideView'] = true;
ok, i moved the alertItem to odf-console as per discussion

2023-04-04 08:33 UTC, TimothyAsirJeyasing commented
UX team is suggesting some other changes now, Will update this pr after getting some more clarity from them

2023-04-05 03:59 UTC, bipuladh requested changes

2023-04-05 03:59 UTC, bipuladh commented on packages/shared/alert/AlertItem.tsx
> +    ></StatusItem>
```suggestion
  return (
    <StatusItem
      Icon={getSeverityIcon(getAlertSeverity(alert))}
      timestamp={getAlertTime(alert)}
      message={
        getAlertDescription(alert) ||
        getAlertMessage(alert) ||
        getAlertSummary(alert)
      }
      name={alertName}
   />
```

2023-04-05 03:59 UTC, bipuladh commented on packages/shared/alert/AlertItem.tsx
> +import * as React from 'react';
Keep this as part of packages/mco. This is not a generic component.

2023-04-05 03:59 UTC, bipuladh commented on packages/shared/alert/AlertItem.tsx
> +  documentationLink?: string;
```suggestion
```

2023-04-05 03:59 UTC, bipuladh commented on packages/shared/alert/AlertsPanel.tsx
> +                <AlertItem key={alert?.rule?.id} alert={alert} />
This will affect all the AlertItems. Instead of that allow users to pass a Component for `AlertItem` the prop name could be `AlertItemComponent` the default value will be the component from the SDK.

2023-04-05 14:09 UTC, SanjalKatiyar commented
@TimothyAsirJeyasing plz add BZ link to the PR's description...

2023-04-13 18:46 UTC, TimothyAsirJeyasing commented on packages/shared/alert/AlertItem.tsx
> +import * as React from 'react';
Since AlertItem.tsx is used by AlertsPanel.tsx from packages/share. If i move the AlertItem.tsx to mco i need to mention the path in AlertsPanel.tsx like 
import AlertItem from 'packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem';
will it be ok ?
Or should i keep the alertItem.tsx in packages/share only and pass a flag to handle hiding.

2023-04-14 06:07 UTC, SanjalKatiyar commented on packages/shared/alert/AlertItem.tsx
> +import * as React from 'react';
odf will still use the component exposed by sdk...
only mco needs to use this one...

2023-04-14 06:10 UTC, SanjalKatiyar commented
u are copying component from console but u are never using it for mco... this BZ is for mco to use that components...
plz make sure PR is complete as per the requirements of the BZ we need to take the BZ in 4.13.0 release...

2023-04-14 13:52 UTC, TimothyAsirJeyasing commented
I am going to move this AlertItem and AlertsPanel to mco as per the suggestion by Bipul.

2023-04-14 17:04 UTC, bipuladh requested changes

2023-04-14 17:04 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertsPanel.tsx
> +const AlertAccordionItem: React.FC<AlertAccordionItemProps> = ({
why do you need to copy this too?

2023-04-14 17:04 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem.tsx
> +import { getAlertSeverity } from '../../../../../shared/utils';
```suggestion
import { getAlertSeverity } from '@odf/shared/utils';
```
Do this for all shared relative imports.

2023-04-14 17:04 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem.tsx
> +import './alert-item.scss';
move scss import to last.

2023-04-14 17:04 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem.tsx
> +};
These could be imported from shared. No need to copy it here.

2023-04-14 17:04 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertsPanel.tsx
> +                <AlertItem key={alert?.rule?.id} alert={alert} />
You could pass `AlertItem` component as a prop in the shared component. So when using from MCO you will pass your custom `AlertItem` without view details button but for rest use the default `AlertItem`.

2023-04-17 06:31 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem.tsx
> +import * as React from 'react';
rename the file to alert-item.tsx

2023-04-17 06:32 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem.tsx
> +import { Timestamp } from '../../../../../shared/details-page/timestamp';
```suggestion
import { Timestamp } from '@odf/shared/details-page/timestamp';
```

2023-04-17 06:32 UTC, GowthamShanmugam commented on packages/mco/components/mco-dashboard/data-policy/alert-card/AlertItem.tsx
> +} from '../../../../../shared/status/icons';
```suggestion
} from '@odf/shared/status/icons';
```

2023-04-17 08:23 UTC, bipuladh commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemProp?: typeof React.Component;
```suggestion
  AlertItemComponent?: typeof React.Component;
```

2023-04-17 08:23 UTC, bipuladh commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemProp,
```suggestion
  AlertItemProp = AlertItem,
```

2023-04-17 08:23 UTC, bipuladh commented on packages/shared/alert/AlertsPanel.tsx
> +              )}
```suggestion
                  <AlertItemComponent key={alert?.rule?.id} alert={alert} />           
```
Make AlertItem the default value for `AlertItemComponent` prop.

2023-04-17 11:02 UTC, bipuladh requested changes

2023-04-17 11:02 UTC, bipuladh commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemComponent?: typeof React.Component;
```suggestion
  AlertItemComponent?: React.FC<{key: string alert: Alert}>;
```

2023-04-17 11:02 UTC, bipuladh commented on packages/shared/utils/common.ts
> +};
Create a file at `shared/alert/utils.ts` and move it there.

2023-04-17 11:02 UTC, bipuladh commented on packages/shared/utils/metrics.ts
> +  alert && alert.labels ? alert.labels.alertname : null;
Move these to `shared/alert/utils.ts` as well.

2023-04-17 13:32 UTC, SanjalKatiyar commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemComponent,
"AlertsPanel" is used in odf as well... are we passing console's "AlertItem" from there ??

2023-04-17 13:34 UTC, SanjalKatiyar commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemComponent,
"AlertsPanel" is used by topology as well, are we passing original (console's) "AlertItem" from there ??

2023-04-17 13:39 UTC, TimothyAsirJeyasing commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemComponent,
yes the default is AlertItem from console only. For mco we are passing as prop.

2023-04-17 13:44 UTC, SanjalKatiyar commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemComponent,
ok...

2023-04-17 14:06 UTC, bipuladh commented on packages/shared/alert/AlertsPanel.tsx
> +  AlertItemComponent = AlertItem,
lets keep it as a default component.

2023-04-17 14:06 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-card.tsx
> +          AlertItemComponent={AlertItem as any}
```suggestion
          AlertItemComponent={AlertItem}
```

2023-04-18 05:58 UTC, SanjalKatiyar commented
@TimothyAsirJeyasing plz update the PR as per reviews and once this is merged and backport PRs are ready, update the title of the backport PRs and add bug number and get the PRs tagged...

2023-04-18 06:25 UTC, bipuladh commented on packages/mco/components/mco-dashboard/data-policy/alert-card/alert-item.tsx
> +const AlertItem: React.FC<AlertItemProps> = ({ alert }) => {
```suggestion
const AlertItem: React.FC<React.ComponentProps<typeof AlertItemSDK>> = ({ alert }) => {
```
import the `AlertItem` from SDK as `AlertItemSDK`

2023-04-18 07:36 UTC, bipuladh approved these changes

2023-04-18 07:46 UTC, TimothyAsirJeyasing commented
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2180410

2023-04-18 12:12 UTC, merged

2023-04-18 12:32 UTC, SanjalKatiyar commented
/cherry-pick release-4.13

2023-04-18 12:33 UTC, SanjalKatiyar commented
/cherry-pick release-4.13-compatibility