Add tests for Add Capacity and Storage System List Page
red-hat-storage/odf-console pull request #77
Opened 2021-12-02 06:24 UTC by bipuladh

2021-12-02 07:48 UTC, rexagod requested changes

2021-12-02 07:48 UTC, rexagod commented on cypress/tests/list-page.spec.ts
> +        cy.contains(OCS_SS).should('exist');
Can we search for just the OCS_SS beforehand? This should prevent errors when there are multiple SS.

![Screenshot from 2021-12-02 12-40-01](https://user-images.githubusercontent.com/33557095/144375598-53ff6471-a54f-41e3-ae0f-ac22c737a17f.png)

2021-12-02 07:48 UTC, rexagod commented on cypress/tests/list-page.spec.ts
> +        cy.get('h1').contains(OCS_SS).should('exist');
```suggestion
        cy.byLegacyTestID('resource-title').contains(OCS_SS).should('exist');
```

2021-12-02 07:48 UTC, rexagod commented on cypress/tests/add-capacity.spec.ts
> +      cy.byLegacyTestID('kebab-button').click();
[link]

2021-12-02 08:41 UTC, vbnrh requested changes
We can make use of consts for the commands that we are executing.

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +      const initialCapcity =
```suggestion
      const initialCapacity =
```

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +      cy.log('Check cluster deivce set count has increased');
```suggestion
      cy.log('Check cluster device set count has increased');
```

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +    cy.exec('oc get storagecluster ocs-storagecluster -n openshift-storage -o json').then((res) => {
```suggestion
    cy.exec(`oc get storagecluster ${OCS_SC} -n openshift-storage -o json`).then((res) => {
```

since we have already declared constants

2021-12-02 08:41 UTC, vbnrh commented on cypress/consts.ts
> +const STORAGECLUSTER_PHASE = `"$(oc get storageclusters -n openshift-storage -o=jsonpath='${SC_PHASE_QUERY("ocs-storagecluster")}')"`;
```suggestion
const STORAGECLUSTER_PHASE = `"$(oc get storageclusters -n ${NS} -o=jsonpath='${SC_PHASE_QUERY("ocs-storagecluster")}')"`;
```

from consts

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +    cy.exec('oc get storagecluster ocs-storagecluster -n openshift-storage -o json').then((res) => {
```suggestion
    cy.exec('oc get storagecluster ${OCS_SC} -n ${NS} -o json').then((res) => {
```

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +    cy.exec('oc get cephCluster ocs-storagecluster-cephcluster -n openshift-storage -o json').then(
Similarly here, we can declare these as consts and use them

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +    cy.exec('oc get cephCluster ocs-storagecluster-cephcluster -n openshift-storage -o json').then(
consts

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/add-capacity.spec.ts
> +      `oc -n openshift-storage rsh $(oc get po -n openshift-storage | grep ceph-operator | awk '{print$1}') ceph --conf=/var/lib/rook/openshift-storage/openshift-storage.config osd tree --format=json
`var/lib/rook/openshift-storage/openshift-storage.config`

We can extract this out too as rookConfigPath

2021-12-02 08:41 UTC, vbnrh commented on cypress/tests/list-page.spec.ts
> +        cy.clickNavLink(['Storage', 'OpenShift Data Foundation']);
Common operation for literally all tests from here on out. Extract out as a function .

2021-12-07 11:55 UTC, vbnrh commented
/test odf-console-e2e-aws

2021-12-08 07:53 UTC, rexagod commented
/lgtm
/test odf-console-e2e-aws

Based on the CI [screenshots](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/red-hat-storage_odf-console/77/pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws/1468461853892939776/artifacts/odf-console-e2e-aws/tests/artifacts/gui-test-screenshots/screenshots/), I'm wondering if we need to revisit the `cy.logout` method, due to its [potentially flaky behavior](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/red-hat-storage_odf-console/77/pull-ci-red-hat-storage-odf-console-master-odf-console-e2e-aws/1468461853892939776/artifacts/odf-console-e2e-aws/tests/artifacts/gui-test-screenshots/cypress_report.html)?

2021-12-08 07:54 UTC, merged