[WIP] Make ODF Console a Monorepo, make OCS an internal package
red-hat-storage/odf-console pull request #78
Opened 2021-12-08 07:19 UTC by bipuladh

/assign @cloudbehl

2021-12-08 11:21 UTC, bipuladh commented
/test odf-console-e2e-aws

2021-12-08 12:15 UTC, bipuladh commented
/hold

2021-12-08 12:17 UTC, bipuladh commented
/test ci/prow/lint

2021-12-08 12:17 UTC, bipuladh commented
/test all

2021-12-08 14:48 UTC, afreen23 commented
/assign @afreen23

2021-12-08 14:50 UTC, afreen23 requested changes
can you add some changelog or description , what changes are you making ?
I see some refactors which are not clear

2021-12-08 14:50 UTC, afreen23 commented on packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
> +          resourceModel={ODFStorageSystem}
why this ?

2021-12-08 14:52 UTC, bipuladh commented on packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
> +          resourceModel={ODFStorageSystem}
Need to do this to segregate common types and odf specific types.

2021-12-09 04:10 UTC, afreen23 approved these changes

2021-12-09 04:39 UTC, cloudbehl approved these changes

2021-12-09 09:41 UTC, GowthamShanmugam approved these changes

2021-12-09 10:10 UTC, rexagod requested changes
This was a much needed change, thank you @bipuladh! 🎉

2021-12-09 10:10 UTC, rexagod commented on packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
> +import { humanizeBinaryBytes } from '../../../../shared/utils/humanize';
Let's leverage the different packages now for cleaner import paths (maybe replacing more than 2 `../` with their package-prefixed paths?).
```suggestion
import { humanizeBinaryBytes } from '@odf/shared/utils/humanize';
```

2021-12-09 10:10 UTC, rexagod commented on packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
> +import { ODFStorageSystem } from '../../../models';
```suggestion
import { ODFStorageSystem } from '@odf/core/models';
```

2021-12-09 10:10 UTC, rexagod commented on packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
> +} from '../../../../shared/dashboards/capacity-card/capacity-card';
```suggestion
} from '@odf/shared/dashboards/capacity-card/capacity-card';
```

2021-12-09 10:10 UTC, rexagod commented on packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
> +import { humanizeBinaryBytes } from '../../../../shared/utils/humanize';
```suggestion
import { humanizeBinaryBytes } from '@odf/shared/utils/humanize';
```

2021-12-09 10:10 UTC, rexagod commented on packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
> +import { StorageSystemKind } from '../../../types';
```suggestion
import { ODFStorageSystem } from '@odf/core/models';
import { StorageSystemKind } from '@odf/core/types';
```

2021-12-09 10:35 UTC, bipuladh commented on package.json
>      "exposedModules": {
This is an internal field that we use to expose components from our packages. Think of it like entry point of webpack.

2021-12-09 10:49 UTC, bipuladh commented on packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
> +import { humanizeBinaryBytes } from '../../../../shared/utils/humanize';
Let's do this only for cross package imports. Same package imports should use relative path.

2021-12-09 11:14 UTC, rexagod commented on packages/odf/components/odf-dashboard/object-storage-card/capacity-card.tsx
> +import { humanizeBinaryBytes } from '../../../../shared/utils/humanize';
Makes sense.

2021-12-09 11:33 UTC, rexagod commented
/lgtm

2021-12-09 18:27 UTC, rexagod commented
@bipuladh Can we remove the hold now?

2021-12-10 06:25 UTC, afreen23 commented
/lgtm

2021-12-10 06:37 UTC, bipuladh commented
/hold cancel

2021-12-10 07:14 UTC, rexagod commented
/lgtm

2021-12-10 07:16 UTC, merged