Check for ODF SS list page during installation.
red-hat-storage/odf-console pull request #80
Opened 2021-12-08 10:12 UTC by rexagod

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

2021-12-08 10:30 UTC, vbnrh requested changes

2021-12-08 10:30 UTC, vbnrh commented on cypress/support.ts
> +      cy.get('td[role="gridcell"]', {timeout: 5 * 60000}).contains("Available");
All this needs to be done after clicking the create button. Please move it before the storagecluster checks

2021-12-10 12:05 UTC, bipuladh requested changes

2022-02-04 10:04 UTC, bipuladh approved these changes
/lgtm

2022-02-04 10:43 UTC, merged