tests: create namespace store
red-hat-storage/odf-console pull request #827
Opened 2023-05-02 07:17 UTC by TimothyAsirJeyasing

2023-05-02 07:55 UTC, alfonsomthd commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +it('checkHeaderText', () => {
Can you please make the test description mor meaningful, like `shows the correct heading texts`

2023-05-02 07:57 UTC, alfonsomthd commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +it('checkTitleText', () => {
It seems this text only adda an additonal expectation over the previous so IMHO these text heading expectations cna libe in the same test.

2023-05-07 12:00 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +  it('shows the correct heading texts', () => {
Breaking down unit tests into separate tests for different parts is considered a beneficial approach rather than consolidating all the checks in one unit test. By doing so, it becomes easier to locate where the test is failing and subsequently fix the code. An ideal unit test should allow developers or testing teams to identify the problem by just reading the title or description.

2023-05-07 12:01 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +  it('shows the correct heading texts', () => {
cc @alfonsomthd

2023-05-07 19:29 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +    expect(historyMock.location.pathname).toBe('/test');
My understanding is that the current check is focused on the cancel button's functionality. However, I suggest that we redirect our attention to verifying whether the NamespaceStoreForm is invoked with the appropriate redirect handler. By doing so, we can ensure that the redirect handler's ability to find the last index is also being tested. Additionally, I recommend mocking the referenceForModel to better isolate the behavior under test.

2023-05-07 19:31 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +    const nsStoreFormClass = container.getElementsByClassName(
Wouldn't it be beneficial to use a mocked version of the NamespaceStoreForm?

cc @alfonsomthd

2023-05-07 19:35 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +    const titleHeading = container.getElementsByClassName('help-block')[0];
We can also verify the size and heading level of the Title component that is being passed from this component.

2023-05-07 19:36 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +  ns: '',
Can we include a test to confirm that the component's default namespace parameter is set to CEPH_STORAGE_NAMESPACE?

2023-05-08 06:40 UTC, alfonsomthd commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +  it('shows the correct heading texts', () => {
> Breaking down unit tests into separate tests for different parts is considered a beneficial approach rather than consolidating all the checks in one unit test. By doing so, it becomes easier to locate where the test is failing and subsequently fix the code. An ideal unit test should allow developers or testing teams to identify the problem by just reading the title or description.

I agree (except when the code being tested is very small). In this particular case it seems the test logic keeps growing so it makes sense to split in order to understand the use case (scenario) being tested.

2023-05-08 06:51 UTC, alfonsomthd commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +    expect(historyMock.location.pathname).toBe('/test');
> Additionally, I recommend mocking the referenceForModel to better isolate the behavior under test.
> 
> cc @alfonsomthd

@debjyoti-pandit we should only mock when necessary: right now (current implementation) the mock is not making any difference: the test is passing without it, so I guess you're suggesting this in order to test the props' values passed to the child component, right?

2023-05-08 06:54 UTC, alfonsomthd commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +    const nsStoreFormClass = container.getElementsByClassName(
@debjyoti-pandit If we want to increase the coverage by testing the props' values passed to it (the child component) then yes.

2023-05-08 06:55 UTC, debjyoti-pandit commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +    expect(historyMock.location.pathname).toBe('/test');
Yes, true. the props values we are passing to the child component.

2023-05-11 05:36 UTC, TimothyAsirJeyasing commented
/test odf-console-e2e-aws

2023-05-15 13:55 UTC, ivoalmeida commented
/lgtm

2023-05-29 08:52 UTC, debjyoti-pandit commented
/test odf-console-e2e-aws

2023-05-29 08:52 UTC, debjyoti-pandit commented
/lgtm

2023-10-17 14:46 UTC, alfonsomthd requested changes

2023-10-17 14:46 UTC, alfonsomthd commented on packages/odf/components/namespace-store/create-namespace-store.spec.tsx
> +  it('test get name', () => {
@TimothyAsirJeyasing this test (and some other above) does not belong here as we should avoid testing the child components.
Here we should test the `CreateNamespaceStore` behavior and make sure that the child component receives the namespace we expect it (but not testing the child itself). So I suggest:

1. Apply this patch where the component-related tests are kept:
```
diff --git a/packages/odf/components/namespace-store/create-namespace-store.spec.tsx b/packages/odf/components/namespace-store/create-namespace-store.spec.tsx
index 5f4f091..67c0259 100644
--- a/packages/odf/components/namespace-store/create-namespace-store.spec.tsx
+++ b/packages/odf/components/namespace-store/create-namespace-store.spec.tsx
@@ -1,55 +1,18 @@
 import * as React from 'react';
-import * as selectors from '@odf/shared/selectors';
-import { fireEvent, render, screen } from '@testing-library/react';
+import { CEPH_STORAGE_NAMESPACE } from '@odf/shared/constants';
+import { render } from '@testing-library/react';
 import CreateNamespaceStore from './create-namespace-store';
 
 const params = {
-  ns: 'anyvalue',
+  ns: 'test-ns',
 };
 
-jest.mock('@odf/shared/selectors', () => ({
-  getName: jest.fn().mockReturnValue('test'),
-}));
-
-jest.mock('@openshift-console/dynamic-plugin-sdk', () => {
-  return {
-    ...jest.requireActual('@openshift-console/dynamic-plugin-sdk'),
-    useK8sWatchResource: jest.fn().mockReturnValue([[], false, false]),
-  };
+const mockNamespaceStoreForm = jest.fn();
+jest.mock('./namespace-store-form', () => (props) => {
+  mockNamespaceStoreForm(props);
+  return <mock-NamespaceStoreForm />;
 });
 
-const historyMock = {
-  location: {
-    pathname: '',
-  },
-  goBack: () => {
-    historyMock.location.pathname = '/testpath';
-  },
-  //push: () => jest.fn(),
-};
-
-jest.mock('react-router', () => {
-  return {
-    ...jest.requireActual('react-router'),
-    useHistory: jest.fn().mockImplementation(() => historyMock),
-  };
-});
-
-jest.mock('@odf/shared/hooks/useK8sList', () => ({
-  __esModule: true,
-  useK8sList: () => [
-    [
-      {
-        metadata: {
-          name: 'test',
-        },
-      },
-    ],
-    true,
-    undefined,
-  ],
-}));
-
 describe('CreateNamespaceStore test', () => {
   it('shows the correct heading texts', () => {
     const { container } = render(<CreateNamespaceStore match={{ params }} />);
@@ -74,23 +37,21 @@ describe('CreateNamespaceStore test', () => {
     ).toBeTruthy();
   });
 
-  it('Check namespace store form class found', () => {
-    const { container } = render(<CreateNamespaceStore match={{ params }} />);
-    const nsStoreFormClass = container.getElementsByClassName(
-      'nb-endpoints-page-form__short'
-    )[0];
-    expect(nsStoreFormClass).toBeInTheDocument();
-  });
-
-  it('Check onCancel and history', () => {
+  it('pass the received namespace to the form', () => {
     render(<CreateNamespaceStore match={{ params }} />);
-    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }));
-    expect(historyMock.location.pathname).toBe('/testpath');
+    expect(mockNamespaceStoreForm).toHaveBeenCalledWith(
+      expect.objectContaining({
+        namespace: 'test-ns',
+      })
+    );
   });
 
-  it('test get name', () => {
-    render(<CreateNamespaceStore match={{ params }} />);
-    const getNameSpy = jest.spyOn(selectors, 'getName');
-    expect(getNameSpy).toHaveBeenCalledWith({ metadata: { name: 'test' } });
+  it('pass the default namespace to the form when no namespace is received', () => {
+    render(<CreateNamespaceStore match={{ params: {} }} />);
+    expect(mockNamespaceStoreForm).toHaveBeenCalledWith(
+      expect.objectContaining({
+        namespace: CEPH_STORAGE_NAMESPACE,
+      })
+    );
   });
 });
```
2. Move the `NamespaceStoreForm` related tests that you implemented (the ones deleted on the patch) to the right file:
```namespace-store-form.spec.tsx```

2023-10-19 09:31 UTC, alfonsomthd commented
Closed in favor of https://github.com/red-hat-storage/odf-console/pull/1086

2023-10-19 09:31 UTC, closed without merging