Add cypress bucket-class test
red-hat-storage/odf-console pull request #86
Opened 2021-12-20 08:07 UTC by TimothyAsirJeyasing

Migrate cypress bucket-class test from ocs-console 
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2021-12-20 09:09 UTC, TimothyAsirJeyasing commented
@bipuladh , @afreen23, @vbnrh  Please review

2021-12-27 04:32 UTC, vbnrh requested changes
Please post screenshots of the tests too in the description

2021-12-27 04:32 UTC, vbnrh commented on cypress/views/common.ts
> +  navigateToOCS: (isOperatorsOpen = false) => {
Please change to go to the ODF page and then bucket class

2022-01-05 11:28 UTC, TimothyAsirJeyasing commented on cypress/views/common.ts
> +  navigateToOCS: (isOperatorsOpen = false) => {
Sure, will do it

2022-01-18 12:18 UTC, vbnrh commented on cypress/views/bc.ts
> +  commonFlows.navigateToODF();
```suggestion
 ODFCommon.visitStorageDashboard();
```

2022-01-18 12:21 UTC, vbnrh commented on cypress/cypress.json
> -  }
Why are we removing all these ?

2022-02-09 08:55 UTC, TimothyAsirJeyasing commented on cypress/cypress.json
> -  }
I found these attributes returns error during the test setup. Will try find the main cause and update accordingly

2022-02-14 09:44 UTC, TimothyAsirJeyasing commented on cypress/cypress.json
> -  }
I have taken these attribute in my latest push, Thank you

2022-02-17 07:00 UTC, bipuladh approved these changes
/lgtm

2022-05-18 07:02 UTC, bipuladh commented
/override ci/prow/odf-console-e2e-aws

2022-05-18 07:23 UTC, merged