Add Common Resource Dropdown Component
red-hat-storage/odf-console pull request #92
Opened 2022-01-13 11:34 UTC by bipuladh

Example:
![Screenshot from 2022-01-13 17-13-20](https://user-images.githubusercontent.com/54092533/149323099-c452e7a2-02ed-471e-bc5b-e8f688a3e2af.png)

2022-01-13 13:07 UTC, afreen23 requested changes

2022-01-13 13:07 UTC, afreen23 commented on packages/shared/selectors/k8s.ts
> +export const getUID: GetStringProperty = (resource) => resource.metadata?.uid;
if this is generic utility , then in usage resource can be undefined as well.

```suggestion
export const getName: GetStringProperty = (resource) => resource?.metadata?.name;

export const getUID: GetStringProperty = (resource) => resource?.metadata?.uid;
```

2022-01-13 13:07 UTC, afreen23 commented on packages/shared/dropdown/resourceDropdown.scss
> +}
can you use pf properties respectively

2022-01-13 13:07 UTC, afreen23 commented on packages/shared/dropdown/ResourceDropdown.tsx
> +    <span className="sr-only">{resourceModel.abbr.toLocaleUpperCase()}</span>
what is "sr-only" ?

2022-01-18 06:08 UTC, bipuladh commented on packages/shared/dropdown/resourceDropdown.scss
> +}
Which PF property?

2022-01-18 06:08 UTC, bipuladh commented on packages/shared/dropdown/ResourceDropdown.tsx
> +    <span className="sr-only">{resourceModel.abbr.toLocaleUpperCase()}</span>
This style is defined on console project.

2022-01-18 06:11 UTC, bipuladh commented
/assign @SanjalKatiyar

2022-01-18 06:52 UTC, SanjalKatiyar commented
**Few functionalities that can be added:**
1) LoadingInline component untill resources are loaded and error in case of loaderror.
2) A filtering prop, which will filter data before creating dropdown items.
3) If we are using this component as a StorageClass dropdown as well, then it should have one more functionality of pre-selecting `default` StorageClass if any initial `selection` is not provided by the parent component (if this functionality is not needed we can skip it and can make a new FC for SC dropdown instead).

2022-01-18 10:00 UTC, bipuladh commented
> **Few functionalities that can be added:**
> 
> 1. LoadingInline component untill resources are loaded and error in case of loaderror.
> 2. A filtering prop, which will filter data before creating dropdown items.
> 3. An initial `selection` prop, if we want any dropdown item pre-selected.
This and the 4th one is the same. You can implement 4 using the above prop.
> 4. If we are using this component as a StorageClass dropdown as well, then it should have one more functionality of pre-selecting `default` StorageClass if any initial `selection` is not provided by the parent component (if this functionality is not needed we can skip it or can make a new FC for SC dropdown as well).

2022-01-18 12:29 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +      setSelectedItem(item);
```suggestion
      setSelectedItem(item);
      onSelect(item);
```

2022-01-18 12:29 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +              Error Loading
```suggestion
              t('Error Loading')
```

2022-01-18 12:29 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +        onClick={onClick}
```suggestion
```
it's not doing anything, right ?

2022-01-18 12:43 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +            getName(res) && (filterResource ? filterResource(res) : true)
```suggestion
            getName(res)) && (filterResource ? filterResource(res) : true)
```

2022-01-18 12:44 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +            getName(res) && (filterResource ? filterResource(res) : true)
missing `)` else we are passing boolean value to `filterName` function.

2022-01-18 12:48 UTC, SanjalKatiyar commented on packages/shared/selectors/k8s.ts
> +import { K8sResourceCommon } from '@openshift-console/dynamic-plugin-sdk';
instead of creating a new directory, can we add these functions under `@odf/shared/utils` ??
(that's where I added them in migration PRs as well along with lot more different utilities)

2022-01-18 12:50 UTC, SanjalKatiyar commented on yarn.lock
> +
can we have one commit for `ResourceDropdown` FC & other for `package.json` (so 2 commits total for this PR) ??

2022-01-18 13:44 UTC, bipuladh commented on packages/shared/selectors/k8s.ts
> +import { K8sResourceCommon } from '@openshift-console/dynamic-plugin-sdk';
I think selectors are good here.

2022-01-18 15:05 UTC, SanjalKatiyar commented
/lgtm

2022-01-19 06:33 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2022-01-21 12:18 UTC, bipuladh commented
/test odf-console-e2e-aws

2022-01-21 13:50 UTC, bipuladh commented
/test ci/prow/lint

2022-01-21 13:51 UTC, bipuladh commented
/test lint

2022-01-21 13:55 UTC, merged