Add shared components
red-hat-storage/odf-console pull request #94
Opened 2022-01-17 14:20 UTC by SanjalKatiyar

On top of https://github.com/red-hat-storage/odf-console/pull/89

2022-01-17 14:21 UTC, SanjalKatiyar commented
/hold
needs to be reviewed.

2022-01-21 15:07 UTC, SanjalKatiyar commented on packages/shared/hooks/history.ts
> +(history as any).pushPath = (path) => (history as any).__push__(path);
I migrated this but is still some issue with the code, history was not working for me. Maybe we can merge this now and create a new issue later to fix the probable cause.

2022-01-21 15:18 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +
fairly new... added `ResourcesDropdown` similar to `ResourceDropdown` but new one can take multiple `resources` as an input and uses `useK8sWatchResources`.

2022-01-21 15:18 UTC, SanjalKatiyar commented on packages/shared/dropdown/singleselectdropdown.tsx
> +};
new

2022-01-21 15:19 UTC, SanjalKatiyar commented on packages/shared/hooks/sort-list.ts
> +};
new

2022-01-31 05:57 UTC, SanjalKatiyar commented on packages/shared/hooks/history.ts
> +}
Will remove it when I will rebase after https://github.com/red-hat-storage/odf-console/pull/89 is merged...

2022-02-03 06:32 UTC, SanjalKatiyar commented on packages/shared/dropdown/ResourceDropdown.tsx
> +
ptal... new component...

2022-02-03 06:44 UTC, SanjalKatiyar commented
/hold cancel

2022-02-03 06:45 UTC, SanjalKatiyar commented
/assign @bipuladh 
First PR #89 out of 4 got merged. This one needs to go second.

2022-02-04 04:18 UTC, bipuladh requested changes

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/utils/common.ts
> +) => (_.has(value, 'metadata.annotations') ? value.metadata.annotations : defaultValue);
https://github.com/red-hat-storage/odf-console/blob/master/packages/shared/selectors/k8s.ts

Add them here or resuse from here.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/utils/common.ts
> +) => k8sPatch({model: kind, resource: { metadata: { name, namespace } }, data: data}) as Promise<any>;
```suggestion
) => k8sPatch({model: kind, resource: { metadata: { name, namespace } }, data: data}) as Promise<any>;
```
Add proper types for Promise.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/types/storage.ts
> +    // https://pkg.go.dev/github.com/red-hat-storage/ocs-operator/api/v1#StorageCluster
```suggestion
```

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/storage/pvc/pvs-available-capacity.tsx
> +        <strong>{t('Available capacity:')}</strong>
Don't change these here. It's being handled by https://github.com/red-hat-storage/odf-console/pull/106

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/status/statuses.tsx
> +      title={props.title || t('Healthy')}
Don't fix i18n here. It's handled by https://github.com/red-hat-storage/odf-console/pull/106.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/models/console-models.ts
> +import { K8sKind } from '@openshift-console/dynamic-plugin-sdk/lib/api/common-types';
These should be part of common.ts. These CRDs are not console specific.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/hooks/sort-list.ts
> +  // columns is not a state variable so its value will not change, but its reference might change on every re-render of parent component
Use `JSON.stringify`

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/hooks/sort-list.ts
> +export const useSortList = <R extends K8sResourceCommon>(
aren't sorting of lists handled by the Table Component itself?

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/hooks/history.ts
> +(history as any).pushPath = (path) => (history as any).__push__(path);
Instead of doing this? Can you please point the extension point which is not injecting history and we can discuss how to solve that issue.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/generic/status-box.tsx
> +import * as _ from 'lodash-es';
```suggestion
import * as _ from 'lodash';
```

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/generic/promise-component.tsx
> +import * as React from 'react';
This is an unnecessary component. We can directly handle the return value of the network calls without using this. I would prefer a hook over a HoC as well. Let's not bring this in.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/dropdown/singleselectdropdown.tsx
> +  };
Wrap it in a React.useCallback.

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/dropdown/singleselectdropdown.tsx
> +    <div>
```suggestion
    <div>
```
Why is this div required?

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/dropdown/multiselectdropdown.tsx
> +export const MultiSelectDropdown: React.FC<MultiSelectDropdownProps> = ({
What is this component used for?

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/dropdown/multiselectdropdown.tsx
> +    <div>
```suggestion
    <div>
```
Is this really required?

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/dropdown/multiselectdropdown.tsx
> +  });
```suggestion
  const items: JSX.Element[] = options.map((item) => <SelectOption key={item} value={item} />);
```

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/dropdown/ResourceDropdown.tsx
> +
lgtm

2022-02-04 04:18 UTC, bipuladh commented on packages/shared/constants/common.ts
> +export const MIN_SPEC_RESOURCES: StorageClusterResource = {
This is ODF specific move it to odf package. Or add it as part of installation flow. This is not a shared component.

2022-02-08 09:02 UTC, SanjalKatiyar commented on packages/shared/dropdown/multiselectdropdown.tsx
> +export const MultiSelectDropdown: React.FC<MultiSelectDropdownProps> = ({
this is used in LSO filtering step, to select multiple items from the dropdown... this is not a new component...

2022-02-08 09:05 UTC, SanjalKatiyar commented on packages/shared/dropdown/multiselectdropdown.tsx
> +    <div>
not sure why exactly this was added... this is old component, I just copied it here...

2022-02-08 09:20 UTC, SanjalKatiyar commented on packages/shared/generic/promise-component.tsx
> +import * as React from 'react';
I would request to let's have it for now... this component also injects `errorMessage` & `inProgress` to the modal component which otherwise we would have to handle ourselves (like we are doing in add-capacity modal) and thus requiring addition of extra code.
wdyt ??

2022-02-08 09:23 UTC, SanjalKatiyar commented on packages/shared/hooks/history.ts
> +(history as any).pushPath = (path) => (history as any).__push__(path);
when I last checked, this was not passing downthe `history` to its `codeRef`:
```
{
  "type": "console.resource/create",
  "properties": {
    "model": {
      "group": "operator.tekton.dev",
      "version": "v1alpha1",
      "kind": "TektonConfig"
    },
    "component": { "$codeRef": "fooComp" }
  }
}
```
PR: https://github.com/openshift/console/pull/9395

2022-02-08 09:25 UTC, SanjalKatiyar commented on packages/shared/hooks/sort-list.ts
> +export const useSortList = <R extends K8sResourceCommon>(
it is same as `useSelectList` componenet. I had to pass `useSortList` same as we are doing with `useSelectList`.

2022-02-08 11:27 UTC, SanjalKatiyar commented on packages/shared/hooks/sort-list.ts
> +export const useSortList = <R extends K8sResourceCommon>(
I have used `Table` component from PatternFly for select-node-table (mainly because of select functionality) which requires `useSelectList` & `useSortList`.

2022-02-08 12:32 UTC, SanjalKatiyar commented on packages/shared/constants/common.ts
> +export const MIN_SPEC_RESOURCES: StorageClusterResource = {
will add as a part of installation flow.

2022-02-08 12:44 UTC, SanjalKatiyar commented on packages/shared/hooks/sort-list.ts
> +  // columns is not a state variable so its value will not change, but its reference might change on every re-render of parent component
IMO it would be an unnecessary computation. `columns` is a static data and would not change dynamically ever, and if we know that we can directly skip it from dependency array, no need to convert to string and check for equality.

2022-02-08 12:48 UTC, SanjalKatiyar commented on packages/shared/models/console-models.ts
> +import { K8sKind } from '@openshift-console/dynamic-plugin-sdk/lib/api/common-types';
reason why I did not add them to `common.ts` because it has all the CRDs which are by default provided by K8s.
`console-models` has more of a custom CRDs provided by us. 
Plz let me know ur thoughts in case I am wrong ??

2022-02-08 13:36 UTC, bipuladh commented on packages/shared/generic/promise-component.tsx
> +import * as React from 'react';
okay

2022-02-09 04:40 UTC, bipuladh commented
/approve
/lgtm

2022-02-09 04:41 UTC, merged