Fixes filesystem provider details
red-hat-storage/odf-console pull request #951
Opened 2023-08-08 07:57 UTC by vbnrh

This commit fixes the provider details in namespacestore details page.

2023-08-09 06:35 UTC, SanjalKatiyar commented on packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
> -        <CardTitle>{t('System capacity')}</CardTitle>
let's keep this as part of its corresponding BZ... this change has nothing to do with this PR...

2023-08-09 06:37 UTC, SanjalKatiyar commented on locales/en/plugin__odf-console.json
> +  "PVC Name": "PVC Name",
```suggestion
  "PVC name": "PVC name",
```

2023-08-09 06:40 UTC, SanjalKatiyar commented on packages/odf/constants/mcg.ts
> +  FILESYSTEM = 'nsfs',
won't this affect what we show on the dropdown as well ??
if we need to show `nsfs` as the dropdown item we need to confirm this with UX and also capitalise it...

2023-08-09 06:43 UTC, SanjalKatiyar commented on packages/odf/components/resource-pages/Providers.tsx
> +        <DetailsItem field={t('PVC Name')}>{pvcName}</DetailsItem>
```suggestion
        <DetailsItem field={t('PersistentVolumeClaim')}>{pvcName}</DetailsItem>
```

2023-08-09 06:44 UTC, SanjalKatiyar commented on packages/odf/components/resource-pages/Providers.tsx
> +        <DetailsItem field={t('PVC Name')}>{pvcName}</DetailsItem>
basically making it same as what's displayed on the form...

2023-08-10 11:26 UTC, bipuladh requested changes

2023-08-10 11:26 UTC, bipuladh commented on packages/odf/components/resource-pages/Providers.tsx
> +  const pvcName = (resource as NamespaceStoreKind).spec.nsfs.pvcName;
Allow ProviderDetailsProps to take a type generic 
ProviderDetailsProps<NamespaceStoreKind>
This should stop us from using `as` here and multiple other places.

2023-08-10 11:49 UTC, vbnrh commented on packages/odf/constants/mcg.ts
> +  FILESYSTEM = 'nsfs',
i am changing this back to Filesystem. The map has the correct value as nsfs.

2023-08-10 11:49 UTC, vbnrh commented on packages/odf/components/odf-dashboard/system-capacity-card/capacity-card.tsx
> -        <CardTitle>{t('System capacity')}</CardTitle>
Got accidentally added before i stashed the other changes.

2023-08-10 11:49 UTC, vbnrh commented on packages/odf/components/resource-pages/Providers.tsx
> +  const pvcName = (resource as NamespaceStoreKind).spec.nsfs.pvcName;
```
type ProviderDetailsProps = {
  resource: BackingStoreKind | NamespaceStoreKind;
};
```
This was already there so i am removing the type casting.

2023-08-14 04:59 UTC, SanjalKatiyar commented
/cherry-pick release-4.14-compatibility

2023-08-14 04:59 UTC, SanjalKatiyar commented
/cherry-pick release-4.14

2023-08-14 04:59 UTC, SanjalKatiyar commented
/test odf-console-e2e-aws

2023-08-14 04:59 UTC, SanjalKatiyar commented
/approve
/lgtm

2023-08-14 06:31 UTC, merged

2023-08-23 09:53 UTC, vbnrh commented
/cherry-pick release-4.13

2023-08-23 09:53 UTC, vbnrh commented
/cherry-pick release-4.13-compatibility