Running OCP console as a container
red-hat-storage/odf-console pull request #972
Opened 2023-08-16 10:42 UTC by GowthamShanmugam

2023-08-16 10:50 UTC, alfonsomthd requested changes

2023-08-16 10:50 UTC, alfonsomthd commented on start-ocp-console.sh
> +      --pull always --rm -p "$CONSOLE_PORT":9000 \
Same as above.

2023-08-16 12:17 UTC, SanjalKatiyar commented
1. we have `scripts` directory, might be a good place for this file as well
2. also, can we have separate commands for running OCP as container or locally ??

2023-08-16 12:18 UTC, SanjalKatiyar commented on start-ocp-console.sh
> +fi
isn't it more of a related to mco, and not concerning to odf ?

2023-08-16 12:24 UTC, alfonsomthd requested changes

2023-08-16 12:24 UTC, alfonsomthd commented on start-ocp-console.sh
> +BRIDGE_PLUGINS="odf-console=http://localhost:9001"
Let's read the active plugins from environment:
```suggestion
BRIDGE_PLUGINS=${BRIDGE_PLUGINS:=odf-console=http://localhost:9001}
```

2023-08-16 12:43 UTC, GowthamShanmugam commented on start-ocp-console.sh
> +fi
I dont know why OCP keeping this on a common file: https://github.com/openshift/console/commits/master/contrib/oc-environment.sh

I need to figure the purpose of this

2023-08-17 06:01 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
if I just run `yarn dev-mco:c` it will bridge to `odf-console` not `mco-console`, why not pass the value of `BRIDGE_PLUGINS` from here...
and for cases where we need to run multiple plugins together, maybe a new command for that or just document it in the ReadMe...

2023-08-17 06:06 UTC, alfonsomthd commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
BRIDGE_PLUGINS config is read from the environment, [it shouldn't be hardcoded](https://12factor.net/config).

2023-08-17 06:14 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
that is fine as well, point here is `if I just run yarn dev-mco:c it will bridge to odf-console not mco-console`

2023-08-17 06:18 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
and to document the steps...

2023-08-17 06:19 UTC, alfonsomthd commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
@SanjalKatiyar If I understand you correctly, your suggestion would be to add the proper `default` to the command (but still having preference the environment), sth like adding:
`BRIDGE_PLUGINS=${BRIDGE_PLUGINS:=odf-multicluster-console="http://localhost:9002"}`.
It makes sense.

2023-08-17 06:26 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
"BRIDGE_PLUGINS" is nothing but constant values like "PLUGIN" or "I8N_NS"... which are not gonna change...

2023-08-17 06:27 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
"BRIDGE_PLUGINS" is nothing but constant values like "PLUGIN" or "I8N_NS"... which are not gonna change much often...

2023-08-17 06:31 UTC, SanjalKatiyar commented
@GowthamShanmugam for running locally can't we serve mco as diff port ?? right now both odf/mco runs on 9001

2023-08-17 06:45 UTC, alfonsomthd commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
BRIDGE_PLUGINS is part of the config (not constant), so I always should be able to run this:
`BRIDGE_PLUGINS="odf-console=http://localhost:9001,fusion-console=http://localhost:9010" yarn dev:c` so it makes sense to set sensible defaults but never hardcoding: it's against the best practices.

2023-08-17 06:55 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
`so it makes sense to set sensible defaults but never hardcoding: it's against the best practices.` >> I think there is some communication gap here, passing it as a process.env is what I was suggesting (which is not a case right now if u run `yarn dev-mco:c`) and not to hardcode on `.sh` file...

also, followup on the last comment, it is little bit confusing, this is "odf-console" repo, but we want to pass "fusion-console" to a script which is defined in entirely diff repo (I can understand it will work)... but @GowthamShanmugam do we need to add script to this repo, doesn't OCP themselves provides a way/script to run it as a container ?? Why do we want to run `yarn ocp-console` from our repo, if console provides the script we can just run from there ??

2023-08-17 07:00 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
btw these are just some questions from my side on quickly going over this PR... I don't have any major issues from my side...

2023-08-17 07:08 UTC, SanjalKatiyar commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
`yarn dev-mco:c` >> passes value for mco-console
`yarn dev:c` >> passes value for odf-console
and other cases we might document the steps... which will to run `BRIDGE_PLUGINS="odf-console=http://localhost:9001,fusion-console=http://localhost:9010"  yarn ocp-console`

2023-08-17 07:12 UTC, GowthamShanmugam commented on start-ocp-console.sh
> +BRIDGE_PLUGINS="odf-console=http://localhost:9001"
https://github.com/red-hat-storage/odf-console/pull/972#issue-1852974243

2023-08-17 07:20 UTC, GowthamShanmugam commented
> @GowthamShanmugam for running locally can't we serve mco at diff port ?? right now both odf/mco runs on 9001

For now, we won't have any use case like running ODF and MCO together, it becomes more complicated when we need to run ODF on multiple clusters. For ODF console i user public URL and for MCO i use local setup.

2023-08-17 07:33 UTC, GowthamShanmugam commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
may you can add this script on fusion-console repo also

2023-08-17 07:46 UTC, GowthamShanmugam commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
I really dont like keeping separate yarn commands for different consoles, lets make everything generic and let all values come from the Env:
"dev:c": "yarn ocp-console & PLUGIN=${PLUGIN} I8N_NS=${I8N_NS} yarn server:plugin"

2023-08-17 08:22 UTC, alfonsomthd commented on package.json
> +    "dev-mco:c": "yarn ocp-console & PLUGIN=mco I8N_NS=plugin__odf-multicluster-console yarn server:plugin",
> also, followup on the last comment, it is little bit confusing, this is "odf-console" repo, but we want to pass "fusion-console" to a script which is defined in entirely diff repo (I can understand it will work)... but 

It's just an example (it could another related plugin), don't be so literal :wink: The point here is that config should not be hardcoded as can change based on different deploys/envs/needs.

2023-08-17 08:52 UTC, alfonsomthd commented on README.md
> +5. Run the development mode of odf-console using `I8N_NS=plugin__odf-console PLUGIN=odf yarn run dev:c`. This runs a webserver in port 9001.
```suggestion
5. Run the development mode of odf-console using `I8N_NS=plugin__odf-console PLUGIN=odf yarn run dev:c`. This runs a container running both the console bridge and a webserver in port 9001.
```

2023-08-17 09:06 UTC, GowthamShanmugam commented on README.md
> +5. Run the development mode of odf-console using `I8N_NS=plugin__odf-console PLUGIN=odf yarn run dev:c`. This runs a webserver in port 9001.
ack

2023-08-17 10:36 UTC, alfonsomthd commented
/lgtm

2023-08-17 11:06 UTC, GowthamShanmugam commented
/assign @SanjalKatiyar 
need your approval

2023-08-22 06:27 UTC, SanjalKatiyar commented on package.json
> +    "dev:c": "yarn ocp-console & PLUGIN=${PLUGIN} I8N_NS=${I8N_NS} yarn server:plugin & wait"
this will start a local server for plugin as well, why do we need `wait` here ?? do we need to wait for some process completion ??

2023-08-22 06:38 UTC, GowthamShanmugam commented on package.json
> +    "dev:c": "yarn ocp-console & PLUGIN=${PLUGIN} I8N_NS=${I8N_NS} yarn server:plugin & wait"
Here, We are using (&) to run the two concurrent servers (OCP and odf-console). But (&) on prevents the command from responding to C-c/C-z and also prevents its return code from propagating in case of a failure.

So it will keep running the one server even when another one is failed. We need to kill the job to stop the other server. 

Here, Wait command will wait for the children to be killed and it will makesure clean exit.

2023-08-22 06:49 UTC, SanjalKatiyar commented
/approve

2023-08-22 09:20 UTC, merged